In [1]:
pip install wordcloud seaborn scipy

Requirement already satisfied: wordcloud in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (1.9.4)
Requirement already satisfied: seaborn in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: scipy in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (1.16.1)
Requirement already satisfied: numpy>=1.6.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from wordcloud) (2.3.1)
Requirement already satisfied: pillow in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from wordcloud) (3.10.3)
Requirement already satisfied: pandas>=1.2 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from seaborn) (2.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import json
import pandas as pd

In [3]:
def get_written_dates_and_any_text_file_locations_to_dataframe(root_folder):
    print(f"--- Starting Scan for metadata.json and any associated non-JSON text files ---")
    print(f"Scanning root folder: {os.path.abspath(root_folder)}\n")

    if not os.path.exists(root_folder):
        print(f"Error: The root folder '{root_folder}' does not exist at '{os.path.abspath(root_folder)}'.")
        return pd.DataFrame()

    data_for_df = []
    
    for dirpath, dirnames, filenames in os.walk(root_folder):
        metadata_filepath_in_dir = None
        text_file_path_in_dir = None
        
        non_json_files = []

        # First, identify the metadata.json and any non-JSON files in the current directory
        for filename in filenames:
            if filename.lower() == "metadata.json":
                metadata_filepath_in_dir = os.path.join(dirpath, filename)
            elif filename.lower().endswith(".txt"): # Consider anything that's not JSON as a potential text file
                non_json_files.append(os.path.join(dirpath, filename))

        # Check conditions for a valid pair
        if metadata_filepath_in_dir:
            if len(non_json_files) == 1:
                # Exactly one non-JSON file found, assume it's the text file
                text_file_path_in_dir = non_json_files[0]
                
                print(f"Processing directory: {os.path.abspath(dirpath)}")
                print(f"  Found metadata.json: {metadata_filepath_in_dir}")
                print(f"  Found associated text file: {text_file_path_in_dir}")

                extracted_written_date = None
                try:
                    with open(metadata_filepath_in_dir, 'r', encoding='utf-8') as f:
                        metadata = json.load(f)
                        if 'written_date' in metadata:
                            extracted_written_date = metadata['written_date']
                            print(f"  Extracted 'written_date': '{extracted_written_date}'")
                        else:
                            print(f"  Warning: 'written_date' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")
                except json.JSONDecodeError as e:
                    print(f"  Error: Could not parse JSON from {metadata_filepath_in_dir}: {e}. Setting 'written_date' to None.")
                except Exception as e:
                    print(f"  An unexpected error occurred reading {metadata_filepath_in_dir}: {e}. Setting 'written_date' to None.")
                
                # Add this pair to our DataFrame data
                data_for_df.append({
                    'written_date': extracted_written_date,
                    'text_file_location': os.path.abspath(text_file_path_in_dir)
                })
                
            elif len(non_json_files) == 0:
                print(f"  Note: Found metadata.json in {os.path.abspath(dirpath)} but NO non-JSON text file found. Skipping this directory.")
            else: # len(non_json_files) > 1
                print(f"  Warning: Found metadata.json in {os.path.abspath(dirpath)} but MULTIPLE non-JSON files ({non_json_files}). Cannot determine which is the text file. Skipping this directory.")
        # No else for when metadata.json is not found at all, to keep output cleaner

    print(f"\n--- Scan Complete ---")
    print(f"Total valid pairs (metadata.json + single non-JSON text file): {len(data_for_df)}")
    
    df = pd.DataFrame(data_for_df)

    if df.empty:
        print("No valid pairs of metadata.json and single non-JSON text file found to create a DataFrame.")
    else:
        print("\n--- Resulting DataFrame Head ---")
        print(df.head())
        print(f"\nDataFrame has {len(df)} rows and {len(df.columns)} columns.")
    
    return df

In [4]:
root_directory_to_scan = "data/OCR_Final"

list_of_file_locations = get_written_dates_and_any_text_file_locations_to_dataframe(root_directory_to_scan)

--- Starting Scan for metadata.json and any associated non-JSON text files ---
Scanning root folder: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final

Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව
  Found metadata.json: data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/metadata.json
  Found associated text file: data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව.txt
  Extracted 'written_date': '1187 - 1225'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/නිදහසේ මන්ත්‍රය
  Found metadata.json: data/OCR_Final/නිදහසේ මන්ත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/නිදහසේ මන්ත්‍රය/නිදහසේ මන්ත්‍රය.txt
  Extracted 'written_date': '1901 - 1938'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/පැරණි ගම
  Found metadata.json: data/OCR_Final/පැරණි ගම/metadata.json
  Found associated text file: data/OCR_Final/පැරණි ගම/පැරණි ගම.txt
  Extracted 'written_date': '1944'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/පන්සිය පනස් ජාතක පොත
  Found metadata.json: data/OCR_Final/පන්සිය පනස් ජාතක පොත/metadata.json
  Found associated text file: data/OCR_Final/පන්සිය පනස් ජාතක පොත/පන්සිය පනස් ජාතක පොත.txt
  Extracted 'written_date': '1303 - 1333'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/හිතෝපදේශ සන්නය
  Found metadata.json: data/OCR_Final/හිතෝපදේශ සන්නය/metadata.json
  Found associated text file: data/OCR_Final/හිතෝපදේශ සන්නය/හිතෝපදේශ සන්නය.txt
  Extracted 'written_date': '1825 - 1905'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/අධිමාස සංග්‍රහව
  Found metadata.json: data/OCR_Final/අධිමාස සංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/අධිමාස සංග්‍රහව/අධිමාස සංග්‍රහව.txt
  Extracted 'written_date': '1850 - 1903'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/දහම් සරණ.txt
  Found metadata.json: data/OCR_Final/දහම් සරණ.txt/metadata.json
  Found associated text file: data/OCR_Final/දහම් සරණ.txt/දහම් සරණ.txt
  Extracted 'written_date': '1220 - 1293'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/දුර්වාදී හෘදය විදාරණය
  Found metadata.json: data/OCR_Final/දුර්වාදී හෘදය විදාරණය/metadata.json
  Found associated text file: data/OCR_Final/දුර්වාදී හෘදය විදාරණය/දුර්වාදී හෘදය විදාරණය.txt
  Extracted 'written_date': '1854 - 1899'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව
  Found metadata.json: data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව.txt
  Extracted 'written_date': '1706 - 1739'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ජුබිලි වර්ණනාව
  Found metadata.json: data/OCR_Final/ජුබිලි වර්ණනාව/metadata.json
  Found associated text file: data/OCR_Final/ජුබිලි වර්ණනාව/ජුබිලි වර්ණනාව.txt
  Extracted 'written_date': '1857 - 1922'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සිතියම් සහිත සද්ධර්මාලංකාරය
  Found metadata.json: data/OCR_Final/සිතියම් සහිත සද්ධර්මාලංකාරය/metadata.json
  Found associated text file: data/OCR_Final/සිතියම් සහිත සද්ධර්මාලංකාරය/සිතියම් සහිත සද්ධර්මාලංකාරය.txt
  Extracted 'written_date': '1398 - 1410'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/හංස සංදේශය
  Found metadata.json: data/OCR_Final/හංස සංදේශය/metadata.json
  Found associated text file: data/OCR_Final/හංස සංදේශය/හංස සංදේශය.txt
  Extracted 'written_date': '1457 - 1465'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/මහාවංස ටීකා
  Found metadata.json: data/OCR_Final/මහාවංස ටීකා/metadata.json
  Found associated text file: data/OCR_Final/මහාවංස ටීකා/මහාවංස ටීකා.txt
  Extracted 'written_date': '1827 - 1895'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ධම්පියා අටුවා ගැටපදය
  Found metadata.json: data/OCR_Final/ධම්පියා අටුවා ගැටපදය/metadata.json
  Found associated text file: data/OCR_Final/ධම්පියා අටුවා ගැටපදය/ධම්පියා අටුවා ගැටපදය.txt
  Extracted 'written_date': '1868 - 1932'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සන්න සහිත සැලළිහිණි සන්දේශය
  Found metadata.json: data/OCR_Final/සන්න සහිත සැලළිහිණි සන්දේශය/metadata.json
  Found associated text file: data/OCR_Final/සන්න සහිත සැලළිහිණි සන්දේශය/සන්න සහිත සැලළිහිණි සන්දේශය.txt
  Extracted 'written_date': '1450'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/කාව්‍ය වජ්‍රායුධය - පළමු කොටස
  Found metadata.json: data/OCR_Final/කාව්‍ය වජ්‍රායුධය - පළමු කොටස/metadata.json
  Found associated text file: data/OCR_Final/කාව්‍ය වජ්‍රායුධය - පළමු කොටස/කාව්‍ය වජ්‍රායුධය - පළමු කොටස.txt
  Extracted 'written_date': '1825 - 1893'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සද්ධර්ම රත්නාවලිය - ප්‍රථම භාගය
  Found metadata.json: data/OCR_Final/සද්ධර්ම රත්නාවලිය - ප්‍රථම භාගය/metadata.json
  Found associated text file: data/OCR_Final/සද්ධර්ම රත්නාවලිය - ප්‍රථම භාගය/සද්ධර්ම රත්නාවලිය - ප්‍රථම භාගය.txt
  Extracted 'written_date': '1220 - 1293'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/දළදා පූජාවලිය
  Found metadata.json: data/OCR_Final/දළදා පූජාවලිය/metadata.json
  Found associated text file: data/OCR_Final/දළදා පූජාවලිය/දළදා පූජාවලිය.txt
  Extracted 'written_date': '1325 - 1333'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය
  Found metadata.json: data/OCR_Final/නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය/metadata.json
  Found associated text file: data/OCR_Final/නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය/නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය.txt
  Extracted 'written_date': '1390'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සිතියම් සහිත මහියංගන වර්ණනාව
  Found metadata.json: data/OCR_Final/සිතියම් සහිත මහියංගන වර්ණනාව/metadata.json
  Found associated text file: data/OCR_Final/සිතියම් සහිත මහියංගන වර්ණනාව/සිතියම් සහිත මහියංගන වර්ණනාව.txt
  Extracted 'written_date': '1878'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සිතියම් සහිත සියබස් මල්දම
  Found metadata.json: data/OCR_Final/සිතියම් සහිත සියබස් මල්දම/metadata.json
  Found associated text file: data/OCR_Final/සිතියම් සහිත සියබස් මල්දම/සිතියම් සහිත සියබස් මල්දම.txt
  Extracted 'written_date': '1820'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/විබත් මල්දම
  Found metadata.json: data/OCR_Final/විබත් මල්දම/metadata.json
  Found associated text file: data/OCR_Final/විබත් මල්දම/විබත් මල්දම.txt
  Extracted 'written_date': '1821'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/කාව්‍යෙශ්ඛරය
  Found metadata.json: data/OCR_Final/කාව්‍යෙශ්ඛරය/metadata.json
  Found associated text file: data/OCR_Final/කාව්‍යෙශ්ඛරය/කාව්‍යෙශ්ඛරය.txt
  Extracted 'written_date': '1408 - 1491'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සංස්කෘත ශබ්ධමාලාව හෙවත් සංස්කෘත නාම වරනැගිල්ල.txt
  Found metadata.json: data/OCR_Final/සංස්කෘත ශබ්ධමාලාව හෙවත් සංස්කෘත නාම වරනැගිල්ල.txt/metadata.json
  Found associated text file: data/OCR_Final/සංස්කෘත ශබ්ධමාලාව හෙවත් සංස්කෘත නාම වරනැගිල්ල.txt/සංස්කෘත ශබ්ධමාලාව හෙවත් සංස්කෘත නාම වරනැගිල්ල.txt
  Extracted 'written_date': '1828 - 1887'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/අධිමාස දීපනය
  Found metadata.json: data/OCR_Final/අධිමාස දීපනය/metadata.json
  Found associated text file: data/OCR_Final/අධිමාස දීපනය/අධිමාස දීපනය.txt
  Extracted 'written_date': '1850 - 1896'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සිංහල ව්‍යාකරණය එනම් සිදත් සඟරාව
  Found metadata.json: data/OCR_Final/සිංහල ව්‍යාකරණය එනම් සිදත් සඟරාව/metadata.json
  Found associated text file: data/OCR_Final/සිංහල ව්‍යාකරණය එනම් සිදත් සඟරාව/සිංහල ව්‍යාකරණය එනම් සිදත් සඟරාව.txt
  Extracted 'written_date': '1827 - 1911'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය
  Found metadata.json: data/OCR_Final/අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය/metadata.json
  Found associated text file: data/OCR_Final/අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය/අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය.txt
  Extracted 'written_date': '1916'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/අධිමාස විනිශ්චය
  Found metadata.json: data/OCR_Final/අධිමාස විනිශ්චය/metadata.json
  Found associated text file: data/OCR_Final/අධිමාස විනිශ්චය/අධිමාස විනිශ්චය.txt
  Extracted 'written_date': '1850 - 1904'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/මුවදෙව් දා විවරණය
  Found metadata.json: data/OCR_Final/මුවදෙව් දා විවරණය/metadata.json
  Found associated text file: data/OCR_Final/මුවදෙව් දා විවරණය/මුවදෙව් දා විවරණය.txt
  Extracted 'written_date': '1887 - 1944'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ධර්මප්‍රදීපිකාව
  Found metadata.json: data/OCR_Final/ධර්මප්‍රදීපිකාව/metadata.json
  Found associated text file: data/OCR_Final/ධර්මප්‍රදීපිකාව/ධර්මප්‍රදීපිකාව.txt
  Extracted 'written_date': '1187 - 1225'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සාරාර්ථ සංග්‍රහව ප්‍රථම භාගය
  Found metadata.json: data/OCR_Final/සාරාර්ථ සංග්‍රහව ප්‍රථම භාගය/metadata.json
  Found associated text file: data/OCR_Final/සාරාර්ථ සංග්‍රහව ප්‍රථම භාගය/සාරාර්ථ සංග්‍රහව ප්‍රථම භාගය.txt
  Extracted 'written_date': '398 - 426'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සිතියම් සහිත සිංහල මහාවංශය
  Found metadata.json: data/OCR_Final/සිතියම් සහිත සිංහල මහාවංශය/metadata.json
  Found associated text file: data/OCR_Final/සිතියම් සහිත සිංහල මහාවංශය/සිතියම් සහිත සිංහල මහාවංශය.txt
  Extracted 'written_date': '1874'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/බුද්ධ සික්ඛා
  Found metadata.json: data/OCR_Final/බුද්ධ සික්ඛා/metadata.json
  Found associated text file: data/OCR_Final/බුද්ධ සික්ඛා/බුද්ධ සික්ඛා.txt
  Extracted 'written_date': '1270 - 1293'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/මොග්ගලලායනව්‍යාකරණං
  Found metadata.json: data/OCR_Final/මොග්ගලලායනව්‍යාකරණං/metadata.json
  Found associated text file: data/OCR_Final/මොග්ගලලායනව්‍යාකරණං/මොග්ගලලායනව්‍යාකරණං.txt
  Extracted 'written_date': '1070 - 1232'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/අනාගතවංශය  මෙතේ බුදු සිරිත
  Found metadata.json: data/OCR_Final/අනාගතවංශය  මෙතේ බුදු සිරිත/metadata.json
  Found associated text file: data/OCR_Final/අනාගතවංශය  මෙතේ බුදු සිරිත/අනාගතවංශය මෙතේ බුදු සිරිත.txt
  Extracted 'written_date': '1325 - 1333'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/සන්න සහිත අභිසම්බෝධි අලංකාරය
  Found metadata.json: data/OCR_Final/සන්න සහිත අභිසම්බෝධි අලංකාරය/metadata.json
  Found associated text file: data/OCR_Final/සන්න සහිත අභිසම්බෝධි අලංකාරය/සන්න සහිත අභිසම්බෝධි අලංකාරය.txt
  Extracted 'written_date': '1698 - 1778'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ඔකඳපොල සන්නය හෙවත් බාලාවතාර ලියන සන්න
  Found metadata.json: data/OCR_Final/ඔකඳපොල සන්නය හෙවත් බාලාවතාර ලියන සන්න/metadata.json
  Found associated text file: data/OCR_Final/ඔකඳපොල සන්නය හෙවත් බාලාවතාර ලියන සන්න/ඔකඳපොල සන්නය හෙවත් බාලාවතාර ලියන සන්න.txt
  Extracted 'written_date': '1760 - 1778'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/කුදුසික
  Found metadata.json: data/OCR_Final/කුදුසික/metadata.json
  Found associated text file: data/OCR_Final/කුදුසික/කුදුසික.txt
  Extracted 'written_date': '1270 - 1293'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/මොග්ගල්ලාන පංචිකා ප්‍රදීපය
  Found metadata.json: data/OCR_Final/මොග්ගල්ලාන පංචිකා ප්‍රදීපය/metadata.json
  Found associated text file: data/OCR_Final/මොග්ගල්ලාන පංචිකා ප්‍රදීපය/මොග්ගල්ලාන පංචිකා ප්‍රදීපය.txt
  Extracted 'written_date': '1070 - 1232'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/කුසජාතක විවරණය (ප්‍රථම භාගය)
  Found metadata.json: data/OCR_Final/කුසජාතක විවරණය (ප්‍රථම භාගය)/metadata.json
  Found associated text file: data/OCR_Final/කුසජාතක විවරණය (ප්‍රථම භාගය)/කුසජාතක විවරණය (ප්‍රථම භාගය).txt
  Extracted 'written_date': '1887 - 1932'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ව්‍යාකරණ විවරණය හෙවත් සිංහල භාෂාවේ ව්‍යාකරණය
  Found metadata.json: data/OCR_Final/ව්‍යාකරණ විවරණය හෙවත් සිංහල භාෂාවේ ව්‍යාකරණය/metadata.json
  Found associated text file: data/OCR_Final/ව්‍යාකරණ විවරණය හෙවත් සිංහල භාෂාවේ ව්‍යාකරණය/ව්‍යාකරණ විවරණය හෙවත් සිංහල භාෂාවේ ව්‍යාකරණය.txt
  Extracted 'written_date': '1887 - 1937'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/පරවි සංදේශය
  Found metadata.json: data/OCR_Final/පරවි සංදේශය/metadata.json
  Found associated text file: data/OCR_Final/පරවි සංදේශය/පරවි සංදේශය.txt
  Extracted 'written_date': '1430 - 1440'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ගඩලාදෙණි සන්නයයි ප්‍රසිද්ධ වූ බාලාවතාරේ පුරාණ ව්‍යාඛ්‍යානය
  Found metadata.json: data/OCR_Final/ගඩලාදෙණි සන්නයයි ප්‍රසිද්ධ වූ බාලාවතාරේ පුරාණ ව්‍යාඛ්‍යානය/metadata.json
  Found associated text file: data/OCR_Final/ගඩලාදෙණි සන්නයයි ප්‍රසිද්ධ වූ බාලාවතාරේ පුරාණ ව්‍යාඛ්‍යානය/ගඩලාදෙණි සන්නයයි ප්‍රසිද්ධ වූ බාලාවතාරේ පුරාණ ව්‍යාඛ්‍යානය.txt
  Extracted 'written_date': '1827 - 1911'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/මගේ මල්ලි
  Found metadata.json: data/OCR_Final/මගේ මල්ලි/metadata.json
  Found associated text file: data/OCR_Final/මගේ මල්ලි/මගේ මල්ලි.txt
  Extracted 'written_date': '1886 - 1938'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/ලියනෝරා නාඩගම
  Found metadata.json: data/OCR_Final/ලියනෝරා නාඩගම/metadata.json
  Found associated text file: data/OCR_Final/ලියනෝරා නාඩගම/ලියනෝරා නාඩගම.txt
  Extracted 'written_date': '1852 - 1927'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/නිකම් හැකියාව
  Found metadata.json: data/OCR_Final/නිකම් හැකියාව/metadata.json
  Found associated text file: data/OCR_Final/නිකම් හැකියාව/නිකම් හැකියාව.txt
  Extracted 'written_date': '1887 - 1941'

--- Scan Complete ---
Total valid pairs (metadata.json + single non-JSON text file): 46

--- Resulting DataFrame Head ---
  written_date                                 text_file_location
0  1187 - 1225  /Users/nevidujayatilleke/Documents/MSC - Resea...
1  1901 - 1938  /Users/nevidujayatilleke/Documents/MSC - Resea...
2         1944  /Users/nevidujayatilleke/Documents/MSC - Resea...
3  1303 - 1333  /Users/nevidujayatilleke/Documents/MSC - Resea...
4  1825 - 1905  /Users/nevidujayatilleke/Documents/MSC - Resea...

DataFrame has 46 rows and 2 columns.

In [5]:
list_of_file_locations

   written_date                                 text_file_location
0   1187 - 1225  /Users/nevidujayatilleke/Documents/MSC - Resea...
1   1901 - 1938  /Users/nevidujayatilleke/Documents/MSC - Resea...
2          1944  /Users/nevidujayatilleke/Documents/MSC - Resea...
3   1303 - 1333  /Users/nevidujayatilleke/Documents/MSC - Resea...
4   1825 - 1905  /Users/nevidujayatilleke/Documents/MSC - Resea...
5   1850 - 1903  /Users/nevidujayatilleke/Documents/MSC - Resea...
6   1220 - 1293  /Users/nevidujayatilleke/Documents/MSC - Resea...
7   1854 - 1899  /Users/nevidujayatilleke/Documents/MSC - Resea...
8   1706 - 1739  /Users/nevidujayatilleke/Documents/MSC - Resea...
9   1857 - 1922  /Users/nevidujayatilleke/Documents/MSC - Resea...
10  1398 - 1410  /Users/nevidujayatilleke/Documents/MSC - Resea...
11  1457 - 1465  /Users/nevidujayatilleke/Documents/MSC - Resea...
12  1827 - 1895  /Users/nevidujayatilleke/Documents/MSC - Resea...
13  1868 - 1932  /Users/nevidujayatilleke/Documents/MSC - Resea...
14         1450  /Users/nevidujayatilleke/Documents/MSC - Resea...
15  1825 - 1893  /Users/nevidujayatilleke/Documents/MSC - Resea...
16  1220 - 1293  /Users/nevidujayatilleke/Documents/MSC - Resea...
17  1325 - 1333  /Users/nevidujayatilleke/Documents/MSC - Resea...
18         1390  /Users/nevidujayatilleke/Documents/MSC - Resea...
19         1878  /Users/nevidujayatilleke/Documents/MSC - Resea...
20         1820  /Users/nevidujayatilleke/Documents/MSC - Resea...
21         1821  /Users/nevidujayatilleke/Documents/MSC - Resea...
22  1408 - 1491  /Users/nevidujayatilleke/Documents/MSC - Resea...
23  1828 - 1887  /Users/nevidujayatilleke/Documents/MSC - Resea...
24  1850 - 1896  /Users/nevidujayatilleke/Documents/MSC - Resea...
25  1827 - 1911  /Users/nevidujayatilleke/Documents/MSC - Resea...
26         1916  /Users/nevidujayatilleke/Documents/MSC - Resea...
27  1850 - 1904  /Users/nevidujayatilleke/Documents/MSC - Resea...
28  1887 - 1944  /Users/nevidujayatilleke/Documents/MSC - Resea...
29  1187 - 1225  /Users/nevidujayatilleke/Documents/MSC - Resea...
30    398 - 426  /Users/nevidujayatilleke/Documents/MSC - Resea...
31         1874  /Users/nevidujayatilleke/Documents/MSC - Resea...
32  1270 - 1293  /Users/nevidujayatilleke/Documents/MSC - Resea...
33  1070 - 1232  /Users/nevidujayatilleke/Documents/MSC - Resea...
34  1325 - 1333  /Users/nevidujayatilleke/Documents/MSC - Resea...
35  1698 - 1778  /Users/nevidujayatilleke/Documents/MSC - Resea...
36  1760 - 1778  /Users/nevidujayatilleke/Documents/MSC - Resea...
37  1270 - 1293  /Users/nevidujayatilleke/Documents/MSC - Resea...
38  1070 - 1232  /Users/nevidujayatilleke/Documents/MSC - Resea...
39  1887 - 1932  /Users/nevidujayatilleke/Documents/MSC - Resea...
40  1887 - 1937  /Users/nevidujayatilleke/Documents/MSC - Resea...
41  1430 - 1440  /Users/nevidujayatilleke/Documents/MSC - Resea...
42  1827 - 1911  /Users/nevidujayatilleke/Documents/MSC - Resea...
43  1886 - 1938  /Users/nevidujayatilleke/Documents/MSC - Resea...
44  1852 - 1927  /Users/nevidujayatilleke/Documents/MSC - Resea...
45  1887 - 1941  /Users/nevidujayatilleke/Documents/MSC - Resea...

In [6]:
list_of_file_locations['text_file_location'][1]

'/Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/Surya_OCR/data/OCR_Final/නිදහසේ මන්ත්\u200dරය/නිදහසේ මන්ත්\u200dරය.txt'

In [7]:
import numpy as np

In [8]:
list_of_file_locations['start_date'] = np.nan
list_of_file_locations['end_date'] = np.nan

In [9]:
for index, row in list_of_file_locations.iterrows():
    date_str = str(row['written_date']) # Ensure it's treated as a string
    
    start_year = np.nan
    end_year = np.nan

    if ' - ' in date_str:
        # It's a range
        try:
            start_year_str, end_year_str = date_str.split(' - ')
            start_year = int(start_year_str.strip())
            end_year = int(end_year_str.strip())
        except ValueError:
            print(f"Warning: Could not parse range '{date_str}' at index {index}. Setting to NaN.")
    else:
        # It's a single year or potentially unparseable
        try:
            single_year = int(date_str.strip())
            start_year = single_year
            end_year = single_year # Duplicate for single date
        except ValueError:
            print(f"Warning: Could not parse single year/date '{date_str}' at index {index}. Setting to NaN.")
            
    # Assign the parsed (or NaN) values back to the DataFrame
    list_of_file_locations.at[index, 'start_date'] = start_year
    list_of_file_locations.at[index, 'end_date'] = end_year

In [10]:
list_of_file_locations.head()

,written_date,text_file_location,start_date,end_date
0,1187 - 1225,/Users/nevidujayatilleke/Documents/MSC - Resea...,1187.0,1225.0
1,1901 - 1938,/Users/nevidujayatilleke/Documents/MSC - Resea...,1901.0,1938.0
2,1944,/Users/nevidujayatilleke/Documents/MSC - Resea...,1944.0,1944.0
3,1303 - 1333,/Users/nevidujayatilleke/Documents/MSC - Resea...,1303.0,1333.0
4,1825 - 1905,/Users/nevidujayatilleke/Documents/MSC - Resea...,1825.0,1905.0

In [11]:
def get_century(year):
    """Calculates the century for a given year."""
    if pd.isna(year):
        return np.nan
    return (int(year) - 1) // 100 + 1

In [12]:
list_of_file_locations['end_century'] = list_of_file_locations['end_date'].apply(get_century)

In [13]:
list_of_file_locations.head()

,written_date,text_file_location,start_date,end_date,end_century
0,1187 - 1225,/Users/nevidujayatilleke/Documents/MSC - Resea...,1187.0,1225.0,13
1,1901 - 1938,/Users/nevidujayatilleke/Documents/MSC - Resea...,1901.0,1938.0,20
2,1944,/Users/nevidujayatilleke/Documents/MSC - Resea...,1944.0,1944.0,20
3,1303 - 1333,/Users/nevidujayatilleke/Documents/MSC - Resea...,1303.0,1333.0,14
4,1825 - 1905,/Users/nevidujayatilleke/Documents/MSC - Resea...,1825.0,1905.0,20

In [14]:
import re

In [15]:
def count_clean_words(path):
    try:
        with open(path, 'r', encoding='utf-8') as file:
            text = file.read()

        # Keep Sinhala + Latin characters + whitespace, remove others
        cleaned = re.sub(r'[^\u0D80-\u0DFFa-zA-Z\s]', '', text)

        # Tokenize by whitespace
        words = cleaned.split()
        # print(words)
        return len(words)

    except Exception as e:
        print(f"Error reading {path}: {e}")
        return 0

In [16]:
list_of_file_locations['word_count_no_punct_num'] = list_of_file_locations['text_file_location'].apply(count_clean_words)

In [17]:
list_of_file_locations['word_count_no_punct_num']

0     1126
1     1280
2     1661
3     1677
4     1283
5      973
6     2022
7     1886
8     1142
9      979
10    1228
11    1097
12    1547
13    1270
14    1137
15    1583
16    2242
17    1515
18    1275
19     848
20    1472
21     920
22    1410
23     843
24     925
25    1656
26    1415
27    1302
28     679
29    1148
30    1062
31    1227
32    1020
33     901
34    1474
35     988
36    1779
37    1311
38    1162
39    1626
40     811
41    1871
42    1280
43     694
44    1623
45     473
Name: word_count_no_punct_num, dtype: int64

In [18]:
list_of_file_locations['word_count_no_punct_num'].sum()

np.int64(58843)

In [19]:
def count_english_words(path):
    try:
        with open(path, 'r', encoding='utf-8') as file:
            text = file.read()

        # Keep only English letters and spaces
        cleaned = re.sub(r'[^a-zA-Z\s]', '', text)

        # Tokenize and filter out empty tokens
        words = [word for word in cleaned.split() if word.isalpha()]

        return len(words)

    except Exception as e:
        print(f"Error reading {path}: {e}")
        return 0

In [20]:
list_of_file_locations['english_word_count'] = list_of_file_locations['text_file_location'].apply(count_english_words)

In [21]:
list_of_file_locations['english_word_count']

0       0
1       0
2       0
3       0
4       1
5       0
6       0
7       0
8       0
9     630
10      0
11    147
12     13
13      0
14      0
15      0
16      0
17      1
18      3
19      0
20      0
21      0
22      0
23     24
24      0
25     12
26      0
27      0
28      0
29      0
30      0
31      0
32      0
33      0
34      0
35      0
36      0
37      0
38      0
39      0
40      0
41      1
42      0
43      0
44      0
45      0
Name: english_word_count, dtype: int64

In [22]:
list_of_file_locations['english_word_count'].sum()

np.int64(832)

In [23]:
list_of_file_locations.head(10)

,written_date,text_file_location,start_date,end_date,end_century,word_count_no_punct_num,english_word_count
0,1187 - 1225,/Users/nevidujayatilleke/Documents/MSC - Resea...,1187.0,1225.0,13,1126,0
1,1901 - 1938,/Users/nevidujayatilleke/Documents/MSC - Resea...,1901.0,1938.0,20,1280,0
2,1944,/Users/nevidujayatilleke/Documents/MSC - Resea...,1944.0,1944.0,20,1661,0
3,1303 - 1333,/Users/nevidujayatilleke/Documents/MSC - Resea...,1303.0,1333.0,14,1677,0
4,1825 - 1905,/Users/nevidujayatilleke/Documents/MSC - Resea...,1825.0,1905.0,20,1283,1
5,1850 - 1903,/Users/nevidujayatilleke/Documents/MSC - Resea...,1850.0,1903.0,20,973,0
6,1220 - 1293,/Users/nevidujayatilleke/Documents/MSC - Resea...,1220.0,1293.0,13,2022,0
7,1854 - 1899,/Users/nevidujayatilleke/Documents/MSC - Resea...,1854.0,1899.0,19,1886,0
8,1706 - 1739,/Users/nevidujayatilleke/Documents/MSC - Resea...,1706.0,1739.0,18,1142,0
9,1857 - 1922,/Users/nevidujayatilleke/Documents/MSC - Resea...,1857.0,1922.0,20,979,630

In [24]:
all_text = ""
for path in list_of_file_locations['text_file_location']:
    try:
        with open(path, 'r', encoding='utf-8') as file:
            all_text += file.read()
    except Exception as e:
        print(f"Error reading {path}: {e}")

In [25]:
cleaned_text = re.sub(r'[^\u0D80-\u0DFF\s]', '', all_text)

In [26]:
cleaned_text

'\t\t\t\t\t\t\tධර්ම ප්රදීපිකාව\n\n\t\t\t\t\t\tනමෝ තස්ස භගවතො අරහතො\n\t\t\t\t\t\t\tසම්මා සම්බුද්ධස්ස\n\n\tඅප බුදුන් සාරාසකි  කප්සුවහස් මතුයෙහි කුලුණුනු වණින්\nයුත් මහත වු සක් වැ දිවකුරු බුදුන් හමුවැ අතට පත් නිවන් සසර සේ\nපියා සතුන් සඳහා විඳුනා සසර දුක් නිවන් සේ ගෙන භව දුර්ගයට\nවැද පැරුම් පුරා තු පුර පැමිණ දසදහස් ලෝදාහි  දෙව්බඹුන්ගේ\nඅයජ මෙන් කිඹුල්වත්හි ඉපද වැඩිවිය පැමිණ මහභිනික්මන් කොට\nපැවිජි වැ මහා වීර්යය කොට බොධිපර්යංකාරූඪ වැ මාරවිජය කොට\nසර්වඥපදප්රාප්ත වැ හුනස්නෙන් නැඟී පූර්වොත්තර දිශා භාගයෙහි\nවැඩ සිට සප්තාහයක් අනිමිසලෝචන යුගලයෙන් පුදන ලද ජය\nමහා බොධිය තත ප්රභව වූ ඵල රුහ මහා බොධිය තදවයව වූ ශාඛා\nහා බොධිය යන තුන් මහා බොධීන්ගේ වංශයෙහි සහස්රරශ්මින්\nවිභක්ත පදයන් අතුරෙහි පරිකථානුකූල පද ගෙන වර්ණනා\nකරනු ලැබේ\n\t යස්ස යනු චතුර්විධ පදයන් කෙරෙහි නාමපදයි එහි චතුර්විධ\nපද නම් කවරයත් නාම පදය ආඛ්යාත පදය උපසර්ග පදය\nනිපාතපදයි\n\nඑහි  නාම පද නම් සර්වාර්ථයන් නමන්නෙන් නාම පද නම්\nවේ එයින් කීහ\n\n\tයත්ත්රිලිංගං ත්රිවචනං සර්වාසු ච විභක්තිෂු\n\tනමත්යර්ථෙන සර්වාර්ථා නාම කවයො විදුඃ  යී\n\nක්රියාවාචක පද  ආඛ්යාත  නම් වේ  එයින් කීහ\n\t\n\tයත්ත්රි කාලං ත්රිපුරුෂං ක්රියාවාචි ත්රිකාරකම්\n\tඅත්රිලිංගං ත්රිවචනං තදාඛ්යාතං ප්රවක්ෂතෙ  යී\n\n\n\t\t\t සාරාසංඛ්ය ලෝධාහි\n\n\n\n\t\t\t\t\t\t\tධර්ම ප්රදීපිකා\n\n\n\n\tක්රියා දොතක පද  උපසර්ග  නම් වේ  එයින් කීහ\n\t\n\t\tයස්මාදුප සෘජන්තයන් පදස්යාපරි ගච්ඡති\n\t\tක්රියායොග වහස්ත ස්මාදුප සර්ග ඉති ස්මෘතඃ  යී\n\n\tදක්වන ලද පදයන්ගේ ආද්යන්ත මධ්යයෙහි නිපතිත වූ විචිත්රාර්ථ\nපදයෝ  නිපාත  නම් වෙත්  එයින් කීහ\n\n\t\tයස්මාදාද්යාන්තමධ්යෙෂු වාක ප්රයොග විශෙෂතඃ\n\t\tනිපතන්ති විචිත්රාර්ථා නිපාතාසතුතු සංඥතාඃ  යි\n\nමේ චතුර්විධ පදයන්ගේ ප්රයෝග දක්වන්නට කීහ\n\t\tපදං චතුර්විධං ප්රොක්තං නාමාඛ්යාතොප සර්ගජම්\n\t\tනිපාතජච ශබ්ද ඥෙරවඃ ඛලවභිධාවති  යී\n\t\t\tමේය  චතුර්විධ පද නම්\n\n\t නිසිතෙනාව යන තන්හි  එව  යන නිපාතය \nඅයොග\nව්යවඡදකය අන්ය යොග ව්යවච්ඡේදකය අත්යන්තා යොග ව්යව\nච්ඡේදකය  යි ත්රිවිධ වූයේ අන්ය යොග ව්යවච්ඡේදක වේ එහි\nවිශෙෂණයා කෙරෙන් පර කොට ප්රයෝග කරන ලද එවකාරය\nඅයොග ව්යවච්ඡේදක වෙයි  චෛත්රො ධනුර්ධර එව යන තන්හි\nසෙයින්  විශෙෂයා කෙරෙන් පර කොට ප්රයෝග කරන ලද එව\nකාරය  අන්ය යොග ව්යවච්ඡේදක  වෙයි  පාර්ථි එව ධනුද්ධරඃ  යන\nතන්හි සෙයින්ක්රියායෙන් පර කොට ප්රයොග කරන ලද එව\nකාරය අත්යන්තා යොග ව්යවච්ඡේදක වෙයි  නීලං සරොජම\nසෙත්යව  යන තන්හි සෙයින්වාක්යයන් ව්යවච්ඡේද ඵල වන\nබැවින් නිපාතයා ප්රයෝග නොකළද විවක්ෂා වශයෙන් ඔහුගේ\nඅර්ථ ප්රතීත වේ මැයි\n\n\t\t\t\tඑයින් කීහ ධර්ම කීර්තිපාදයෝ\n\n\t\t අයොගං යොගම පරෛරත්යන්තා යොග මෙව ච\n\t\tව්යවච්ඡිනත්ති ධර්මස්ය නිපාතො ව්යතිරෙචකඃ\n\n\t\tවිශේෂණ විශේෂ්යාභ්යා ක්රියයා ච සහොදිතඃ\n\t\tවිවක්ෂාතො ප්රයොගෙ පි තයාර්ථෙ  යං ප්රතීයතෙ\n\n\t\tව්යවච්ඡෙද ඵලං වාක්යං යතා චිත්රො ධනුද්ධරඃ\n\t\tපාථො ධනුර්ධරො නීලං සරොජමස්ති වා යථා\n\n\t\t\t සරොජමිති යන පාඨය මෙහි පුර්වොක්තිය හා නොගැළපේ\n\n\n\n\n\t\t\t\t\t\t\tඅහීස මාධි කථා\n\t\t\t\t\n\t\t\t\tප්රතියොග ව්යවච්ඡෙදස්තත්රාප්යර්වෙෂු ගම්යතෙ\n\t\t\t\tතථා ප්රසිද්ධෙස්සා ධර්මර්ෂ්යාවක්ෂානුගමානෝ  යී\n\n\t පත්තෝ සබ්බඤ්ඤැතං සත්ථා යනුයෙන් දක්වන ලද\nබුදුහු අනන්තා පරිමාණ ගුණ ඇතියෝ කිසේය යත් බුදුහු රූප\nවිලාසයෙනුදු වචන විලාසයෙනුදු ඥාන විලාසයෙනුදු අචින්ත්යයහ\nඅවාච්යයහ අතුල්යහ අවෙද්යයෝයි එව්හු අචින්ත්ය වන බැවින්\nචින්තා විෂයාතික්රාන්තයහ අවාච්ය වන බැවින් වාග් විෂයාතික්රාන්ත\nසහ අතුල්ය වන බැවින් උපමා විෂයාතික්රාන්තයහ අද වන\nබැවින් ඥාන විෂයාතික්රාන්තයහ කපකුදු වූ දවස් තම සේම වූ බුදු\nකෙනෙකුනුදු කියත් නොගෙවෙන ගුණ ඇතියෝ  මහ මුහුදැ හෙළූ\nසිදුහතුළුදු කළ සැළදු තම තමා පමණින් දියගන්නා සේ ඒ බුදු\nරජහුගේ ගුණ මුහුදට වන් පසේ බුදුහුදු බුදු සවෝද තම තමන්ගේ\nනුවණ පමණින් ගන්ති ගුණ පමණින් ගන්නට නොනිසෝ\n\t\tගංගාය වාලුකා බීයෙ උදකං ඛීයෙ මහණ්ණ වෙ\n\t\tමහියා මත්තිකා ඛීයෙ ලක්ඛෙන මම බුද්ධියා  යී \n\n\tඥානගර්ජනා කරන්නට සමර්ථ වූ ධර්ම සෙනෙවි සැරියුත් මහතෙ\nරුන් වැනි මහා පුරුෂයනටත් අවිෂය වූ බුදු ගුණ පුහුදුන් වැ කියම්\nහයි සිතනු මදුරු දළින් විදුරු ගිරි විදුනාක් පින හැඹිළි දළින් මහ\nපොළොව උකුල් දෙනුවක් වැනි බැවින් තම හට අවිෂය වතුදු ප්රසාද\nපරවශ වැ ප්රවචන වහල් කොට ශ්රද්ධා බුද්ධි සම්පන්නජනයන් සඳහා\nකතිපය ගුණයෙක් දක්වනු ලැබේ\n\n\tබුදුන්ගේ ගුණයෙහි පුහුදුනන් හාද සව්පසේ බුදුන් හාද සාධා\nරණ ගුණයෝ ඇත්මය අසාධාරණ ගුණයෝ ඇත්මැයි එහි\nසෙසු  තිරිසනුන් හා සාධාරණ තණ කබල ගඳැත්කුස දිරුණ සිව් දෑ\nගඳ වන සෙයින් පුහුදුන් ආදීන් හා සාධාරණ වූ රූපශොභාද ධ්යානාභි\nඥාදි ගුණයෝද බුදු සතන්හිලා අසාධාරණ වෙති නොරබීජ\nනෙහි නොසිටුනා සිංහ තෙල් සෙයින් දශබල චතුර්වෛශාරද්යාදි\nඅසාධාරණ ගුණයෝ වූ කල නොබුදු සතන්හි ලා නොසිටිත්\n\n\tඔවුන්ගේ  රූප විලාස  නම් කවරයත් ද්වාත්රිංශන්මහා පුරුෂ\nලක්ෂණයෙන් හා අශීති අනුව්යංජනයෙන් ප්රජ්වලිත රූප ශොභායි\n\tඑහි  ද්වාත්රිංගන් මහා පුරුෂ ලක්ෂණ  නම් කවරයත් \n\t\t\tවදාළේ මැනො බුදුන් විසින්\n\n\tසුප්පතිටඨිත පාදො  හෙට්ඨාපාදතලෙසු චක්කානි ජාතානී සහ\nසාරානී සනෙමිකානි සනාභිකානි සබ්බාකාර පරිපුරානි  ආයත\n\n\t\t\t\t\t\t තෙසු\n\n\n\n\n\t\t\t\t\t\t\tධර්ම ප්රදීපිකා\n\nපණහි  දීඝගුලි  මුදු තලු නහත්ථ පාදො  ජාල හත්ථපාදො  උස්සං\nඛපාදො  එණිජංඝො  ඨිතකා අනොනිමන්තො උභොහි පාණී\nතලෙහි ජෂ්ණුකානි පරිමසති පරිමජ්ජතිකොසොහිතවත්ථගු\nහ  සුවණ්ණවණ්ණො කඤචන සන්නිභත්තචො  සුඛුමච්ඡවි වි\nසුඛුමන්තා ඡවියා රජො ජල්ලං කායෙ න උපලිප්පති  එකෙක\nරජොජල්ලං ලොමො එකෙකානි ලොමානි ලොමකූපෙසු ජාතානි  උඩග්ග ලොමො\nඋද්ධග්ගානි ලොමානි ජාතානි නිලානි අඤ්ජන වණ්ණානි කුණ්ඩ\nලාවත්තානි පදක්ඛිණාවත්තක ජාතානි  බ්රහ්මුජ්ජුගත්තො  සත්තු\nසීහ පුබ්බකායො  චිතන්තරංසො  නිග්රොධ පරිමණ්ඩ\nලො යාවතඣස්ස කායො තාවතස්ස ව්යාමො යාවතස්ස ව්යාමො\nතාවතඤස්ස කායො  සමවත්තක්ඛන්ධො  රසග්ගසග්ගි  සීහහනු \nචත්තාලීසදනෙන්තො  සමදන්තො  අවිවර දන්තො  සුසුක්කදාඨො \nපහූත ජි වෙහා  බ්රහ්මස්සරෝ කරවීකභාණී  අභිනීල නෙත්තො \nගොපඛුමො  උණ්ණා භමුකන්තරෙ ජාතා ඔදාතා මුදුතු ලසන්නිභා \nඋණහීස සීසො යී\n\n\tමෙහි සුප්පතිටඨිතපාදො යන තන්හි සුප්රතිෂ්ඨිතපාදතා\nනම් කවරයත් අනුන් පතුල් බිම ඔබන කලැ අග්ර පාද තලය හෝ\nපාර්ෂණිය හෝ පාර්ශවය හෝ පෙරට වැ භූමි ස්පර්ශ කෙරෙහි පාදතල\nමධ්යයෙහි ජිදු හෝ වෙයි පත්ල නඟන කලද අග්රපාදතලාදීන්\nකෙරෙන් අන්යතර ස්ථානයෙක් පෙරට වැ නැඟෙයිමොවුන් පතුල්\nවූ කල ස්වර්ණපාදුකා සෙයින් එක පැහැර භූමි සපර්ශ කෙරෙයි එක\nපැහැර නැගේ  ඉදින් අනෙකශත පෞරුෂ නරක ප්රපාතයෙහි\nඇක්මෙමියි පය එයට ඵළ වූයේ වී නම් එම විගස වළ තැන් භස්ත්රාසෙ\nයින් පිරෙයි ගොඩ තැන් භෙරිතල සෙයින් සම වේ දුර ඇක්මෙමියි\nපය නැඟුයේ වී නම් ප්රාතිහාර්යාවසානයෙහි සෙයින් මෙරු ප්රමාණ\nපර්වතයෙකුදු හුයාපී වෙයග බඩක් සෙයින් නැමී පාද සමීපයට උප\nගත වේ\n\t\t\t\t\tඑයින් කීහ\n\n\t\tනින්නං ඨානං උණ්ණමති ගච්ඡන්තෙ ලොක නාය කෙ\n\t\tඋණ්ණතංච සමං හොති පඨවී ච අචෙතනා\n\n\t\tපාසාණා සක්ඛරා චෙව කඨලා ඛාණු කණට කා\n\t\tසබ්බෙ මග්ගා විවජ්ජෙන්ති ගච්ඡන්තෙ ලොක නාය කෙ\n\t\tගච්ඡතො බුද්ධසෙට්ඨස්ස හෙට්ඨාපාදතලං මුදු\n\t\tසමං සත්ථුසතෙ භූමිං රජසා නූපලිප්පනි\n\t\tනාග වික්කන්තචාරො සො ගමනෙ සොභතෙ ජිනො\n\t\tචාරුං ගච්ඡති ලොකග්ගො හාසයන්තො සදෙවකෙ  යී\n\t\t\t\n\n\t\t\t\t\tඅභිස ඹාධිකය\n\n\n\tමෙසෙයින් සුප්රතිෂ්ඨිත වූ පාද තලද්වය ඇති වන බැවින්  සුප්රතිෂ්ඨිත\nපාද  නම් වෙත් බුදුහු\n\n\tහෙට්ඨාපාදතලෙසු චක්කානි ජාතානි යන තන්හි චක්රයෝ\nනම් කවරහයත් බුදුන් දෙපත්ලෙහි දෙචක්රයෙක් විය එකි\nඑකී චක්රයෙහි දහස් දහස් දැව් විය නෙමිදු විය නාභිදු වී  ඒ චක්රයෙහි\nපාදතල මධ්යයට වැ නාභි පැනෙයි නාභි වටා සිටි වටරෙඛා පැනෙයි\nනාභිමුඛ වටා සිටි වට පැනෙයි ඡිද්රමුඛ පැනෙයි දැවි පැනෙයි දැවියෙහි\nවටරෙඛා පැනෙයි නෙමි පැනෙයි නෙමිමණි පැනෙයි ඒ වටා\nස්වස්තිකය ශ්රීවත්සය නන්දාවර්තය සෞවස්තිකය අවතංස\nකය වර්ධමානකය භද්ර පීඨය ප්රාසාදය තොරණය ශ්වේතච්ඡත්රය\nඛංඩගය තාලවෘත්තය මයුර හස්තය චාමරය උෂ්ණීෂය මණිය\nසුමනාදාමය නීලොත්පලය රක්තොත්පලය රක්ත පද්මමය ශ්වෙත\nපදමය පූර්ණකලසය පූර්ණපාත්රය සමුදාය චක්රවාල පර්වතය\nහිමවත් පර්වතය මෙරු පර්වතය සුර්යය මණ්ඩලය චන්ද්ර මණ්ඩලය\nසපරිවාර සතර මහාද්වීපය ස්පර්ෂත සප්තරත්න චක්රවර්තිය දක්ෂිණා\nවර්ණා ශ්වෙතශංඛය ස්වර්ණ මතස්යයුගලය චක්රායුධයසපත\nමහා ගංගාය සප්ත මහා ශෛලය සප්ත මහාභ්රදය සුපර්ණ රාජය\nශිශුමාරය ධ්වජය පතාකාය ස්වර්ණශි විකාය ස්වර්ණ වාලව්යජ\nනය කෛලාස පර්වතය සිංහ රාජය ව්යාඝ්ර රාජය වලාහක අශ්ව\nරාජය පෞෂථභස්තිරාජය වාසුකි නාගරාජය හංසරාජය වෘෂභ\nරාජය ඓරාවණහස්ති රාජය ස්වර්ණමකරය චතුර්මුඛ ස්වර්ණ\nනෞකාය සවත් සකධෙනුය කිම පුරුෂය කින්නරීය කුරවිකය\nමයුර රාජය සුංව රාජය චක්රවාක රාජය ජිවඤ්ජිවක රාජය\nෂඩ් විධ දිව්ය ලොකය ෂොඩශවිධ බ්රහ්ම ලොකය යන මෙතෙක්\nමංගල ලක්ෂණයෝ පැනෙත්\n\n\tමෙසෙයින් බුදුන් දෙපත්ලෙහි දහස් දහස් දැව් ඇති නිම් නැබ\nසියෝ මඟුල් ලකුණු පිරිවර ලද දෙචක්ර ලක්ෂණයෝ  චක්ර  නම්\nවෙත්\n\tආයන පණහි යන තන්හි ආයත වු පාෂීණී නම් කවරයත්\nපිරිහුන් දික්විළු මැ සෙස්සන් අක්පතුල් දික් වෙයි විළුම් මුදුනෙහි\nසිහින් කකුල් වෙයි විළුම් සැසපීවාක් වැනි වෙයි බුදුනට වූ කල එසේ\nනොවෙයි බුදුන් පත්ලෙහි සතර භාගයෙන් දෙභාගයෙක් අක්\nපතුල් වෙයි තුන්වන භාගයෙහි ජංඝා ප්රතිෂඨිත වෙයි සතර වන\nභාගයෙහි හිදි අගින් වටා තුබුවාක් වැනි රක්ත කම්බල ගෙණ්ඩුකයක්\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\nකෙස් ගහ පවා වෙන රටවල මිනිසු\t\t\tන්නේ\nඋ ස් නිදහස පිණිස සටනට සැරැසෙ\t\t\tන්නේ\nහිස් මොළ තිබෙද්දීත් මේ වගනොතක\t\tන්නේ\nඇස් ගෙඩි දෙකට හෙණ ගැහිල ද සිහළු\t\tන්නේ\n\nනොලැබී නියත නිදහස රට ජාතිය\t\t\tට\nනොහොබී සැපැයි සැලැකුම කිසි සැපතක\t\tට\nකැලැඹී එතත් මේ මුළු තුන්ලොව එක\t\tට\nළැඹී සිටුමු නිදහස් නම් රණ බිම\t\t\tට\n\nසිරසට කිරුළ සතුරන්ගේ කඩු ප\t\t\tහර\nඋරවට හරය වැගිරෙන උණු ලේ ද\t\t\tහර\nමරහට ඇසෙන සාපය වෙයි අම අ\t\t\tහර\nතරකොට සිත වු තරුණෙනි තෙපි මේ ව\t\tහර\n\nහැඬි දැඩි වෙසින් මරු මරහඬ තලන කොට\t\tත්\nඑනවෙඩි පහර පාමුල ගිනි නඟන විට\t\tත්\nසි ටි අ ඩි නො සොල්වා සිටිනට සමත් වතො\t\tත්\nඋඹ දැඩි හදෑති විකුමැති පිරිමියෙකි කිය\t\tත්\n\nනා සක බලය නැස්මට වැද සතුරු සෙ\t\tබේ\nමා ර ක පහර ලැබහෙන මළ සිරුර ඔ\t\tබේ\nජාතික බලය පිළිබඳ සරදඹර ගැ\t\t\tබේ\nනෑ සැක පහන් තරුවක සිරි සරින් හෙ\t\tබේ\n\nමැරුණු කෙණෙහි උපදින මරණයක් ගැ\t\tන\nදරුණු දුකින් මිරිකෙන නිවටයන් මෙ\t\t\tන\nපිරුණු තෙදැති පරපුරෙකින් පැවැත එ\t\tන\nතුරුණු ඔබට යුතු නැති බව සිතනු මැ\t\tන\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රීය\n\n\nබියවනු කුමට සැරැසෙවු තෙපි මරණය\t\tට\nසිය රට නිසා යුද බිම් වැද පරලොව\t\tට\nගිය අප මුතුන් මිත්තන් හමුවෙයි එවි\t\tට\nකිය තැකි යළිත් අප හා එක් වන ලෙස\t\tට\n\nඑක මරණෙකින් හැකි නම් මේ තරම් දෙය\t\tක්\nදුක කිම එයට එක වරකට සියක් වර\t\tක්\nදැක තොප නිදන සැටි නොලැබ ම වහල් බව\t\tක්\nනෑ තොපට එක්වනුවට තවත් දහ\t\t\tක්\n\nඑක ලේ බිඳක් එක මිනිහෙකුගෙන් වැටෙ\t\tන\nඑක උල්පතක් නම් නිදහස් දිය උන\t\t\tන\nඑක එක්කෙනා තම තම හදවතින්\t\t\tන\t\nඑකණින් දමවු මුළු සිරිලක තෙමෙන මෙ\t\tන\n\nනොහැර දෙනුව ඉටු සිරි දෙව් දුවට ඉ\t\tඩ\nසතර රදිගින් එන මොළ රුපු බලය මැ\t\tඩ\nඅයරලන්තෙ ඩි වැලේරා කරපු වැ\t\t\tඩ\nඇ සැර බලවු සිහළුනි කොතරම් ද හැ\t\tඩ\n\nවිපතින් බියව ජාතික එඩි ගති සි\t\t\tන්දා\nහි ව ලු න් ලෙසින් මෙරමා දෙපතුල ව\t\tන්දා\nදෙවියන් සමග සැනහෙන දිය දද බ\t\t\tන්දා\nමළවුන් නමට නො කරවු සිහළුනි නි\t\t\tන්දා\n\nඅවටින් තුඬු පොවන මාරක සතුර\t\t\tන්ට\nඉඩ දෙන් නමුද රට ජාතිය වනස\t\t\tන්ට\nමළවුන් සමග නිදහස් සැප වළඳ\t\t\tන්ට\nනැගිටින් ඉතින් හොඳ නැහැ අලසව ඉ\t\tන්ට\n\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\nඇතහොත් අකණිටායෙහි මුත් සැපෙක් ඉ\t\tත\nසිරිමත් නිදහසම මිස වෙන දෙයක් නැ\t\tත\nමෙය සිත් රැගෙන වැඩ කොට ගිනි\t\t\tත\nමැරුණත් මොක ද එහි නො මැරෙන නමක් ඇ\t\tත\n\nසටන් නමැති යකිණිගෙ ගත සිත දෙක\t\tම\nමසින් උණු ලෙයින් සතපා ලන තුරු\t\t\tම\nනොවන්නෙ නම් අපහට නිදහස උරු\t\t\tම\nකරනමු එය ද දහමක් ලෙස පර\t\t\tම\n\nඅයුත් තක් දුටොත් එය එම තැනම කො\t\tටවු\nසිතත් බසත් කිරියත් එකිනෙකට ග\t\t\tටවු\nමහත් පරපුරැති විකුමැති සිහළ පැ\t\t\tටවු\nඅදත් සිහළ ලේවල බල පපා න\t\t\tටවු\n\nනිදහස් ගහේ ජාතික මල් පිපෙන තු\t\t\tරූ\nඇද වත් කරමු පපුවේ උණු ලේ වතු\t\t\tරූ\nඑ ද නොහැකි නම් නිවහල් මිනිහකු අයු\t\tරූ\nවැඳ ලක් මවට අද අවසන් හුස්ම හ\t\tරූ\n\nබලවු පොළොන්නරු අනුරාපුර පෙදෙ\t\tස\nසිතවු පැවැති නිදහස මෙහි පෙර දව\t\tස\nනඟවු තව තවත් තර සර තරුණ ගො\t\tස\nවරෙවු  යම වු නැඟිටි වු නො පියවු දෙ ඇ\tස\n\nඋපන් නෙත් මැරෙනෙත් තනිව ම යි ලො\t\tවේ\nඑයින් පිටත්තර වෙන විදියෙකින් නො\t\t\tවේ\nඅනුන් පිහිට තකමින් යුතුකම හමු\t\t\tවේ\nබියෙන් මුලු වදිනු අපහට තරම් නො\t\t\tවේ\n\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\nදික් කළ කෙණෙහි සතුරන්ගේ ගෙල නොසි\t\tඳ\nවක් නු පොරණ සිංහල අත් යුවළ අ\t\tඳ\nඔක් කෝට ම වඳින හැටි බල බලා ඉ\t\tඳ\nලක් මව අඬන හැටි උඹටත් පෙනෙනව\t\tද\n\nඋපන්නේ පුතෙක් වී උඹ ලක් මව\t\t\tට\nකරන්නට නොවෙද සේවය ඇගෙ නම\t\t\tට\nඉතින් එ ගැන නො තකා කිසිවක්\t\t\tට\nමැරෙන්නට හිතන උඹ පවිටෙකි නිව\t\t\tට\n\nඉපදුණ රටට අදහන ආගමට සෙ\t\t\tට\nමොන මොන අන්දමින්මුත් මෙහෙයක් නො කො\t\tට\nපැටවුණ බරක් මෙන් ලංකා පොළොව පි\t\tට\nපසුවන එක හොඳ ද සිංහල පුතකු හ\t\tට\n\nබෑ කිය කියා නිවටව අහු මුලු නො වැ\t\tදී\nජාතිය නිසා මාරක සටනකට වැ\t\t\tදී\nමාපිය සහෝදරයන් පණ පුදන වි\t\t\tදී\nපී තිය සිතින් නරඹමි පුහු මෙතින් මි\t\tදී\n\nගිරි මත පැමිණි එකසර කෙසරිඳු සේ\t\tවී\nසිරිබර පවර ජාතික ආලෙහි ගෑ\t\t\tවී\nහරි පිරිමියකු මෙන් වැඩ නො කොළොත් පේ\t\tවී\nසිරි ලක් මවට උඹ ණය ගැතියෙක් වේ\t\tවී\n\nඅපේ රට අපේ ජාතිය අපේ ග\t\t\tම\nඅපෙ අසල්වැසියා යන සියල්ල\t\t\tම\nඅපේ අතට අවනත කරගෙන වහ\t\t\tම\nඅපේ කමට සලකමු දිවි දෙමු මෙහෙ\t\tම\n\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\nහිස පිට වැටෙන හෙණ උසුලන්නට සැ\t\tදෙව\nවටපිට රැවුම් ගෙරවුම් ගැන කන් නො\t\tදෙව\nමරණට වුව ද සතුටින් යන්නට බැ\t\t\tඳෙව\nඑමවිට ලැබෙන නිදහස් සුවයෙහි රැ\t\t\tඳෙව\n\nදනට අණට බලයට පා පහර\t\t\t\tදෙව\nගුණට නැණට දහමට දිවි වුව ද\t\t\tදෙව\nසිතට බසට අනුව ම කිරියෙහි යෙ \t\t\tදෙව\nඑවිට ලැබෙන නිදහස් සුවයෙහි රැ\t\t\tදෙව\n\nසල කවු ගැමුණු පැරැකුම් සිහළුන්ගේ සෙ\t\tට\nමළ කුණු වලින් පෝර වු ලක් පොළොව පි\t\tට\t\nපැළවුණු සඳුන් පැළයක් මෙන් වැඩෙන්න\t\tට\nමැල වී ඉඳිනු යුතු නැහැ සිංහල උඹ\t\tට\n\nලක සමුදුරෙක ජාතික ආලය නැවෙ\t\t\tක\nසැක නෑ බුහුටි තරුණය උඹ නියමුවෙ\t\tක\nකිකලෙක නමුදු නිදහස් පරතෙර නොදැ\t\tක\nඅත රක නතර නො කරනු උඹේ යුතු කමෙ\t\tක\n\nරටක් ජාතියක් සමයක් කරණ කො\t\t\tට\nතුවක් කුවට කඩුවට ගල් මුල් වල\t\t\tට\t\nඉලක් කයක් වන්නට ඇත්නම් අප\t\t\tට\t\nසැපක් තමයි නො නිවෙන නිවනින් මෙපි\t\tට\n\nදෙදහස් තෙසිය සත් පනසක් වන තුරු\t\tම\nනිදහස් රටක් ලෙස කළ සිරිලක රැකු\t\tම\nදිය දෙස් සිහළ කිරුළෙහි බල සිහිකර\t\tම\nතියු ගොස් නඟ වූ නැගිටි වූ නො නිදවූ මෙහෙ\tම\n\n\n\n\t\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\nහෙණ පිට හෙණත් කඩුපිට කඩු හෙතත් හෙ\t\tම\nපණ නළ අපෙ අපගෙන් වෙන්වෙන තුරු\t\tම\nවණ නො කරමු යි ජාතික ගතිගුණ පර\t\tම\nදණ ඇන සිඹි මු ලක්මවගේ පාපියු\t\t\tම\n\nකපන්නට බැරි ද වැවු ළිං පොළොව පු\t\tරා\nඅනුන් ගේ වතුරු නළයට නො කරනු\t\t\tරා\nතමන්ගේ ම ඇස්වල උණු කඳුලු පෙ\t\t\tරා\nබොමින් ඉඳිමු ජාතික පණ නැහෙන තු\t\tරා\n\nදෙන්නට සුව සෙවණ බැරි නම් සිය හිස\t\tට\nදන් ඩකි එ අත සිඳලවු සත් කඩක් කො\t\tට\nඅන් අය තැනූ සුදු පටකුඩ වල පිහි\t\t\tට\nගන්නට එපා ජාතික ගති ඇතොත් සෙ\t\tට\n\nඇතොත් රටට ආදරයක් සිතින් සි\t\t\tපා\nඅතත් පයත් ඔලුවත් වෙන වෙන ම ක\t\tපා\nකතත් කමක් නැහැ කැත බිය ගතිය ප\t\tපා\nඅයුත් තකට අත්දෙක ඔසවන්ට එ\t\t\tපා\n\nඅපේ රටට පිළිමල් වන සතුරු මු\t\t\tල\nඅපේ අයම නම් බිඳිනමු උන්ගෙ බ\t\t\tල\nඅපේ මුතුන් මිත්තන් මළ සොහොන් ව\t\tල\nපිපේ එවිට ජාතික අබිමාන ම\t\t\tල\n\nපුවතර මුතුන් මිත්තන්ගේ සොහොන් ග\t\tබ\nමුව සිඹ හමන සිහිලැල් මඳ සුළඟ ලැ\t\tබ\nනව ජීවනය ලැබ ලැබ සුව විඳින ඔ\t\t\tබ\nතව නිදිමතේ ඇයි ගත සිත නො කර පො\t\tබ\n\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\nරට සහ ජාති ආගම තුන කරණ කො\t\tට\nසටනට යම වු යයි අඬගා කියන කො\t\tට\nමට බැහැ  කිවොත් සිහළකු නම් ඔහුගෙ ක\tට\nපට වනු නිසිය ගිනියම් කළ ලොහොදි කැ\t\tට\n\n\n\nමම් එක කෙනෙක නො සිතා කිසිවිටෙක නො\t\tපා\n මාර ක බිමෙහි ඇටවුණු මරු කපොලු ක\t\tපා\n ජාතික වැඩට සමයට දිවි කරමි කැ\t\tපා\nසාතික වෙන්න තරුණය අත හිසේ හ\t\tපා\n\nජාතික වැඩට මරුගුල් අටවමින් සි\t\t\tට\nනායක නමට දඟලන නිවටයන් හ\t\t\tට\nමේලක එකට අමු සොහොනක් කරන්න\t\tට\nසාතික වෙන්න තරුණය අද පටන් කො\t\tට\n\nඑනමුත් වියරු පුහු වැඩ නො කරන්නන්ට ඉ\t\tටවු\nපෙනුණොත් නියම යුතුකම අබිරුව මන\t\tටවු\nපපුවත් අතත් එකවිට අසිපතට ග\t\t\tටවු\nමැරුණත් කමක් නැහැ නැගිටි වූ සිහළ පැ\t\tටවු\n\nගන්දී නේරු පාතෙල් ඈ වීර ව\t\t\tරෝ\nඉන්දී නිදහසට දිව රෑ කරති අ\t\t\tරෝ\nකන්දී උන් බසට සිංහල සොහෝ වු\t\t\tරෝ\nදැන්දී පේ තිබෙන ජාතික වැඩට ව\t\t\tරෝ\n\nඇතියම්බලය පමණින් තම තමන් හ\t\t\tට\nයුතුකම් ඉටු කරනු මිස සමයට රට\t\t\tට\nපැරැදුම් දිනුම් වැනැසුම් සැනැසුම් වල\t\tට\nසැලැකුම් නො කොට එවු කවුරුත් ඉදිරිය\t\tට\n\n\n\n\n\t\t\t\t\t\t\tනිදහසේ මන්ත්රය\n\n\t\t\t\t\t\tජාතික ගීය\nදින දින දිනෙ දිනෙ සිරිලක ජාතික ආලේ \n\t\tජාතික ආලය ජාතික ආලේ \nදින දින දිනෙ දිනෙ සිරිලක ජාතික ආලේ \n\n\t\tජාතික රුධිරය යුද්ධ බිමේහි \n\t\tලූ අප නරවිරු ලාමුමෙනෙහි \nපාමූ දැන් අපි එක් වී රොක් වී ජාතික ආලේ \n\t\tජාතික ආ \nදින දින දිනෙ දිනෙ \n\t\tජාතික නිදහස සුද්ධ බිමේහී\n\t\tපෝරට ඇති දෙය ලේය ඇඟේ හී \nමේවා සීකොට පාමූ දැන් අපි ජාතික ආලේ \n\t\tජාතික ආ \nදින දින දිනෙ දිනෙ  \n\t\t\t\t\t\tපැරැණිගම\n\t\t\t\t\t\tපළමු අදියර\n\t\t\t\t\t\tගම්කාරයා\n\n\n\tගම යන වචනයෙහි ඇති සාමාන්ය අදහස විස්තර කිරීමට හැඳින්\nවීම් ලිවීම නිෂ්ඵල වැඩකි නමුත් අපේ සාහිත්යයට හා ඉතිහාසයට ද\nඅයත් ලිපි ලෙඛන වල මේ වචනය යොදා තිබෙන හැටියෙන් දැනට මේහි\nප්රචාරිත අර්ථයට වඩා පලල් වූ අදහසක් එහි ගැබ්ව පවත්නා බව පෙනී\nයයි  ගාමා වා අරඤ්ඤ වා  යන පාළි වචනය අටුවාකරණ බුද්ධඝොෂ\nපාදයෝ  ඉඳිකඩ දෙකක් ඇති අනුරාධපුරය වැනි ගමක ඇතුළු ඉඳි\nකඩෙහි සිට මධ්යම ප්රමාණ පුරුෂයකු ගලක් නැගූ කල්හි ගල වැටෙන\nපමණ දුර ගම් ඉම වේ  යයි කියමින් ග්රාම සීමාව නිශ්චය කළහ බුද්ධ\nඝොෂපාදයන් ලංකාවට වැඩම වූ කාලයෙහි අනුරාධපුරය අංග සම්පූර්ණ\nරාජධානියක් ව පැවති බව දන්නා කරුණකි එහෙත් යට කී වාක්යයෙහි\nඅනුරාධපුරය වැනි ගමක යයි කියා තිබීමෙන් බෞද්ධ සාහිත්යයෙහි ඇතැම්\nවිට ගම යන වචනය නියම් ගම් රාජධානිවලට පවා විශෙෂයක් නො සලකා\nව්යවහාර කොට තිබෙන බව පැහැදිලි වෙයි\n\n\tබුද්ධ ධර්මය පිළිබඳ සකලසාරය ම් හකුළුවා බුද්ධඝොෂ ස්ථවිර පාදයන්ම\nලියා ඇති විශුද්ධි මාර්ගය නම් ධර්ම ග්රන්ථයෙහි එක් තැනෙක තවද මෙසේ ත්\nදක්වා ඇත  අගුවට වැසි දිය වැටෙන තැනින් ඇතුළු පෙදෙස ගෙය ය\nගෘහිණිය විසින් බඳුන් සෝදා ඉවත ලන වතුර වැටෙන ප්රමාණ ප්රදේශය\nගෘහය පිළිබඳ උපචාරය ය මේ වැනි ගෙවල් ගොමුව ගමය එබඳු වූ\nගමෙහි අවසාන ගෙයි සීමාවේ සිට මධ්යම් වයසේ සිටි අයකු විසින් ගලක්\nහෙලා ලන පමණ දුර ගමට උපචාරය ය මේ ගම් සීමාවට  ගම්වල් \nයයි ව්යවහාර විය\n\n\tපැරැණි රජුන් විසින් ලියා කොටවන ලද සෙල්ලිපි හා තුඩපත් ආදි\nයෙහි මෙන්ම සාමාන්ය ව්යවහාරයෙහි පවා පෙනෙන ස භොග ග්රාම\n බඩවැටිගම  ආදී වචනවලට අනුව සලකන විට මෙය ඉඩම් කැබැල්ලක්\nහෝ කැබැලි කීපයක් උදෙසා ද භාවිත වූ බවට සැකයෙක් නැත\n\n\tවර්තමාන සිංහලයාගේ කිළුටු භාෂාවට ද පවිටු සමාජ සිරිත් විරිත්\nවලට ද විශේෂයෙන්ම කැලැල්ව ගිය ආගම භක්තියට ද කොයි ලෙස\nකින් හෝ සම්මිශ්රණය වීමෙන් තුමුත් කෙලෙසෙතැයි යන බියෙන් මෙන්\nවල් වැදුනු අවුරුදු දහස් දෙදහස් ගණන් පැරැණි ශිලාලේඛන මහත්\nරාශියක් විශේෂයෙන්ම උතුරුමැද පළාතේ ද වයඹ පළාතේ හා හම්බන්\nතොට දිස්ත්රික්කයේ ද පොළොව මතු පිටට මෙන්ම ඇතුළට ද වී සැඟවී\nසිටින බව අපි දනිමු දැනට දැන තිබෙන සිංහලයාගේ යට ගිය යසස්ස\nපිළිබිඹු කරවන මේ ලිපි ලෙඛන සියල්ලම දෙවන පෑතිස් රජුගෙන් පසු\nකාලයෙහි ලියන ලද ඒවා වෙති එම ලිපිවල  ගමිණි සිරිසඟබො අබහට\nයන විරුද වචන ඒ ඒ රජුන්ගේ නම් වලට මුලින් දක්නට තිබේ\n\n\tමෙහි ගාමණී යන පාලි වචනයට සමාන වූ ගමිණි යන විරුද වචනය\nපුරා විද්යාඥයන්ගේ විශෙෂ කල්පනාවට භාජන වූවකි එහි අදහස  ගමේ\nනායකයා  යන්න ය ධර්මාශෝක රජු විසින් අනුදැන් වූ දෙවෙනි පෑතිස්\nතුමා ලක්දිව පළමු වරට හිස පැන් වත්කිරීමෙන් අභිෂේකය ලැබූ රජ\nබව ද ඊට පෙර සිටි නරපතීන් අභිෂෙකය ලැබූ රජුන් මෙන් නොව\nගමිණි  නාමයෙන් හැඳින් වූ බවද ඔවුන්ගේ හැඟීමක්ව පවතී\n\n\tගමක් පිහිටු වීමට අදහස් කරන්නන් විසින් පළමු කොටම සිතා\n\t\t\tබලන කරුණ වතුර ලබා ගැණීමේ පහසු කම ය\nගම්වැසියා කුඬියා \tරොගොපද්රවාදී දහසක් කරදර වලට භාජන වෙමි\n\tසහ\t\tනුත් අප රට වියලි කලාපයෙහි අදත් ජීවත් වන\n\tගම්දස්සා\tබොහෝ දෙනාගේ ගම්මානවල් පිහිටා ඇත්තේ\n\t\t\tවැව් අසබඩ ය අධිපතීන්ගේ තාඩන පීඩන වලින්\nබේරීමට පළා ගොස් නතර වන පවුලක් දෙකක් නිසා කල්යාමේ දී ගම්\nමානවල් පැන නැඟෙති එබඳු ගම් දුගීම් වූ කඳු මත්තෙහි පිහිටුවා\nගණිති එහෙත් වතුර ලබා ගැණීමට යහපත් ඇළක් හෝ දොළක් ළඟ\nනොමැති නම් නිතැතින්ම එහි නිවාසය ඔවුන්ට අරුචි වෙයි ගමක්\nඑලෙස පැන නැඟී බවට ගණන් ගත යුතු ඉතාම වැදගත් සාක්කිය නම්\nඑගම වැස්සන් එකම් පෙළපතකට අයත් වූවන් වීමය මෑතක් වන\nතුරු ම එසේ එකම පෙළපතකින් පැවැතියන් විසූ ගම් කීපයක් අපි දු\nදන්නෙමු නමුත් ක්රමානුකූලව ගමක් බැඳීමෙන් ගම ඇති වී නම් එහි\nඑකම පෙළපතක වූවන් වෙතොත් ඒ කලාතුරකිනි අංග සම්පූර්ණ\nගමක එකල්හි සමාජයෙහි නොයෙක් තත්වය දරණ ගම්මුන් සිටිය යුතුය\n\n\tමිහින්තලා ශිලා ලේඛනයෙහි හා තවත් බොහෝ ලිපිවලද ගමක\nසිටින්නවුන් ගැණ සඳහන් කරණ විට ගම්වැස්සාය කුඩියා ය ගම්දස්\nසාය යන වචන තුණක් ව්යවහාර කොට ඇත මෙයින් ගම්වැසිකමට බල\nවත් සැලකිල්ලක් අදත් අප අතර දක්නා ලැබේ අපේ රටේ සර්වජන\n\n\nඡන්දය නිසි සේ ක්රියාවේ යොදා ගැණීමට නොහැකිව පවත්නා එක් කරු\nණක් නම් ගමේ කමට තැන නොතැන නොසලකා පමණ ඉක්මවා\nදක්වන සැලකිල්ලයි සෝවාන් වීමට ඔන්න මෙන්නැයි ළංව සිටින\nඅයට ඇතිවන කෙලෙසිලි දෙකක් ධර්ම ග්රන්ථ වල දක්වති ඉනුදු එකක්\nනම් ජනපද විතර්කය යයි අන්ය නාමයකින් කියැවෙන ගමේ කමට සැල\nකිල්ලය අතිමාත්ර වූ හැමෙකක්ම් වරද වන්නා සේ මිස ගමේ කමට\nසැලකීම හැම තැනම වරද යයි ලෞකික වූ අපි කෙසේ කියමුද ආණ්ඩුව\nසන්තක ඉඩම් බදුහදු දීම් ආදියෙහි ද ගම්මුළාදෑනිකම් දීම් ආදියෙහි ද\nආණ්ඩුව පවා අදත් පුරුද්දක් හැටියට ම් ගමේ කමට වැඩි සැලකිලි දක්\nවන බව කිව යුතුයි ගම්වැසියකු නො වීම නින්දාවක් ලෙස ද වීම නද\nපතුරුවා කියා ගත යුතු ගෞරවයක් ලෙස ද අදත් සැලකෙන්නේය\nකෝ දෙලෙන් දිලෙන නෙත් අයා පහරට පහර දෙන ගැටළු ගැටවරයන්\nදෙදෙනෙකු ගෙන් එකෙක් කලහයේ මද අස්වැසිල්ලක් ලබා උදාරමට\nදික්වෙන තර්ජනිය විදහා දනුව මීම ගමේ එකෙකැයි හඬ නඟන්නේය\nමේ උදාරම් වාක්යයම අනික් පැත්තට පෙරළූ කළ ඉන් ගමේ නො වීම\nනින්දාවක් බව ද කියැවෙයි සෑම දෙයක මෙන්ම මනුෂ්යයාගේ සිතුම්\nපැතුම් පිළිබඳව ද බලවත් විපර්යාසයක් ඇති වූ මේ විසිවෙනි ශත වර්ෂයෙහි\nගමේ කමෙන් ඇතිවන ප්රශංසාව මහජනයා මෙයට වඩා ඇතැම්\nවිට අඩුවට සිතන්ට පුළුවන පෙර කී තුන් කොටසට අයත් අයගෙන්\nගම් වැසියෝ වනාහි ගම් බැඳීමට හෝ ගම පිහිටුවීමට මුල් වූවෝ වෙති\nනැතහොත් ගම් බැඳීමට මුල් වූ අයගේ පරම්පරාවෙන් පැවත එන්නෝ\nවෙති දෙවෙනි කී කුඩියා ගමට හෝ ගමේ කමට අපිතියක් ඇත්තෙක්\nනොවේ සෙල්ලිපි බොහොමයකම කුඩීන් වරින් වර මාරුවෙමින් යන\nඅස්ථිර වාසයක් ඇත්තවුන් බවට සාක්ෂි තිබේ දැනුදු ස්ථිර නැති වාස\nයක් ගැණ කෙනෙකු කථා කරන්නේ  පැලේ ඉන්නා වගෙයි  කියා ය\nපැල්කාරයා දලුපත්කාරයා කියන්නේත් කුඬියාට මය මොවුන්ට ගම්\nවැසියන් සම්ග නෑ සබඳකම් නො වෙතත් ගම් වැසියෝ මො

In [27]:
tokens = cleaned_text.split()

In [28]:
tokens

['ධර්ම',
 'ප්රදීපිකාව',
 'නමෝ',
 'තස්ස',
 'භගවතො',
 'අරහතො',
 'සම්මා',
 'සම්බුද්ධස්ස',
 'අප',
 'බුදුන්',
 'සාරාසකි',
 'කප්සුවහස්',
 'මතුයෙහි',
 'කුලුණුනු',
 'වණින්',
 'යුත්',
 'මහත',
 'වු',
 'සක්',
 'වැ',
 'දිවකුරු',
 'බුදුන්',
 'හමුවැ',
 'අතට',
 'පත්',
 'නිවන්',
 'සසර',
 'සේ',
 'පියා',
 'සතුන්',
 'සඳහා',
 'විඳුනා',
 'සසර',
 'දුක්',
 'නිවන්',
 'සේ',
 'ගෙන',
 'භව',
 'දුර්ගයට',
 'වැද',
 'පැරුම්',
 'පුරා',
 'තු',
 'පුර',
 'පැමිණ',
 'දසදහස්',
 'ලෝදාහි',
 'දෙව්බඹුන්ගේ',
 'අයජ',
 'මෙන්',
 'කිඹුල්වත්හි',
 'ඉපද',
 'වැඩිවිය',
 'පැමිණ',
 'මහභිනික්මන්',
 'කොට',
 'පැවිජි',
 'වැ',
 'මහා',
 'වීර්යය',
 'කොට',
 'බොධිපර්යංකාරූඪ',
 'වැ',
 'මාරවිජය',
 'කොට',
 'සර්වඥපදප්රාප්ත',
 'වැ',
 'හුනස්නෙන්',
 'නැඟී',
 'පූර්වොත්තර',
 'දිශා',
 'භාගයෙහි',
 'වැඩ',
 'සිට',
 'සප්තාහයක්',
 'අනිමිසලෝචන',
 'යුගලයෙන්',
 'පුදන',
 'ලද',
 'ජය',
 'මහා',
 'බොධිය',
 'තත',
 'ප්රභව',
 'වූ',
 'ඵල',
 'රුහ',
 'මහා',
 'බොධිය',
 'තදවයව',
 'වූ',
 'ශාඛා',
 'හා',
 'බොධිය',
 'යන',
 'තුන්',
 'මහා',
 'බොධීන්ගේ',
 'වංශයෙහි',
 'සහස්රරශ්මින්',
 'විභක්ත',
 'පදයන්',
 'අතුරෙහි',
 'පරිකථානුකූල',
 'පද',
 'ගෙන',
 'වර්ණනා',
 'කරනු',
 'ලැබේ',
 'යස්ස',
 'යනු',
 'චතුර්විධ',
 'පදයන්',
 'කෙරෙහි',
 'නාමපදයි',
 'එහි',
 'චතුර්විධ',
 'පද',
 'නම්',
 'කවරයත්',
 'නාම',
 'පදය',
 'ආඛ්යාත',
 'පදය',
 'උපසර්ග',
 'පදය',
 'නිපාතපදයි',
 'එහි',
 'නාම',
 'පද',
 'නම්',
 'සර්වාර්ථයන්',
 'නමන්නෙන්',
 'නාම',
 'පද',
 'නම්',
 'වේ',
 'එයින්',
 'කීහ',
 'යත්ත්රිලිංගං',
 'ත්රිවචනං',
 'සර්වාසු',
 'ච',
 'විභක්තිෂු',
 'නමත්යර්ථෙන',
 'සර්වාර්ථා',
 'නාම',
 'කවයො',
 'විදුඃ',
 'යී',
 'ක්රියාවාචක',
 'පද',
 'ආඛ්යාත',
 'නම්',
 'වේ',
 'එයින්',
 'කීහ',
 'යත්ත්රි',
 'කාලං',
 'ත්රිපුරුෂං',
 'ක්රියාවාචි',
 'ත්රිකාරකම්',
 'අත්රිලිංගං',
 'ත්රිවචනං',
 'තදාඛ්යාතං',
 'ප්රවක්ෂතෙ',
 'යී',
 'සාරාසංඛ්ය',
 'ලෝධාහි',
 'ධර්ම',
 'ප්රදීපිකා',
 'ක්රියා',
 'දොතක',
 'පද',
 'උපසර්ග',
 'නම්',
 'වේ',
 'එයින්',
 'කීහ',
 'යස්මාදුප',
 'සෘජන්තයන්',
 'පදස්යාපරි',
 'ගච්ඡති',
 'ක්රියායොග',
 'වහස්ත',
 'ස්මාදුප',
 'සර්ග',
 'ඉති',
 'ස්මෘතඃ',
 'යී',
 'දක්වන',
 'ලද',
 'පදයන්ගේ',
 'ආද්යන්ත',
 'මධ්යයෙහි',
 'නිපතිත',
 'වූ',
 'විචිත්රාර්ථ',
 'පදයෝ',
 'නිපාත',
 'නම්',
 'වෙත්',
 'එයින්',
 'කීහ',
 'යස්මාදාද්යාන්තමධ්යෙෂු',
 'වාක',
 'ප්රයොග',
 'විශෙෂතඃ',
 'නිපතන්ති',
 'විචිත්රාර්ථා',
 'නිපාතාසතුතු',
 'සංඥතාඃ',
 'යි',
 'මේ',
 'චතුර්විධ',
 'පදයන්ගේ',
 'ප්රයෝග',
 'දක්වන්නට',
 'කීහ',
 'පදං',
 'චතුර්විධං',
 'ප්රොක්තං',
 'නාමාඛ්යාතොප',
 'සර්ගජම්',
 'නිපාතජච',
 'ශබ්ද',
 'ඥෙරවඃ',
 'ඛලවභිධාවති',
 'යී',
 'මේය',
 'චතුර්විධ',
 'පද',
 'නම්',
 'නිසිතෙනාව',
 'යන',
 'තන්හි',
 'එව',
 'යන',
 'නිපාතය',
 'අයොග',
 'ව්යවඡදකය',
 'අන්ය',
 'යොග',
 'ව්යවච්ඡේදකය',
 'අත්යන්තා',
 'යොග',
 'ව්යව',
 'ච්ඡේදකය',
 'යි',
 'ත්රිවිධ',
 'වූයේ',
 'අන්ය',
 'යොග',
 'ව්යවච්ඡේදක',
 'වේ',
 'එහි',
 'විශෙෂණයා',
 'කෙරෙන්',
 'පර',
 'කොට',
 'ප්රයෝග',
 'කරන',
 'ලද',
 'එවකාරය',
 'අයොග',
 'ව්යවච්ඡේදක',
 'වෙයි',
 'චෛත්රො',
 'ධනුර්ධර',
 'එව',
 'යන',
 'තන්හි',
 'සෙයින්',
 'විශෙෂයා',
 'කෙරෙන්',
 'පර',
 'කොට',
 'ප්රයෝග',
 'කරන',
 'ලද',
 'එව',
 'කාරය',
 'අන්ය',
 'යොග',
 'ව්යවච්ඡේදක',
 'වෙයි',
 'පාර්ථි',
 'එව',
 'ධනුද්ධරඃ',
 'යන',
 'තන්හි',
 'සෙයින්ක්රියායෙන්',
 'පර',
 'කොට',
 'ප්රයොග',
 'කරන',
 'ලද',
 'එව',
 'කාරය',
 'අත්යන්තා',
 'යොග',
 'ව්යවච්ඡේදක',
 'වෙයි',
 'නීලං',
 'සරොජම',
 'සෙත්යව',
 'යන',
 'තන්හි',
 'සෙයින්වාක්යයන්',
 'ව්යවච්ඡේද',
 'ඵල',
 'වන',
 'බැවින්',
 'නිපාතයා',
 'ප්රයෝග',
 'නොකළද',
 'විවක්ෂා',
 'වශයෙන්',
 'ඔහුගේ',
 'අර්ථ',
 'ප්රතීත',
 'වේ',
 'මැයි',
 'එයින්',
 'කීහ',
 'ධර්ම',
 'කීර්තිපාදයෝ',
 'අයොගං',
 'යොගම',
 'පරෛරත්යන්තා',
 'යොග',
 'මෙව',
 'ච',
 'ව්යවච්ඡිනත්ති',
 'ධර්මස්ය',
 'නිපාතො',
 'ව්යතිරෙචකඃ',
 'විශේෂණ',
 'විශේෂ්යාභ්යා',
 'ක්රියයා',
 'ච',
 'සහොදිතඃ',
 'විවක්ෂාතො',
 'ප්රයොගෙ',
 'පි',
 'තයාර්ථෙ',
 'යං',
 'ප්රතීයතෙ',
 'ව්යවච්ඡෙද',
 'ඵලං',
 'වාක්යං',
 'යතා',
 'චිත්රො',
 'ධනුද්ධරඃ',
 'පාථො',
 'ධනුර්ධරො',
 'නීලං',
 'සරොජමස්ති',
 'වා',
 'යථා',
 'සරොජමිති',
 'යන',
 'පාඨය',
 'මෙහි',
 'පුර්වොක්තිය',
 'හා',
 'නොගැළපේ',
 'අහීස',
 'මාධි',
 'කථා',
 'ප්රතියොග',
 'ව්යවච්ඡෙදස්තත්රාප්යර්වෙෂු',
 'ගම්යතෙ',
 'තථා',
 'ප්රසිද්ධෙස්සා',
 'ධර්මර්ෂ්යාවක්ෂානුගමානෝ',
 'යී',
 'පත්තෝ',
 'සබ්බඤ්ඤැතං',
 'සත්ථා',
 'යනුයෙන්',
 'දක්වන',
 'ලද',
 'බුදුහු',
 'අනන්තා',
 'පරිමාණ',
 'ගුණ',
 'ඇතියෝ',
 'කිසේය',
 'යත්',
 'බුදුහු',
 'රූප',
 'විලාසයෙනුදු',
 'වචන',
 'විලාසයෙනුදු',
 'ඥාන',
 'විලාසයෙනුදු',
 'අචින්ත්යයහ',
 'අවාච්යයහ',
 'අතුල්යහ',
 'අවෙද්යයෝයි',
 'එව්හු',
 'අචින්ත්ය',
 'වන',
 'බැවින්',
 'චින්තා',
 'විෂයාතික්රාන්තයහ',
 'අවාච්ය',
 'වන',
 'බැවින්',
 'වාග්',
 'විෂයාතික්රාන්ත',
 'සහ',
 'අතුල්ය',
 'වන',
 'බැවින්',
 'උපමා',
 'විෂයාතික්රාන්තයහ',
 'අද',
 'වන',
 'බැවින්',
 'ඥාන',
 'විෂයාතික්රාන්තයහ',
 'කපකුදු',
 'වූ',
 'දවස්',
 'තම',
 'සේම',
 'වූ',
 'බුදු',
 'කෙනෙකුනුදු',
 'කියත්',
 'නොගෙවෙන',
 'ගුණ',
 'ඇතියෝ',
 'මහ',
 'මුහුදැ',
 'හෙළූ',
 'සිදුහතුළුදු',
 'කළ',
 'සැළදු',
 'තම',
 'තමා',
 'පමණින්',
 'දියගන්නා',
 'සේ',
 'ඒ',
 'බුදු',
 'රජහුගේ',
 'ගුණ',
 'මුහුදට',
 'වන්',
 'පසේ',
 'බුදුහුදු',
 'බුදු',
 'සවෝද',
 'තම',
 'තමන්ගේ',
 'නුවණ',
 'පමණින්',
 'ගන්ති',
 'ගුණ',
 'පමණින්',
 'ගන්නට',
 'නොනිසෝ',
 'ගංගාය',
 'වාලුකා',
 'බීයෙ',
 'උදකං',
 'ඛීයෙ',
 'මහණ්ණ',
 'වෙ',
 'මහියා',
 'මත්තිකා',
 'ඛීයෙ',
 'ලක්ඛෙන',
 'මම',
 'බුද්ධියා',
 'යී',
 'ඥානගර්ජනා',
 'කරන්නට',
 'සමර්ථ',
 'වූ',
 'ධර්ම',
 'සෙනෙවි',
 'සැරියුත්',
 'මහතෙ',
 'රුන්',
 'වැනි',
 'මහා',
 'පුරුෂයනටත්',
 'අවිෂය',
 'වූ',
 'බුදු',
 'ගුණ',
 'පුහුදුන්',
 'වැ',
 'කියම්',
 'හයි',
 'සිතනු',
 'මදුරු',
 'දළින්',
 'විදුරු',
 'ගිරි',
 'විදුනාක්',
 'පින',
 'හැඹිළි',
 'දළින්',
 'මහ',
 'පොළොව',
 'උකුල්',
 'දෙනුවක්',
 'වැනි',
 'බැවින්',
 'තම',
 'හට',
 'අවිෂය',
 'වතුදු',
 'ප්රසාද',
 'පරවශ',
 'වැ',
 'ප්රවචන',
 'වහල්',
 'කොට',
 'ශ්රද්ධා',
 'බුද්ධි',
 'සම්පන්නජනයන්',
 'සඳහා',
 'කතිපය',
 'ගුණයෙක්',
 'දක්වනු',
 'ලැබේ',
 'බුදුන්ගේ',
 'ගුණයෙහි',
 'පුහුදුනන්',
 'හාද',
 'සව්පසේ',
 'බුදුන්',
 'හාද',
 'සාධා',
 'රණ',
 'ගුණයෝ',
 'ඇත්මය',
 'අසාධාරණ',
 'ගුණයෝ',
 'ඇත්මැයි',
 'එහි',
 'සෙසු',
 'තිරිසනුන්',
 'හා',
 'සාධාරණ',
 'තණ',
 'කබල',
 'ගඳැත්කුස',
 'දිරුණ',
 'සිව්',
 'දෑ',
 'ගඳ',
 'වන',
 'සෙයින්',
 'පුහුදුන්',
 'ආදීන්',
 'හා',
 'සාධාරණ',
 'වූ',
 'රූපශොභාද',
 'ධ්යානාභි',
 'ඥාදි',
 'ගුණයෝද',
 'බුදු',
 'සතන්හිලා',
 'අසාධාරණ',
 'වෙති',
 'නොරබීජ',
 'නෙහි',
 'නොසිටුනා',
 'සිංහ',
 'තෙල්',
 'සෙයින්',
 'දශබල',
 'චතුර්වෛශාරද්යාදි',
 'අසාධාරණ',
 'ගුණයෝ',
 'වූ',
 'කල',
 'නොබුදු',
 'සතන්හි',
 'ලා',
 'නොසිටිත්',
 'ඔවුන්ගේ',
 'රූප',
 'විලාස',
 'නම්',
 'කවරයත්',
 'ද්වාත්රිංශන්මහා',
 'පුරුෂ',
 'ලක්ෂණයෙන්',
 'හා',
 'අශීති',
 'අනුව්යංජනයෙන්',
 'ප්රජ්වලිත',
 'රූප',
 'ශොභායි',
 'එහි',
 'ද්වාත්රිංගන්',
 'මහා',
 'පුරුෂ',
 'ලක්ෂණ',
 'නම්',
 'කවරයත්',
 'වදාළේ',
 'මැනො',
 'බුදුන්',
 'විසින්',
 'සුප්පතිටඨිත',
 'පාදො',
 'හෙට්ඨාපාදතලෙසු',
 'චක්කානි',
 'ජාතානී',
 'සහ',
 'සාරානී',
 'සනෙමිකානි',
 'සනාභිකානි',
 'සබ්බාකාර',
 'පරිපුරානි',
 'ආයත',
 'තෙසු',
 'ධර්ම',
 'ප්රදීපිකා',
 'පණහි',
 'දීඝගුලි',
 'මුදු',
 'තලු',
 'නහත්ථ',
 'පාදො',
 'ජාල',
 'හත්ථපාදො',
 'උස්සං',
 'ඛපාදො',
 'එණිජංඝො',
 'ඨිතකා',
 'අනොනිමන්තො',
 'උභොහි',
 'පාණී',
 'තලෙහි',
 'ජෂ්ණුකානි',
 'පරිමසති',
 'පරිමජ්ජතිකොසොහිතවත්ථගු',
 'හ',
 'සුවණ්ණවණ්ණො',
 'කඤචන',
 'සන්නිභත්තචො',
 'සුඛුමච්ඡවි',
 'වි',
 'සුඛුමන්තා',
 'ඡවියා',
 'රජො',
 'ජල්ලං',
 'කායෙ',
 'න',
 'උපලිප්පති',
 'එකෙක',
 'රජොජල්ලං',
 'ලොමො',
 'එකෙකානි',
 'ලොමානි',
 'ලොමකූපෙසු',
 'ජාතානි',
 'උඩග්ග',
 'ලොමො',
 'උද්ධග්ගානි',
 'ලොමානි',
 'ජාතානි',
 'නිලානි',
 'අඤ්ජන',
 'වණ්ණානි',
 'කුණ්ඩ',
 'ලාවත්තානි',
 'පදක්ඛිණාවත්තක',
 'ජාතානි',
 'බ්රහ්මුජ්ජුගත්තො',
 'සත්තු',
 'සීහ',
 'පුබ්බකායො',
 'චිතන්තරංසො',
 'නිග්රොධ',
 'පරිමණ්ඩ',
 'ලො',
 'යාවතඣස්ස',
 'කායො',
 'තාවතස්ස',
 'ව්යාමො',
 'යාවතස්ස',
 'ව්යාමො',
 'තාවතඤස්ස',
 'කායො',
 'සමවත්තක්ඛන්ධො',
 'රසග්ගසග්ගි',
 'සීහහනු',
 'චත්තාලීසදනෙන්තො',
 'සමදන්තො',
 'අවිවර',
 'දන්තො',
 'සුසුක්කදාඨො',
 'පහූත',
 'ජි',
 'වෙහා',
 'බ්රහ්මස්සරෝ',
 'කරවීකභාණී',
 'අභිනීල',
 'නෙත්තො',
 'ගොපඛුමො',
 'උණ්ණා',
 'භමුකන්තරෙ',
 'ජාතා',
 'ඔදාතා',
 'මුදුතු',
 'ලසන්නිභා',
 'උණහීස',
 'සීසො',
 'යී',
 'මෙහි',
 'සුප්පතිටඨිතපාදො',
 'යන',
 'තන්හි',
 'සුප්රතිෂ්ඨිතපාදතා',
 'නම්',
 'කවරයත්',
 'අනුන්',
 'පතුල්',
 'බිම',
 'ඔබන',
 'කලැ',
 'අග්ර',
 'පාද',
 'තලය',
 'හෝ',
 'පාර්ෂණිය',
 'හෝ',
 'පාර්ශවය',
 'හෝ',
 'පෙරට',
 'වැ',
 'භූමි',
 'ස්පර්ශ',
 'කෙරෙහි',
 'පාදතල',
 'මධ්යයෙහි',
 'ජිදු',
 'හෝ',
 'වෙයි',
 'පත්ල',
 'නඟන',
 'කලද',
 'අග්රපාදතලාදීන්',
 'කෙරෙන්',
 'අන්යතර',
 'ස්ථානයෙක්',
 'පෙරට',
 'වැ',
 'නැඟෙයිමොවුන්',
 'පතුල්',
 'වූ',
 'කල',
 'ස්වර්ණපාදුකා',
 'සෙයින්',
 'එක',
 'පැහැර',
 'භූමි',
 'සපර්ශ',
 'කෙරෙයි',
 'එක',
 'පැහැර',
 'නැගේ',
 'ඉදින්',
 'අනෙකශත',
 'පෞරුෂ',
 'නරක',
 'ප්රපාතයෙහි',
 'ඇක්මෙමියි',
 'පය',
 'එයට',
 'ඵළ',
 'වූයේ',
 'වී',
 'නම්',
 'එම',
 'විගස',
 'වළ',
 'තැන්',
 'භස්ත්රාසෙ',
 'යින්',
 'පිරෙයි',
 'ගොඩ',
 'තැන්',
 'භෙරිතල',
 'සෙයින්',
 'සම',
 'වේ',
 'දුර',
 'ඇක්මෙමියි',
 'පය',
 'නැඟුයේ',
 'වී',
 'නම්',
 'ප්රාතිහාර්යාවසානයෙහි',
 'සෙයින්',
 'මෙරු',
 'ප්රමාණ',
 'පර්වතයෙකුදු',
 'හුයාපී',
 'වෙයග',
 'බඩක්',
 'සෙයින්',
 'නැමී',
 'පාද',
 'සමීපයට',
 'උප',
 'ගත',
 'වේ',
 'එයින්',
 'කීහ',
 'නින්නං',
 'ඨානං',
 'උණ්ණමති',
 'ගච්ඡන්තෙ',
 'ලොක',
 'නාය',
 'කෙ',
 'උණ්ණතංච',
 'සමං',
 'හොති',
 'පඨවී',
 'ච',
 'අචෙතනා',
 'පාසාණා',
 'සක්ඛරා',
 'චෙව',
 'කඨලා',
 'ඛාණු',
 'කණට',
 'කා',
 'සබ්බෙ',
 'මග්ගා',
 'විවජ්ජෙන්ති',
 'ගච්ඡන්තෙ',
 'ලොක',
 'නාය',
 'කෙ',
 'ගච්ඡතො',
 'බුද්ධසෙට්ඨස්ස',
 'හෙට්ඨාපාදතලං',
 'මුදු',
 'සමං',
 'සත්ථුසතෙ',
 'භූමිං',
 'රජසා',
 'නූපලිප්පනි',
 'නාග',
 'වික්කන්තචාරො',
 'සො',
 'ගමනෙ',
 'සොභතෙ',
 'ජිනො',
 'චාරුං',
 'ගච්ඡති',
 'ලොකග්ගො',
 'හාසයන්තො',
 'සදෙවකෙ',
 'යී',
 'අභිස',
 'ඹාධිකය',
 'මෙසෙයින්',
 'සුප්රතිෂ්ඨිත',
 'වූ',
 'පාද',
 'තලද්වය',
 'ඇති',
 'වන',
 'බැවින්',
 'සුප්රතිෂ්ඨිත',
 'පාද',
 'නම්',
 'වෙත්',
 'බුදුහු',
 'හෙට්ඨාපාදතලෙසු',
 'චක්කානි',
 'ජාතානි',
 'යන',
 'තන්හි',
 'චක්රයෝ',
 'නම්',
 'කවරහයත්',
 'බුදුන්',
 'දෙපත්ලෙහි',
 'දෙචක්රයෙක්',
 'විය',
 'එකි',
 'එකී',
 'චක්රයෙහි',
 'දහස්',
 'දහස්',
 'දැව්',
 'විය',
 'නෙමිදු',
 'විය',
 'නාභිදු',
 'වී',
 'ඒ',
 'චක්රයෙහි',
 'පාදතල',
 'මධ්යයට',
 'වැ',
 'නාභි',
 'පැනෙයි',
 'නාභි',
 'වටා',
 'සිටි',
 'වටරෙඛා',
 'පැනෙයි',
 'නාභිමුඛ',
 'වටා',
 'සිටි',
 'වට',
 'පැනෙයි',
 'ඡිද්රමුඛ',
 'පැනෙයි',
 'දැවි',
 'පැනෙයි',
 'දැවියෙහි',
 'වටරෙඛා',
 'පැනෙයි',
 'නෙමි',
 'පැනෙයි',
 'නෙමිමණි',
 'පැනෙයි',
 'ඒ',
 'වටා',
 'ස්වස්තිකය',
 'ශ්රීවත්සය',
 'නන්දාවර්තය',
 'සෞවස්තිකය',
 'අවතංස',
 'කය',
 'වර්ධමානකය',
 'භද්ර',
 'පීඨය',
 'ප්රාසාදය',
 'තොරණය',
 'ශ්වේතච්ඡත්රය',
 'ඛංඩගය',
 'තාලවෘත්තය',
 'මයුර',
 'හස්තය',
 'චාමරය',
 'උෂ්ණීෂය',
 'මණිය',
 'සුමනාදාමය',
 'නීලොත්පලය',
 'රක්තොත්පලය',
 'රක්ත',
 'පද්මමය',
 'ශ්වෙත',
 'පදමය',
 'පූර්ණකලසය',
 'පූර්ණපාත්රය',
 'සමුදාය',
 'චක්රවාල',
 'පර්වතය',
 'හිමවත්',
 'පර්වතය',
 'මෙරු',
 'පර්වතය',
 'සුර්යය',
 'මණ්ඩලය',
 'චන්ද්ර',
 'මණ්ඩලය',
 'සපරිවාර',
 'සතර',
 'මහාද්වීපය',
 'ස්පර්ෂත',
 'සප්තරත්න',
 'චක්රවර්තිය',
 'දක්ෂිණා',
 'වර්ණා',
 'ශ්වෙතශංඛය',
 'ස්වර්ණ',
 'මතස්යයුගලය',
 'චක්රායුධයසපත',
 'මහා',
 'ගංගාය',
 'සප්ත',
 'මහා',
 'ශෛලය',
 'සප්ත',
 'මහාභ්රදය',
 'සුපර්ණ',
 'රාජය',
 'ශිශුමාරය',
 'ධ්වජය',
 ...]

In [29]:
len(tokens)

58027

In [30]:
unique_tokens = sorted(set(tokens))

In [31]:
unique_tokens

['ං',
 'ංඑත්ථාහ',
 'ංකාරූඪව',
 'ංග',
 'ංගයකින්',
 'ංග්රහව',
 'ංඤ්ච',
 'ංඩය',
 'ඃ',
 'අ',
 'අං',
 'අංඉති',
 'අංග',
 'අංගණ',
 'අංගණාවට',
 'අංගනාවන්ගෙ',
 'අංගාන්',
 'අංගානි',
 'අංගුත්තර',
 'අංජනනිලේ',
 'අංයන',
 'අංයයි',
 'අංසක',
 'අආඉඊඋඌ',
 'අආදයො',
 'අඉඋ',
 'අඑ',
 'අක',
 'අකංසු',
 'අකණිටායෙහි',
 'අකඬලා',
 'අකප්පියං',
 'අකප්පියසයනානි',
 'අකප්පියානි',
 'අකප්පියානිසයනානි',
 'අකම්පිත්ථ',
 'අකමිකයි',
 'අකර්මක',
 'අකරොන්තෙන',
 'අකල්යල්ය',
 'අකලිෂ්ට',
 'අක්',
 'අක්කොච්ඡිමං',
 'අක්ඛන්ති',
 'අක්ඛරවන්තො',
 'අක්ඛරා',
 'අක්ඛරාපාදයො',
 'අක්ඛරාපි',
 'අක්ඛරෙසු',
 'අක්ඛෙපෙච',
 'අක්පතුල්',
 'අක්ෂ',
 'අක්ෂර',
 'අක්ෂරයන්',
 'අක්ෂරයන්ගේ',
 'අක්ෂරයෙන්',
 'අක්ෂරයෝ',
 'අක්ෂි',
 'අකා',
 'අකාර',
 'අකාරතො',
 'අකාරය',
 'අකාරයක්හු',
 'අකාරයහා',
 'අකාරයා',
 'අකාරාදයො',
 'අකාරාන්ත',
 'අකාරො',
 'අකැ',
 'අකැප',
 'අකැපපී',
 'අකීකරුවී',
 'අකුරකට',
 'අකුරු',
 'අකුරුත්',
 'අකුරුතුණ',
 'අකුරුයැයි',
 'අකුරෙකි',
 'අකුරෙන්',
 'අකුසලට',
 'අකුසලයක්',
 'අකුසල්',
 'අකුසල්හි',
 'අකුසලින්',
 'අඛණ්ඩ',
 'අඛිනන්න',
 'අඛිනන්නං',
 'අඛින්න',
 'අඛිලං',
 'අඛිලංවෙසං',
 'අඛිලා',
 'අග',
 'අගච්ඡා',
 'අගඤඡා',
 'අගඤ්ඡි',
 'අගතියටත්',
 'අගතෙක්',
 'අගන',
 'අගනා',
 'අගනුන්ට',
 'අගම්',
 'අගමැණ',
 'අගමැති',
 'අගය',
 'අගයක්ම',
 'අගල',
 'අගවිනි',
 'අගස',
 'අගසව්',
 'අග්ග',
 'අග්ගං',
 'අග්ගහීතතියෙවාරෙ',
 'අග්ගා',
 'අග්ගො',
 'අග්නි',
 'අග්නිවෙස',
 'අග්ර',
 'අග්රපාදතලය',
 'අග්රපාදතලා',
 'අග්රපාදතලාදීන්',
 'අග්රමහෙසිකා',
 'අග්රශ්රාවිකා',
 'අග්රාභරණ',
 'අග්රාම්ය',
 'අග්රාමාත්යයන්',
 'අගා',
 'අගාඃ',
 'අගාපච්චන්ත',
 'අගාමගධගාමිනා',
 'අගාර',
 'අගාරිකමුනි',
 'අගැ',
 'අගින්',
 'අගී',
 'අගීරසන',
 'අගු',
 'අගුලගත්',
 'අගුවට',
 'අගේ',
 'අඝො',
 'අඝොෂාදෙශයෙන්',
 'අඝොස',
 'අඝොසය',
 'අඝොසයෝ',
 'අඟ',
 'අඟන',
 'අඟනගේ',
 'අඟනන්',
 'අඟනන්ට',
 'අඟන්නෝ',
 'අඟනුන්ට',
 'අඟහරුවා',
 'අඟු',
 'අඟුල්',
 'අච්චයෙ',
 'අච්ඡරියබ්භුත',
 'අචින්ත්ය',
 'අචින්ත්යයහ',
 'අචෙතනා',
 'අචෛතනික',
 'අජ',
 'අජජ්ඣි',
 'අජපාල',
 'අජපාලන්ය',
 'අජර',
 'අජරාමරවත්',
 'අජ්ජ',
 'අජ්ඣත්තං',
 'අජ්ඣෙසිතො',
 'අජාගලස්තනය්යෙව',
 'අජාතමෘත',
 'අජාසත්',
 'අජිනි',
 'අඤඤත්ථ',
 'අඤපෙඅඤ්ඤෙ',
 'අඤ්ජන',
 'අඤ්ජනී',
 'අඤ්ඤ',
 'අඤ්ඤං',
 'අඤ්ඤත්ථසෙසා',
 'අඤ්ඤථා',
 'අඤ්ඤපදත්ථස්ස',
 'අඤ්ඤා',
 'අඤ්ඤාණ',
 'අඤ්ඤාතා',
 'අඤ්ඤාපදෙස',
 'අඤ්ඤෙ',
 'අඤා',
 'අඤේඤ්ඤෙ',
 'අඥත්වය',
 'අඥාන',
 'අඥානද',
 'අඥානයා',
 'අඥානයෙක්ද',
 'අට',
 'අටක',
 'අටකට',
 'අටක්',
 'අටක්ද',
 'අටතැන',
 'අටදෙනාගෙන්',
 'අටපනස්',
 'අටපරිද්දෙකින්',
 'අටපිරි',
 'අටමසක්',
 'අටමසකින්',
 'අටමසෙහි',
 'අටමා',
 'අටමිට',
 'අටමිටක්',
 'අටයදසය',
 'අටලොස්මනින්',
 'අටවන',
 'අටවමින්',
 'අටවැන්නෙහි',
 'අටවැනි',
 'අටවියා',
 'අටවිව්වාසි',
 'අටවෙනි',
 'අටසාළිස්',
 'අටසිය',
 'අටසිල්',
 'අටළොස',
 'අටළොසයයි',
 'අටළොස්',
 'අට්ටිතො',
 'අට්ඨ',
 'අට්ඨකථා',
 'අට්ඨකුසලචි',
 'අට්ඨා',
 'අට්ඨාරසන්නං',
 'අට්ඨාරසාධි',
 'අට්ඨාරසාධිමාසා',
 'අට්ඨි',
 'අට්ඨිකත්වා',
 'අට්ඨිතා',
 'අටි',
 'අටින්',
 'අටුවා',
 'අටුවාකරණ',
 'අටුවාවෙහි',
 'අටුවාවෙහිද',
 'අටෙකි',
 'අටෙන්',
 'අටෝරාසියක්',
 'අඩ',
 'අඩංගු',
 'අඩඑරත්තං',
 'අඩඪ',
 'අඩ්ඪ',
 'අඩා',
 'අඩාල',
 'අඩු',
 'අඩුනු',
 'අඩුයි',
 'අඩුව',
 'අඩුවට',
 'අඩුවුවත්',
 'අණ',
 'අණට',
 'අඬගා',
 'අඬන',
 'අඬන්නේ',
 'අඬා',
 'අඬාරසාති',
 'අත',
 'අතකට',
 'අතක්',
 'අතට',
 'අතත්',
 'අතදයි',
 'අතමඩනේද',
 'අතර',
 'අතරක්',
 'අතරත්',
 'අතරමග',
 'අතරමඟ',
 'අතරෙහි',
 'අතලක්',
 'අතවාසිකෙනාපි',
 'අත්',
 'අත්කර',
 'අත්තජො',
 'අත්තධාදෙසා',
 'අත්තනායක',
 'අත්තනි',
 'අත්තනො',
 'අත්තභාවං',
 'අත්තාණස්ස',
 'අත්තුඩාර',
 'අත්තූපණායිකං',
 'අත්ථ',
 'අත්ථං',
 'අත්ථංච',
 'අත්ථඛ්යංජන',
 'අත්ථදසයිධම්ම',
 'අත්ථදස්සිය',
 'අත්ථදස්සී',
 'අත්ථමෙව',
 'අත්ථානුගතසම',
 'අත්ථාය',
 'අත්ථාව',
 'අත්ථාවධාරණං',
 'අත්ථි',
 'අත්ථික',
 'අත්ථිකො',
 'අත්ථෙපි',
 'අත්ථෙසු',
 'අත්ථො',
 'අත්දෙක',
 'අත්නො',
 'අත්පුරා',
 'අත්යන්තා',
 'අත්යන්තායොගව්යව',
 'අත්රජා',
 'අත්රජො',
 'අත්රිලිංගං',
 'අත්වය',
 'අත්වයො',
 'අත්වෙති',
 'අත්වෙයි',
 'අතැ',
 'අතැඹුලක්',
 'අතැවැසි',
 'අති',
 'අතික්කන්ත',
 'අතික්කම්ම',
 'අතික්කමෙත්වා',
 'අතික්රාන්ත',
 'අතිගාම්භීර',
 'අතිජාත',
 'අතිදුල්ලහං',
 'අතින්',
 'අතින්ගි',
 'අතිපරිශුද්ධත්වය',
 'අතිපාපිෂ්ට',
 'අතිමාත්ර',
 'අතිමුඛපණිතං',
 'අතිරත්තො',
 'අතිරාහසික',
 'අතිරික්ත',
 'අතිවිය',
 'අතිවිසිට්ඨං',
 'අතිවිසිට්ඨෙන',
 'අතිශය',
 'අතිශයින්',
 'අතිශයින්ම',
 'අතිසයින්',
 'අතී',
 'අතීත',
 'අතීතයෙහි',
 'අතීතායති',
 'අතීරක්ත',
 'අතු',
 'අතුට',
 'අතුපතර',
 'අතුර',
 'අතුරක්',
 'අතුරු',
 'අතුරුකප',
 'අතුරෙන්',
 'අතුරෙහි',
 'අතුල',
 'අතුලං',
 'අතුල්',
 'අතුල්ය',
 'අතුල්යයහ',
 'අතුල්යහ',
 'අතෙහි',
 'අතො',
 'අථ',
 'අථඛො',
 'අථවා',
 'අථොක්ත',
 'අද',
 'අදට',
 'අදත්',
 'අදත්තාදානයෙහි',
 'අදන්තඃ',
 'අදනා',
 'අදර',
 'අදරකර',
 'අදරට',
 'අදරයෙන්',
 'අදරවි',
 'අදරින්',
 'අදහ',
 'අදහන',
 'අදහස',
 'අදහසක්',
 'අදහස්',
 'අදහස්පැවැසෙන්නේ',
 'අදහසින්',
 'අද්දස',
 'අද්ධමුණ්ඩකෙ',
 'අද්භූත',
 'අද්වයවාදිතාදිනං',
 'අද්වයවාදිනො',
 'අදාසි',
 'අදාළ',
 'අදි',
 'අදිකාරි',
 'අදිට්ඨෙ',
 'අදින්නං',
 'අදිනාසඳ',
 'අදිමන්',
 'අදියර',
 'අදිස්වාත',
 'අදීහු',
 'අදෙතුං',
 'අදෙස්',
 'අදෝනා',
 'අධඃශරීරය',
 'අධර්මයට',
 'අධර්මවාදීන්',
 'අධ්යන්',
 'අධ්යයනාධ්යාපන',
 'අධ්යාගාර',
 'අධ්යාරොපිත',
 'අධ්යාශය',
 'අධ්යාසය',
 'අධ්යාහාර',
 'අධ්යාහාරයෙන්',
 'අධි',
 'අධික',
 'අධිකපතනයව',
 'අධිකයි',
 'අධිකරණයන්',
 'අධිකව',
 'අධිකානි',
 'අධිකානී',
 'අධිකාර',
 'අධිකාරො',
 'අධිකාසාළහ',
 'අධිකෙ',
 'අධිගත',
 'අධිගතයන්',
 'අධිගම',
 'අධිගමයන්',
 'අධිගමසාසනස්ස',
 'අධිචි',
 'අධිචිත්ත',
 'අධිචිත්තං',
 'අධිචිත්තය',
 'අධිචිත්තසික්ඛා',
 'අධිට්ඨාන',
 'අධිට්ඨිත',
 'අධින්න',
 'අධිප',
 'අධිපඤ්ඤා',
 'අධිපඤ්ඤාවසෙන',
 'අධිපඤ්ඤාසික්ඛාති',
 'අධිපති',
 'අධිපතීන්ගේ',
 'අධිප්පා',
 'අධිප්පායත්ථො',
 'අධිප්පායො',
 'අධිප්රඥා',
 'අධිමා',
 'අධිමානීකො',
 'අධිමාස',
 'අධිමාසංදීපනි',
 'අධිමාසපතන',
 'අධිමාසපතනයට',
 'අධිමාසභෙදයෙහි',
 'අධිමාසය',
 'අධිමාසයද',
 'අධිමාසයයිද',
 'අධිමාසයේ',
 'අධිමාසවිනිච්ඡයං',
 'අධිමාසවිනිශ්චය',
 'අධිමාසස්',
 'අධිමාසා',
 'අධිමාසානි',
 'අධිමාසෙ',
 'අධිමොක්ඛ',
 'අධිවචනං',
 'අධිවේද',
 'අධිශීල',
 'අධිශීලය',
 'අධිෂ්ඨාන',
 'අධිසී',
 'අධිසීල',
 'අධිසීලං',
 'අධිසීලසික්ඛාව',
 'අධිසීලාද',
 'අධුනක්',
 'අධුනික',
 'අධුනිකයයි',
 'අධොලිපියෙහි',
 'අන',
 'අනංග',
 'අනංගරංගජභූතමංග',
 'අනංගරූ',
 'අනංගරූපො',
 'අනගසේ',
 'අනගාර',
 'අනගාරිකමුනි',
 'අනගි',
 'අනඝොත්තම',
 'අනඤ්ඤප්පටිසරණං',
 'අනට',
 'අනත',
 'අනත්ත',
 'අනත්තටා',
 'අනත්තාත්රාණ',
 'අනත්ථසහිතං',
 'අනනතා',
 'අනන්ත',
 'අනන්තං',
 'අනන්තයාහා',
 'අනන්තරං',
 'අනන්තරා',
 'අනන්තරායෙන',
 'අනන්තරෙ',
 'අනන්තා',
 'අනන්තාපරිමාණ',
 'අනන්තෙ',
 'අනන්ය',
 'අනන්යසාධාරණ',
 'අනන්යා',
 'අනභයා',
 'අනභිලාසං',
 'අනභිවෘද්ධියක්',
 'අනයං',
 'අනර්ඝ',
 'අනල්ප',
 'අනලෙස',
 'අනවතපත',
 'අනවතප්ත',
 'අනවද්ය',
 'අනවයවග්ගහ',
 'අනවයවොහි',
 'අනවරත',
 'අනවරතයෙන්',
 'අනවස්ථිත',
 'අනවිලස',
 'අනෂ්ටකාය',
 'අන්',
 'අන්ක',
 'අන්කිසිවෙකුට',
 'අන්කීසි',
 'අන්ත',
 'අන්තං',
 'අන්තක',
 'අන්තනිමිත්තයැ',
 'අන්තය',
 'අන්තයෙහි',
 'අන්තයෝ',
 'අන්තරන්තරයෙන්',
 'අන්තර්ගත',
 'අන්තර්ගතව',
 'අන්තර්ථ',
 'අන්තර්නිමිත්ත',
 'අන්තරා',
 'අන්තරායෙක්',
 'අන්ත්ය',
 'අන්තානං',
 'අන්තිම',
 'අන්තිමේදී',
 'අන්තෙ',
 'අන්තො',
 'අන්දමින්මුත්',
 'අන්දමේ',
 'අන්ධකාර',
 'අන්ධකාරය',
 'අන්ධකාරයද',
 'අන්ධකාරයෙහි',
 'අන්ධය',
 'අන්ධයෂ්ටි',
 'අන්ධයෙක්මය',
 'අන්පරිද්දකින්',
 'අන්ය',
 'අන්යච්ච',
 'අන්යතර',
 'අන්යයන්ට',
 'අන්යයොග',
 'අන්යර්ථයෙන්',
 'අන්යාර්ථ',
 'අන්යොන්ය',
 'අන්රජ',
 'අන්වත්ථ',
 'අන්වය',
 'අන්වෙති',
 'අන්හටද',
 'අනාග',
 'අනාගත',
 'අනාගතකාල',
 'අනාගතත්තා',
 'අනාගතයෙහි',
 'අනාගතවංශ',
 'අනාගතවංශය',
 'අනාගතෙසු',
 'අනාගාමි',
 'අනාථ',
 'අනාදරියං',
 'අනාදරියස්ස',
 'අනාදරියස්සච',
 'අනාපජ්ජන්තෙ',
 'අනාම',
 'අනාරූ',
 'අනාවරණ',
 'අනාවරණය',
 'අනැඟි',
 'අනිකකුදු',
 'අනික්',
 'අනික්ඛිත්ත',
 'අනික්ඛිත්තසික්ඛෝ',
 'අනිකුදු',
 'අනිකෙක',
 'අනිච',
 'අනිචචසඤ්ඤා',
 'අනිච්චං',
 'අනිත්',
 'අනිත්පැත්තේ',
 'අනිමිෂ',
 'අනිමිසලෝචන',
 'අනියමය',
 'අනියම්',
 'අනිල',
 'අනිවකාම',
 'අනිවරුපිනී',
 'අනිෂ්ට',
 'අනිෂ්ටාභිධායිනා',
 'අනු',
 'අනුකම්පමානො',
 'අනුකම්පා',
 'අනුකම්පාවෙන්',
 'අනුක්ත',
 'අනුක්තක',
 'අනුක්තස්යා',
 'අනුක්රමණිකාව',
 'අනුක්රමයෙන්',
 'අනුකූල',
 'අනුකූලයෙ',
 'අනුග්ගහීතො',
 'අනුජාති',
 'අනුජානාමි',
 'අනුජානි',
 'අනුජානීති',
 'අනුඤ්ඤාතං',
 'අනුට්ඨාන',
 'අනුත්තර',
 'අනුත්තරං',
 'අනුත්තරො',
 'අනුත්තාන',
 'අනුත්තානත්ථ',
 'අනුදනිමියි',
 'අනුදාසීන',
 'අනුදැන්',
 'අනුදැනීම',
 'අනුදැනීමෙන්',
 'අනුනය',
 'අනුන්',
 'අනුන්ට',
 'අනුප',
 'අනුපඤ්ඤත්තිතො',
 'අනුපට්ඨිත',
 'අනුපන්ධාන',
 'අනුප්පත්තො',
 'අනුප්පාදිසෙස',
 'අනුප්පාදෙත්වා',
 'අනුප්රඥප්ති',
 'අනුපාදිසෙසනිබ්බාණසංපාපකං',
 'අනුපාපුණි',
 'අනුපූර්ව',
 'අනුභව',
 'අනුභවය',
 'අනුභවයැ',
 'අනුභවී',
 'අනුමතය',
 'අනුමතයෙන්',
 'අනුමානයෙන්',
 'අනුරාධපුරය',
 'අනුරාධපුරයෙහි',
 'අනුරාපුර',
 'අනුරුද්ධ',
 'අනුරුද්ධය',
 'අනුරූ',
 'අනුලොම',
 'අනුලෝම',
 'අනුව',
 'අනුවත්ති',
 'අනුවත්තිතුං',
 'අනුවන',
 'අනුවන්ට',
 'අනුවමත්',
 'අනුවර්තන',
 'අනුව්යංජනයෙන්',
 'අනුව්යඤ්ජනයෙන්',
 'අනුවෘත්ත',
 'අනුවෘත්තඣග්රහ',
 'අනුශයාවස්ථායෙන්',
 'අනුශ්රවණාර්ථයෙහි',
 'අනුශාසනා',
 'අනුශාසනායෙහි',
 'අනුෂ්ටුබ්',
 'අනුසය',
 'අනුස්පඤ්ඤන්හිදීපනී',
 'අනූ',
 'අනූදවස',
 'අනූනං',
 'අනූනත්වයෙන්',
 'අනූපම',
 'අනූපමා',
 'අනූරියන්',
 'අනෙ',
 'අනෙක',
 'අනෙකකුගේ',
 'අනෙකත්ථ',
 'අනෙකධා',
 'අනෙකප්රකාර',
 'අනෙකවිධ',
 'අනෙකශත',
 'අනෙකශතපෞරුෂ',
 'අනෙකානි',
 'අනෙකින්',
 'අනෙකො',
 'අනෙකොපමාවෙන්',
 'අනෙත',
 'අනෙන',
 'අනේ',
 'අනේක',
 'අනො',
 'අනොණමනෙතා',
 'අනොනමන්තො',
 'අනොනිමන්තො',
 'අනොපම',
 'අනොපමෙය්ය',
 'අනොම',
 'අනොමදයි',
 'අනොමදසුයි',
 'අනොමා',
 'අනොලොකියං',
 'අනොලොකියමඤ්ජනී',
 'අනොලොකෙත්වා',
 'අනොසක්කිත්වා',
 'අනෝමදස්සී',
 'අනෝමා',
 'අඳනා',
 'අඳවන්නට',
 'අඳින්නට',
 'අඳිනා',
 'අඳුන්',
 'අඳුන්දිවිසම',
 'අඳුන්වාදීම',
 'අඳුර',
 'අඳුරයි',
 'අඳුරු',
 'අඳුරුමෙ',
 'අඳුරුයෙන්',
 'අඳුරුයෙහි',
 'අඳුරුහැරැ',
 'අප',
 'අපක්කමි',
 'අපගෙන්',
 'අපගේ',
 'අපඤ්ඤත්තා',
 'අපට',
 'අපතයෙව',
 'අපත්තාධි',
 'අපත්තාධිමාසයන්',
 'අපත්තෙ',
 'අපත්යව',
 'අපදානං',
 'අපදානය',
 'අපන්නක',
 'අපන්නකා',
 'අපපාපුණනෙ',
 'අපඵුටං',
 'අපභාග්යවතුන්',
 'අපම',
 'අපමණ',
 'අපමහ',
 'අපරං',
 'අපරචවර',
 'අපරජ්ජුගතාය',
 'අපරජ්ජුගතායාසාල්හියා',
 'අපරජ්ජුති',
 'අපරට',
 'අපරාජිත',
 'අපරාජේශ්වරිගේ',
 'අපරාධ',
 'අපරාධය',
 'අපරාධයකට',
 'අපරාධයෙක්',
 'අපරාධයෙහි',
 'අපරාන්හාදි',
 'අපරිමිත',
 'අපරිමෙය්යෙ',
 'අපරිහා',
 'අපරෙසු',
 'අපරොක්ඛෙසු',
 'අපරොක්ඛෙසුති',
 'අපසර',
 'අපස්මාරය',
 'අපහට',
 'අපහස',
 'අපහාස්ය',
 'අප්පකත්ථො',
 'අප්පකා',
 'අප්පකාදි',
 'අප්පටිපජ්ජන්නෙහි',
 'අප්පටිස්සරණෙ',
 'අප්පටිහත',
 'අප්පත්ව',
 'අප්පමත්තොච',
 'අප්පමාදං',
 'අප්පමාදංච',
 'අප්පමාදඤ්ච',
 'අප්පමාදද්ව',
 'අප්පමාදන්තිච',
 'අප්පයොගත්තා',
 'අප්පිත',
 'අප්පුගෙ',
 'අප්රත්යය',
 'අප්රතිමල්ල',
 'අප්රප්තාධි',
 'අප්රමාණ',
 'අප්රයුක්ත',
 'අප්රසිද්ධ',
 'අප්රහර්ෂශ්ව',
 'අප්රාත්තාධීමාස',
 'අප්රාප්තාධී',
 'අප්රිය',
 'අප්රීතිය',
 'අපා',
 'අපාදාන',
 'අපාදානකාරක',
 'අපාදානවචනො',
 'අපාදානසාධනො',
 'අපාදෙන්තා',
 'අපානවායු',
 'අපාය',
 'අපායාදි',
 'අපි',
 'අපිච',
 'අපිතියක්',
 'අපිවිතුරු',
 'අපුච්ඡිය',
 'අපුණ්ණ',
 'අපුත්තකත්තාව',
 'අපුත්රක',
 'අපෙ',
 'අපෙන්ති',
 'අපේ',
 'අපොහොසත්',
 'අබ',
 'අබර',
 'අබරණ',
 'අබරනින්',
 'අබහට',
 'අබ්රවුං',
 'අබ්රාහ්ම',
 'අබින්නරූපො',
 'අබිමාන',
 'අබිරුව',
 'අබිසරු',
 'අබිසෙස්',
 'අභ',
 'අභදා',
 'අභය',
 'අභයදායී',
 'අභයපුරථලප්පදෙසම්හි',
 'අභයම්පි',
 'අභවන',
 'අභාවතො',
 'අභාසථ',
 'අභි',
 'අභිචාරිකාංග',
 'අභිඤ්ඤාහා',
 'අභිඥා',
 'අභිඥාලාභීව',
 'අභිධර්ම',
 'අභිධර්මයෙහි',
 'අභිධාන',
 'අභිධානංච',
 'අභිධෙය්ය',
 'අභිධෙය්යං',
 'අභිධෙය්යො',
 'අභිනව',
 'අභිනික්ඛමි',
 'අභිනිප්ඵාදිතං',
 'අභිනීල',
 'අභිපත්ථිතාරහස්ස',
 'අභිප්රානු',
 'අභිප්රාය',
 'අභිප්රායද',
 'අභිප්රායයි',
 'අභිප්රායානුකූල',
 'අභිප්රායෙන්',
 'අභිප්රාව',
 'අභිභවනයැ',
 'අභිභායතනං',
 'අභිභූතං',
 'අභිමච්ඡා',
 'අභිමත',
 'අභිමතාර්ථ',
 'අභිමතාර්ථය',
 'අභිමුඛ',
 'අභිමුඛා',
 'අභිලාස',
 'අභිව',
 'අභිවණ්ණයිස්සං',
 'අභිව්යාප්ත',
 'අභිවාදනය',
 'අභිවායමානො',
 'අභිවෘද්ධිය',
 'අභිවෘද්ධියැ',
 'අභිවෘද්ධියෙන්යුක්ත',
 'අභිශේක',
 'අභිෂෙක',
 'අභිෂෙකය',
 'අභිෂේකය',
 'අභිස',
 'අභිසංකරිස්සං',
 'අභිසංග',
 'අභිසම්බොධි',
 'අභිසම්බොධිකථා',
 'අභීතා',
 'අභීසිත්තොපි',
 'අභූ',
 'අභූත',
 'අම',
 'අමගම',
 'අමච්චාසන්නිපතිතා',
 'අමත',
 'අමතං',
 'අමතංපදං',
 'අමතද',
 'අමන',
 'අමන්ද',
 'අමන්දව',
 'අමනුවෝ',
 'අමනොඥභාවය',
 'අමර',
 'අමරණ',
 'අමරණම්',
 'අමරපුර',
 'අමරපුරාධිපති',
 'අමරවති',
 'අමරවතියා',
 'අමරවතී',
 'අමරවර',
 'අමරාභිධානකං',
 'අම්බුජ',
 'අම්ම',
 'අම්හාකංහි',
 'අම්හෙ',
 'අම්හෙහි',
 'අමා',
 'අමාත්ය',
 'අමාත්යයන්',
 'අමාත්යයා',
 'අමාත්යවර',
 'අමාඵල',
 'අමාමහ',
 'අමාමහා',
 'අමාවක්',
 'අමාවා',
 'අමාවාසිය',
 'අමාවාසියට',
 'අමිතොදනො',
 'අමිශ්ර',
 'අමිහිරිව',
 'අමු',
 'අමුක්ත',
 'අමුතු',
 'අමුතුවෙන්',
 'අමෘත',
 'අමෘතර',
 'අඹ',
 'අඹර',
 'අඹරෙහි',
 'අඹුර',
 'අඹුවද',
 'අය',
 'අයං',
 'අයංහි',
 'අයකටනරිදන්ත',
 'අයකු',
 'අයගෙන්',
 'අයගේ',
 'අයජ',
 'අයජමෙන්',
 'අයට',
 'අයත්',
 'අයද',
 'අයදමෙන්',
 'අයදින්නෙමි',
 'අයදුමෙන්',
 'අයන්න',
 'අයපා',
 'අයම',
 'අයමත්ථො',
 'අයමත්ථොව',
 'අයමධිකාරො',
 'අයමෙත්ථ',
 'අයරලන්තෙ',
 'අයල',
 ...]

In [32]:
len(unique_tokens)

22837

In [33]:
century_tokens = list_of_file_locations.groupby('end_century')['word_count_no_punct_num'].sum().reset_index()

In [34]:
century_tokens

   end_century  word_count_no_punct_num
0            5                     1062
1           13                    10932
2           14                     5941
3           15                     6743
4           18                     3909
5           19                    11251
6           20                    19005

In [35]:
def extract_sinhala_tokens(path):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            text = f.read()
        # Keep Sinhala characters and spaces
        text = re.sub(r'[^\u0D80-\u0DFF\s]', '', text)
        return text.split()
    except Exception as e:
        print(f"Error reading {path}: {e}")
        return []

In [36]:
list_of_file_locations['tokens'] = list_of_file_locations['text_file_location'].apply(extract_sinhala_tokens)

In [37]:
list_of_file_locations['tokens'][0]

['ධර්ම',
 'ප්රදීපිකාව',
 'නමෝ',
 'තස්ස',
 'භගවතො',
 'අරහතො',
 'සම්මා',
 'සම්බුද්ධස්ස',
 'අප',
 'බුදුන්',
 'සාරාසකි',
 'කප්සුවහස්',
 'මතුයෙහි',
 'කුලුණුනු',
 'වණින්',
 'යුත්',
 'මහත',
 'වු',
 'සක්',
 'වැ',
 'දිවකුරු',
 'බුදුන්',
 'හමුවැ',
 'අතට',
 'පත්',
 'නිවන්',
 'සසර',
 'සේ',
 'පියා',
 'සතුන්',
 'සඳහා',
 'විඳුනා',
 'සසර',
 'දුක්',
 'නිවන්',
 'සේ',
 'ගෙන',
 'භව',
 'දුර්ගයට',
 'වැද',
 'පැරුම්',
 'පුරා',
 'තු',
 'පුර',
 'පැමිණ',
 'දසදහස්',
 'ලෝදාහි',
 'දෙව්බඹුන්ගේ',
 'අයජ',
 'මෙන්',
 'කිඹුල්වත්හි',
 'ඉපද',
 'වැඩිවිය',
 'පැමිණ',
 'මහභිනික්මන්',
 'කොට',
 'පැවිජි',
 'වැ',
 'මහා',
 'වීර්යය',
 'කොට',
 'බොධිපර්යංකාරූඪ',
 'වැ',
 'මාරවිජය',
 'කොට',
 'සර්වඥපදප්රාප්ත',
 'වැ',
 'හුනස්නෙන්',
 'නැඟී',
 'පූර්වොත්තර',
 'දිශා',
 'භාගයෙහි',
 'වැඩ',
 'සිට',
 'සප්තාහයක්',
 'අනිමිසලෝචන',
 'යුගලයෙන්',
 'පුදන',
 'ලද',
 'ජය',
 'මහා',
 'බොධිය',
 'තත',
 'ප්රභව',
 'වූ',
 'ඵල',
 'රුහ',
 'මහා',
 'බොධිය',
 'තදවයව',
 'වූ',
 'ශාඛා',
 'හා',
 'බොධිය',
 'යන',
 'තුන්',
 'මහා',
 'බොධීන්ගේ',
 'වංශයෙහි',
 'සහස්රරශ්මින්',
 'විභක්ත',
 'පදයන්',
 'අතුරෙහි',
 'පරිකථානුකූල',
 'පද',
 'ගෙන',
 'වර්ණනා',
 'කරනු',
 'ලැබේ',
 'යස්ස',
 'යනු',
 'චතුර්විධ',
 'පදයන්',
 'කෙරෙහි',
 'නාමපදයි',
 'එහි',
 'චතුර්විධ',
 'පද',
 'නම්',
 'කවරයත්',
 'නාම',
 'පදය',
 'ආඛ්යාත',
 'පදය',
 'උපසර්ග',
 'පදය',
 'නිපාතපදයි',
 'එහි',
 'නාම',
 'පද',
 'නම්',
 'සර්වාර්ථයන්',
 'නමන්නෙන්',
 'නාම',
 'පද',
 'නම්',
 'වේ',
 'එයින්',
 'කීහ',
 'යත්ත්රිලිංගං',
 'ත්රිවචනං',
 'සර්වාසු',
 'ච',
 'විභක්තිෂු',
 'නමත්යර්ථෙන',
 'සර්වාර්ථා',
 'නාම',
 'කවයො',
 'විදුඃ',
 'යී',
 'ක්රියාවාචක',
 'පද',
 'ආඛ්යාත',
 'නම්',
 'වේ',
 'එයින්',
 'කීහ',
 'යත්ත්රි',
 'කාලං',
 'ත්රිපුරුෂං',
 'ක්රියාවාචි',
 'ත්රිකාරකම්',
 'අත්රිලිංගං',
 'ත්රිවචනං',
 'තදාඛ්යාතං',
 'ප්රවක්ෂතෙ',
 'යී',
 'සාරාසංඛ්ය',
 'ලෝධාහි',
 'ධර්ම',
 'ප්රදීපිකා',
 'ක්රියා',
 'දොතක',
 'පද',
 'උපසර්ග',
 'නම්',
 'වේ',
 'එයින්',
 'කීහ',
 'යස්මාදුප',
 'සෘජන්තයන්',
 'පදස්යාපරි',
 'ගච්ඡති',
 'ක්රියායොග',
 'වහස්ත',
 'ස්මාදුප',
 'සර්ග',
 'ඉති',
 'ස්මෘතඃ',
 'යී',
 'දක්වන',
 'ලද',
 'පදයන්ගේ',
 'ආද්යන්ත',
 'මධ්යයෙහි',
 'නිපතිත',
 'වූ',
 'විචිත්රාර්ථ',
 'පදයෝ',
 'නිපාත',
 'නම්',
 'වෙත්',
 'එයින්',
 'කීහ',
 'යස්මාදාද්යාන්තමධ්යෙෂු',
 'වාක',
 'ප්රයොග',
 'විශෙෂතඃ',
 'නිපතන්ති',
 'විචිත්රාර්ථා',
 'නිපාතාසතුතු',
 'සංඥතාඃ',
 'යි',
 'මේ',
 'චතුර්විධ',
 'පදයන්ගේ',
 'ප්රයෝග',
 'දක්වන්නට',
 'කීහ',
 'පදං',
 'චතුර්විධං',
 'ප්රොක්තං',
 'නාමාඛ්යාතොප',
 'සර්ගජම්',
 'නිපාතජච',
 'ශබ්ද',
 'ඥෙරවඃ',
 'ඛලවභිධාවති',
 'යී',
 'මේය',
 'චතුර්විධ',
 'පද',
 'නම්',
 'නිසිතෙනාව',
 'යන',
 'තන්හි',
 'එව',
 'යන',
 'නිපාතය',
 'අයොග',
 'ව්යවඡදකය',
 'අන්ය',
 'යොග',
 'ව්යවච්ඡේදකය',
 'අත්යන්තා',
 'යොග',
 'ව්යව',
 'ච්ඡේදකය',
 'යි',
 'ත්රිවිධ',
 'වූයේ',
 'අන්ය',
 'යොග',
 'ව්යවච්ඡේදක',
 'වේ',
 'එහි',
 'විශෙෂණයා',
 'කෙරෙන්',
 'පර',
 'කොට',
 'ප්රයෝග',
 'කරන',
 'ලද',
 'එවකාරය',
 'අයොග',
 'ව්යවච්ඡේදක',
 'වෙයි',
 'චෛත්රො',
 'ධනුර්ධර',
 'එව',
 'යන',
 'තන්හි',
 'සෙයින්',
 'විශෙෂයා',
 'කෙරෙන්',
 'පර',
 'කොට',
 'ප්රයෝග',
 'කරන',
 'ලද',
 'එව',
 'කාරය',
 'අන්ය',
 'යොග',
 'ව්යවච්ඡේදක',
 'වෙයි',
 'පාර්ථි',
 'එව',
 'ධනුද්ධරඃ',
 'යන',
 'තන්හි',
 'සෙයින්ක්රියායෙන්',
 'පර',
 'කොට',
 'ප්රයොග',
 'කරන',
 'ලද',
 'එව',
 'කාරය',
 'අත්යන්තා',
 'යොග',
 'ව්යවච්ඡේදක',
 'වෙයි',
 'නීලං',
 'සරොජම',
 'සෙත්යව',
 'යන',
 'තන්හි',
 'සෙයින්වාක්යයන්',
 'ව්යවච්ඡේද',
 'ඵල',
 'වන',
 'බැවින්',
 'නිපාතයා',
 'ප්රයෝග',
 'නොකළද',
 'විවක්ෂා',
 'වශයෙන්',
 'ඔහුගේ',
 'අර්ථ',
 'ප්රතීත',
 'වේ',
 'මැයි',
 'එයින්',
 'කීහ',
 'ධර්ම',
 'කීර්තිපාදයෝ',
 'අයොගං',
 'යොගම',
 'පරෛරත්යන්තා',
 'යොග',
 'මෙව',
 'ච',
 'ව්යවච්ඡිනත්ති',
 'ධර්මස්ය',
 'නිපාතො',
 'ව්යතිරෙචකඃ',
 'විශේෂණ',
 'විශේෂ්යාභ්යා',
 'ක්රියයා',
 'ච',
 'සහොදිතඃ',
 'විවක්ෂාතො',
 'ප්රයොගෙ',
 'පි',
 'තයාර්ථෙ',
 'යං',
 'ප්රතීයතෙ',
 'ව්යවච්ඡෙද',
 'ඵලං',
 'වාක්යං',
 'යතා',
 'චිත්රො',
 'ධනුද්ධරඃ',
 'පාථො',
 'ධනුර්ධරො',
 'නීලං',
 'සරොජමස්ති',
 'වා',
 'යථා',
 'සරොජමිති',
 'යන',
 'පාඨය',
 'මෙහි',
 'පුර්වොක්තිය',
 'හා',
 'නොගැළපේ',
 'අහීස',
 'මාධි',
 'කථා',
 'ප්රතියොග',
 'ව්යවච්ඡෙදස්තත්රාප්යර්වෙෂු',
 'ගම්යතෙ',
 'තථා',
 'ප්රසිද්ධෙස්සා',
 'ධර්මර්ෂ්යාවක්ෂානුගමානෝ',
 'යී',
 'පත්තෝ',
 'සබ්බඤ්ඤැතං',
 'සත්ථා',
 'යනුයෙන්',
 'දක්වන',
 'ලද',
 'බුදුහු',
 'අනන්තා',
 'පරිමාණ',
 'ගුණ',
 'ඇතියෝ',
 'කිසේය',
 'යත්',
 'බුදුහු',
 'රූප',
 'විලාසයෙනුදු',
 'වචන',
 'විලාසයෙනුදු',
 'ඥාන',
 'විලාසයෙනුදු',
 'අචින්ත්යයහ',
 'අවාච්යයහ',
 'අතුල්යහ',
 'අවෙද්යයෝයි',
 'එව්හු',
 'අචින්ත්ය',
 'වන',
 'බැවින්',
 'චින්තා',
 'විෂයාතික්රාන්තයහ',
 'අවාච්ය',
 'වන',
 'බැවින්',
 'වාග්',
 'විෂයාතික්රාන්ත',
 'සහ',
 'අතුල්ය',
 'වන',
 'බැවින්',
 'උපමා',
 'විෂයාතික්රාන්තයහ',
 'අද',
 'වන',
 'බැවින්',
 'ඥාන',
 'විෂයාතික්රාන්තයහ',
 'කපකුදු',
 'වූ',
 'දවස්',
 'තම',
 'සේම',
 'වූ',
 'බුදු',
 'කෙනෙකුනුදු',
 'කියත්',
 'නොගෙවෙන',
 'ගුණ',
 'ඇතියෝ',
 'මහ',
 'මුහුදැ',
 'හෙළූ',
 'සිදුහතුළුදු',
 'කළ',
 'සැළදු',
 'තම',
 'තමා',
 'පමණින්',
 'දියගන්නා',
 'සේ',
 'ඒ',
 'බුදු',
 'රජහුගේ',
 'ගුණ',
 'මුහුදට',
 'වන්',
 'පසේ',
 'බුදුහුදු',
 'බුදු',
 'සවෝද',
 'තම',
 'තමන්ගේ',
 'නුවණ',
 'පමණින්',
 'ගන්ති',
 'ගුණ',
 'පමණින්',
 'ගන්නට',
 'නොනිසෝ',
 'ගංගාය',
 'වාලුකා',
 'බීයෙ',
 'උදකං',
 'ඛීයෙ',
 'මහණ්ණ',
 'වෙ',
 'මහියා',
 'මත්තිකා',
 'ඛීයෙ',
 'ලක්ඛෙන',
 'මම',
 'බුද්ධියා',
 'යී',
 'ඥානගර්ජනා',
 'කරන්නට',
 'සමර්ථ',
 'වූ',
 'ධර්ම',
 'සෙනෙවි',
 'සැරියුත්',
 'මහතෙ',
 'රුන්',
 'වැනි',
 'මහා',
 'පුරුෂයනටත්',
 'අවිෂය',
 'වූ',
 'බුදු',
 'ගුණ',
 'පුහුදුන්',
 'වැ',
 'කියම්',
 'හයි',
 'සිතනු',
 'මදුරු',
 'දළින්',
 'විදුරු',
 'ගිරි',
 'විදුනාක්',
 'පින',
 'හැඹිළි',
 'දළින්',
 'මහ',
 'පොළොව',
 'උකුල්',
 'දෙනුවක්',
 'වැනි',
 'බැවින්',
 'තම',
 'හට',
 'අවිෂය',
 'වතුදු',
 'ප්රසාද',
 'පරවශ',
 'වැ',
 'ප්රවචන',
 'වහල්',
 'කොට',
 'ශ්රද්ධා',
 'බුද්ධි',
 'සම්පන්නජනයන්',
 'සඳහා',
 'කතිපය',
 'ගුණයෙක්',
 'දක්වනු',
 'ලැබේ',
 'බුදුන්ගේ',
 'ගුණයෙහි',
 'පුහුදුනන්',
 'හාද',
 'සව්පසේ',
 'බුදුන්',
 'හාද',
 'සාධා',
 'රණ',
 'ගුණයෝ',
 'ඇත්මය',
 'අසාධාරණ',
 'ගුණයෝ',
 'ඇත්මැයි',
 'එහි',
 'සෙසු',
 'තිරිසනුන්',
 'හා',
 'සාධාරණ',
 'තණ',
 'කබල',
 'ගඳැත්කුස',
 'දිරුණ',
 'සිව්',
 'දෑ',
 'ගඳ',
 'වන',
 'සෙයින්',
 'පුහුදුන්',
 'ආදීන්',
 'හා',
 'සාධාරණ',
 'වූ',
 'රූපශොභාද',
 'ධ්යානාභි',
 'ඥාදි',
 'ගුණයෝද',
 'බුදු',
 'සතන්හිලා',
 'අසාධාරණ',
 'වෙති',
 'නොරබීජ',
 'නෙහි',
 'නොසිටුනා',
 'සිංහ',
 'තෙල්',
 'සෙයින්',
 'දශබල',
 'චතුර්වෛශාරද්යාදි',
 'අසාධාරණ',
 'ගුණයෝ',
 'වූ',
 'කල',
 'නොබුදු',
 'සතන්හි',
 'ලා',
 'නොසිටිත්',
 'ඔවුන්ගේ',
 'රූප',
 'විලාස',
 'නම්',
 'කවරයත්',
 'ද්වාත්රිංශන්මහා',
 'පුරුෂ',
 'ලක්ෂණයෙන්',
 'හා',
 'අශීති',
 'අනුව්යංජනයෙන්',
 'ප්රජ්වලිත',
 'රූප',
 'ශොභායි',
 'එහි',
 'ද්වාත්රිංගන්',
 'මහා',
 'පුරුෂ',
 'ලක්ෂණ',
 'නම්',
 'කවරයත්',
 'වදාළේ',
 'මැනො',
 'බුදුන්',
 'විසින්',
 'සුප්පතිටඨිත',
 'පාදො',
 'හෙට්ඨාපාදතලෙසු',
 'චක්කානි',
 'ජාතානී',
 'සහ',
 'සාරානී',
 'සනෙමිකානි',
 'සනාභිකානි',
 'සබ්බාකාර',
 'පරිපුරානි',
 'ආයත',
 'තෙසු',
 'ධර්ම',
 'ප්රදීපිකා',
 'පණහි',
 'දීඝගුලි',
 'මුදු',
 'තලු',
 'නහත්ථ',
 'පාදො',
 'ජාල',
 'හත්ථපාදො',
 'උස්සං',
 'ඛපාදො',
 'එණිජංඝො',
 'ඨිතකා',
 'අනොනිමන්තො',
 'උභොහි',
 'පාණී',
 'තලෙහි',
 'ජෂ්ණුකානි',
 'පරිමසති',
 'පරිමජ්ජතිකොසොහිතවත්ථගු',
 'හ',
 'සුවණ්ණවණ්ණො',
 'කඤචන',
 'සන්නිභත්තචො',
 'සුඛුමච්ඡවි',
 'වි',
 'සුඛුමන්තා',
 'ඡවියා',
 'රජො',
 'ජල්ලං',
 'කායෙ',
 'න',
 'උපලිප්පති',
 'එකෙක',
 'රජොජල්ලං',
 'ලොමො',
 'එකෙකානි',
 'ලොමානි',
 'ලොමකූපෙසු',
 'ජාතානි',
 'උඩග්ග',
 'ලොමො',
 'උද්ධග්ගානි',
 'ලොමානි',
 'ජාතානි',
 'නිලානි',
 'අඤ්ජන',
 'වණ්ණානි',
 'කුණ්ඩ',
 'ලාවත්තානි',
 'පදක්ඛිණාවත්තක',
 'ජාතානි',
 'බ්රහ්මුජ්ජුගත්තො',
 'සත්තු',
 'සීහ',
 'පුබ්බකායො',
 'චිතන්තරංසො',
 'නිග්රොධ',
 'පරිමණ්ඩ',
 'ලො',
 'යාවතඣස්ස',
 'කායො',
 'තාවතස්ස',
 'ව්යාමො',
 'යාවතස්ස',
 'ව්යාමො',
 'තාවතඤස්ස',
 'කායො',
 'සමවත්තක්ඛන්ධො',
 'රසග්ගසග්ගි',
 'සීහහනු',
 'චත්තාලීසදනෙන්තො',
 'සමදන්තො',
 'අවිවර',
 'දන්තො',
 'සුසුක්කදාඨො',
 'පහූත',
 'ජි',
 'වෙහා',
 'බ්රහ්මස්සරෝ',
 'කරවීකභාණී',
 'අභිනීල',
 'නෙත්තො',
 'ගොපඛුමො',
 'උණ්ණා',
 'භමුකන්තරෙ',
 'ජාතා',
 'ඔදාතා',
 'මුදුතු',
 'ලසන්නිභා',
 'උණහීස',
 'සීසො',
 'යී',
 'මෙහි',
 'සුප්පතිටඨිතපාදො',
 'යන',
 'තන්හි',
 'සුප්රතිෂ්ඨිතපාදතා',
 'නම්',
 'කවරයත්',
 'අනුන්',
 'පතුල්',
 'බිම',
 'ඔබන',
 'කලැ',
 'අග්ර',
 'පාද',
 'තලය',
 'හෝ',
 'පාර්ෂණිය',
 'හෝ',
 'පාර්ශවය',
 'හෝ',
 'පෙරට',
 'වැ',
 'භූමි',
 'ස්පර්ශ',
 'කෙරෙහි',
 'පාදතල',
 'මධ්යයෙහි',
 'ජිදු',
 'හෝ',
 'වෙයි',
 'පත්ල',
 'නඟන',
 'කලද',
 'අග්රපාදතලාදීන්',
 'කෙරෙන්',
 'අන්යතර',
 'ස්ථානයෙක්',
 'පෙරට',
 'වැ',
 'නැඟෙයිමොවුන්',
 'පතුල්',
 'වූ',
 'කල',
 'ස්වර්ණපාදුකා',
 'සෙයින්',
 'එක',
 'පැහැර',
 'භූමි',
 'සපර්ශ',
 'කෙරෙයි',
 'එක',
 'පැහැර',
 'නැගේ',
 'ඉදින්',
 'අනෙකශත',
 'පෞරුෂ',
 'නරක',
 'ප්රපාතයෙහි',
 'ඇක්මෙමියි',
 'පය',
 'එයට',
 'ඵළ',
 'වූයේ',
 'වී',
 'නම්',
 'එම',
 'විගස',
 'වළ',
 'තැන්',
 'භස්ත්රාසෙ',
 'යින්',
 'පිරෙයි',
 'ගොඩ',
 'තැන්',
 'භෙරිතල',
 'සෙයින්',
 'සම',
 'වේ',
 'දුර',
 'ඇක්මෙමියි',
 'පය',
 'නැඟුයේ',
 'වී',
 'නම්',
 'ප්රාතිහාර්යාවසානයෙහි',
 'සෙයින්',
 'මෙරු',
 'ප්රමාණ',
 'පර්වතයෙකුදු',
 'හුයාපී',
 'වෙයග',
 'බඩක්',
 'සෙයින්',
 'නැමී',
 'පාද',
 'සමීපයට',
 'උප',
 'ගත',
 'වේ',
 'එයින්',
 'කීහ',
 'නින්නං',
 'ඨානං',
 'උණ්ණමති',
 'ගච්ඡන්තෙ',
 'ලොක',
 'නාය',
 'කෙ',
 'උණ්ණතංච',
 'සමං',
 'හොති',
 'පඨවී',
 'ච',
 'අචෙතනා',
 'පාසාණා',
 'සක්ඛරා',
 'චෙව',
 'කඨලා',
 'ඛාණු',
 'කණට',
 'කා',
 'සබ්බෙ',
 'මග්ගා',
 'විවජ්ජෙන්ති',
 'ගච්ඡන්තෙ',
 'ලොක',
 'නාය',
 'කෙ',
 'ගච්ඡතො',
 'බුද්ධසෙට්ඨස්ස',
 'හෙට්ඨාපාදතලං',
 'මුදු',
 'සමං',
 'සත්ථුසතෙ',
 'භූමිං',
 'රජසා',
 'නූපලිප්පනි',
 'නාග',
 'වික්කන්තචාරො',
 'සො',
 'ගමනෙ',
 'සොභතෙ',
 'ජිනො',
 'චාරුං',
 'ගච්ඡති',
 'ලොකග්ගො',
 'හාසයන්තො',
 'සදෙවකෙ',
 'යී',
 'අභිස',
 'ඹාධිකය',
 'මෙසෙයින්',
 'සුප්රතිෂ්ඨිත',
 'වූ',
 'පාද',
 'තලද්වය',
 'ඇති',
 'වන',
 'බැවින්',
 'සුප්රතිෂ්ඨිත',
 'පාද',
 'නම්',
 'වෙත්',
 'බුදුහු',
 'හෙට්ඨාපාදතලෙසු',
 'චක්කානි',
 'ජාතානි',
 'යන',
 'තන්හි',
 'චක්රයෝ',
 'නම්',
 'කවරහයත්',
 'බුදුන්',
 'දෙපත්ලෙහි',
 'දෙචක්රයෙක්',
 'විය',
 'එකි',
 'එකී',
 'චක්රයෙහි',
 'දහස්',
 'දහස්',
 'දැව්',
 'විය',
 'නෙමිදු',
 'විය',
 'නාභිදු',
 'වී',
 'ඒ',
 'චක්රයෙහි',
 'පාදතල',
 'මධ්යයට',
 'වැ',
 'නාභි',
 'පැනෙයි',
 'නාභි',
 'වටා',
 'සිටි',
 'වටරෙඛා',
 'පැනෙයි',
 'නාභිමුඛ',
 'වටා',
 'සිටි',
 'වට',
 'පැනෙයි',
 'ඡිද්රමුඛ',
 'පැනෙයි',
 'දැවි',
 'පැනෙයි',
 'දැවියෙහි',
 'වටරෙඛා',
 'පැනෙයි',
 'නෙමි',
 'පැනෙයි',
 'නෙමිමණි',
 'පැනෙයි',
 'ඒ',
 'වටා',
 'ස්වස්තිකය',
 'ශ්රීවත්සය',
 'නන්දාවර්තය',
 'සෞවස්තිකය',
 'අවතංස',
 'කය',
 'වර්ධමානකය',
 'භද්ර',
 'පීඨය',
 'ප්රාසාදය',
 'තොරණය',
 'ශ්වේතච්ඡත්රය',
 'ඛංඩගය',
 'තාලවෘත්තය',
 'මයුර',
 'හස්තය',
 'චාමරය',
 'උෂ්ණීෂය',
 'මණිය',
 'සුමනාදාමය',
 'නීලොත්පලය',
 'රක්තොත්පලය',
 'රක්ත',
 'පද්මමය',
 'ශ්වෙත',
 'පදමය',
 'පූර්ණකලසය',
 'පූර්ණපාත්රය',
 'සමුදාය',
 'චක්රවාල',
 'පර්වතය',
 'හිමවත්',
 'පර්වතය',
 'මෙරු',
 'පර්වතය',
 'සුර්යය',
 'මණ්ඩලය',
 'චන්ද්ර',
 'මණ්ඩලය',
 'සපරිවාර',
 'සතර',
 'මහාද්වීපය',
 'ස්පර්ෂත',
 'සප්තරත්න',
 'චක්රවර්තිය',
 'දක්ෂිණා',
 'වර්ණා',
 'ශ්වෙතශංඛය',
 'ස්වර්ණ',
 'මතස්යයුගලය',
 'චක්රායුධයසපත',
 'මහා',
 'ගංගාය',
 'සප්ත',
 'මහා',
 'ශෛලය',
 'සප්ත',
 'මහාභ්රදය',
 'සුපර්ණ',
 'රාජය',
 'ශිශුමාරය',
 'ධ්වජය',
 ...]

In [38]:
# def load_stopwords(file_path):
#     try:
#         with open(file_path, 'r', encoding='utf-8') as f:
#             stopwords = f.read().splitlines()
#             # Remove empty lines and strip whitespace
#             stopwords = [word.strip() for word in stopwords if word.strip()]
#             return set(stopwords)  # set is faster for lookups
#     except Exception as e:
#         print(f"Error loading stopwords from {file_path}: {e}")
#         return set()

In [39]:
# sinhala_stopwords = load_stopwords("stop words.txt")

In [40]:
# sinhala_stopwords

In [41]:
# list_of_file_locations['filtered_tokens'] = list_of_file_locations['tokens'].apply(
#     lambda tokens: [word for word in tokens if word not in sinhala_stopwords]
# )

In [42]:
# all_tokens = sum(list_of_file_locations['filtered_tokens'], [])

In [43]:
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt

In [44]:
# counter = Counter(all_tokens)
# top_words = counter.most_common(100)

In [45]:
# top_words

In [46]:
# words, freqs = zip(*top_words)
# plt.figure(figsize=(12, 6))
# plt.bar(words, freqs, color='mediumseagreen')
# plt.xticks(rotation=45, ha='right', fontsize=13)
# plt.ylabel("Frequency")
# plt.title("Top 20 Sinhala Words")
# plt.tight_layout()
# plt.show()

In [47]:
# wordcloud = WordCloud(
#     font_path="NotoSerifSinhala-VariableFont_wdth.ttf",  # Make sure Sinhala font is available
#     background_color='white',
#     width=800,
#     height=400
# ).generate_from_frequencies(counter)

# plt.figure(figsize=(12, 6))
# plt.imshow(wordcloud, interpolation='bilinear')
# plt.axis('off')
# plt.title("Sinhala Word Cloud", fontsize=16)
# plt.show()

In [48]:
century_tokens = list_of_file_locations.groupby('end_century')['tokens'].sum()  # flatten lists
century_tokens = century_tokens.to_dict()

In [49]:
century_tokens

{5: ['සාරාර්ථ',
  'සංග්රඥාව',
  'තමස්ත',
  'භගවතෙහිත',
  'සම්යක්',
  'යමු',
  'බුද්ධාය',
  'නත්වා',
  'මුනින්දචරණං',
  'තිභවෙක',
  'සෙට්ඨං',
  'සන්තෙහි',
  'වුත්ත',
  'විවිධං',
  'වරතන්තසත්ථෙ',
  'අත්ථං',
  'හිසක්ක',
  'කුසලෙහි',
  'සමුචරිත්වා',
  'වක්ඛාමි',
  'සංගහ',
  'මං',
  'ජනසංග',
  'හත්ථං',
  'තිභවෙක',
  'සෙට්ඨං',
  'කාම',
  'ලොක',
  'රූප',
  'ලොක',
  'අරූපලෝක',
  'යන්',
  'ලොකත්රයට',
  'ශ්රෙෂ්ඨ',
  'වූ',
  'මුනින්ද',
  'චරණං',
  'මුනීන්ද්ර',
  'නම්',
  'වූ',
  'සම්යක්',
  'සම්බුද්ධයන්',
  'වහන්සේගේ',
  'ශ්රී',
  'පාද',
  'පද්මය',
  'නත්වා',
  'භය',
  'ලොහ',
  'කුලාචාරයෙන්',
  'විනා',
  'සකසා',
  'වැඳ',
  'සන්තෙහි',
  'සකල',
  'ශාස්ත්රයෙහි',
  'පාරප්රාප්ත',
  'පණ්ඩිත',
  'වූ',
  'භී',
  'සක්ක',
  'කුසලෙහි',
  'භෛෂජ්යාර්ථයෙහි',
  'දක්ෂ',
  'වූ',
  'වෙදුන්',
  'විසින්',
  'වර්ණ',
  'තන්තස්සත්ථෙ',
  'උතුම්',
  'වූ',
  'රස',
  'සංහිතාදි',
  'තන්ත්ර',
  'ශාස්ත්රයෙහි',
  'වුත',
  'කියන',
  'ලද',
  'විවිධං',
  'නානාප්රකාර',
  'වූ',
  'අත්ථං',
  'සාරාර්ථය',
  'සමුචරිත්වා',
  'උදුරාගෙණ',
  'ජනසංගහත්ථං',
  'සකල',
  'සත්වයන්ගේ',
  'රොග',
  'ව්යපසමන',
  'සංඛ්යාත',
  'සංග්රහව',
  'පිණිස',
  'ඉමං',
  'සංගහං',
  'මේ',
  'සාරාර්ථ',
  'සංග්රහ',
  'නම්',
  'ප්රකරණය',
  'වක්ඛාමි',
  'සර්ථාවබොධය',
  'සඳහා',
  'කියන්නෙමි',
  'බ්රහ්මා',
  'ප්රොවාව',
  'සොවර්ග',
  'වෙද',
  'මායු',
  'නිබන්ධ',
  'නම්',
  'ශිෂ්යායාං',
  'කථයාමාස',
  'කාශි',
  'රාජොත්තමඃ',
  'ක්රමාත්',
  'යනාදී',
  'අනෙකවිධ',
  'මානයෙන්',
  'දැක්වූ',
  'මේ',
  'වෛද්ය',
  'ශාස්ත්රය',
  'ප්රථම',
  'කල්පයෙහි',
  'ලෝකාර්ථය',
  'කරන්නා',
  'වූ',
  'මහ',
  'බ්රහ්මයා',
  'දක්ෂ',
  'පුජාපති',
  'හට',
  'කීහ',
  'දක්ෂ',
  'ප්රජාපති',
  'අග',
  'විනීන්',
  'දෙදෙනා',
  'හට',
  'කීහ',
  'අගවිනි',
  'දෙදෙනා',
  'ශක්රයාහට',
  'කීහ',
  'ශක්රයා',
  'ධන්වන්තරී',
  'හට',
  'කීහ',
  'ධන්වන්ත',
  'සුශ්රුතාදී',
  'රුසිවරයන්ට',
  'කීහ',
  'රුසිවරු',
  'කසී',
  'රජහට',
  'කීහ',
  'ශිෂ්යානුශිෂ්ය',
  'පරම්පරානුගතව',
  'පැවැත්තා',
  'වූ',
  'මේ',
  'වෛද්ය',
  'ශාස්ත්රය',
  'අධි',
  'දීර්ඝ',
  'කාලයකින්',
  'ග්රන්ථි',
  'ස්ථාන',
  'ශුඪවීය',
  'තථාගතයන්',
  'වහන්සේ',
  'විසින්',
  'දක්වන',
  'ලද',
  'උතුම්',
  'වූ',
  'ධර්මය',
  'සත්ව',
  'කරුණාවෙන්',
  'බොහෝ',
  'කල්',
  'පට',
  'තිනා',
  'ලෙස',
  'වදාළ',
  'සේක්',
  'නම්',
  'එසේම',
  'ලොකාචාර්යය',
  'ඍෂින්',
  'විසින්',
  'කරුණාධ්යාසයෙන්',
  'කල්පායුෂ්ක',
  'කාලයක්',
  'පවතිනා',
  'පරිද්දෙන්',
  'හදා',
  'ගුඪාර්ථ',
  'සහිත',
  'වූ',
  'වෛද්ය',
  'ශාස්ත්රය',
  'ජීවකයන්හට',
  'කීවාහුය',
  'ඔහු',
  'විසින්',
  'හිමිව',
  'විපුලව',
  'ප්රසිද්ධ',
  'කළේයි',
  'ඔවුන්',
  'කයයෙකුදු',
  'පවත්තා',
  'සාරාර්ථ',
  'සංග්රහව',
  'ලද',
  'මේ',
  'මහා',
  'වෛද්යාණිවයට',
  'බැස',
  'බලනු',
  'හැම',
  'සත්වයන්ට',
  'උගහටසේ',
  'දැක',
  'සිතු',
  'සේ',
  'බැස',
  'ඇවිදිනා',
  'සකල',
  'සත්ව',
  'වර්ගයන්ට',
  'නානා',
  'ස්ථානගත',
  'සෘෂි',
  'ප්රොක්ත',
  'උදාහරණ',
  'ලොකාචරණයෙන්',
  'සමලංකෘත',
  'වූ',
  'නිර්ව්යාජ',
  'ස්වභාෂානු',
  'කථාවෙන්',
  'වණන්නෙමි',
  'හිෂක්',
  'ශාස්ත්රයක්',
  'ප්රකාශ',
  'කරන්',
  'නෙමැයි',
  'සේයි',
  'මෙසේ',
  'ශාස්ත්රොත්පත්ති',
  'කථනයෙන්',
  'ගරු',
  'භාවය',
  'ප්රකාශ',
  'කොට',
  'භිෂගුත්තමයා',
  'හට',
  'වෛද්යයාංගයන්',
  'දක්වත්',
  'වෛද්යගයෝ',
  'දූත',
  'ලක්ෂණ',
  'නෛම්ත්ත',
  'මංග',
  'ස්වජන',
  'මරිෂ්ටකම්',
  'ආරොග්ය',
  'විපරිතඤ්ච',
  'භිෂග්',
  'භෛෂජමාතුරඃ',
  'පරිචාරක',
  'සම්පත්ති',
  'ව්යාධි',
  'ප්රකෘති',
  'ස්ථානකං',
  'දේශ',
  'කාල',
  'වයො',
  'දෙහ',
  'සත්ව',
  'සාත්මි',
  'ක',
  'ලක්ෂණම්',
  'රස',
  'දොෂ',
  'ස්වභාවඤ්ච',
  'සර්වදොෂ',
  'සමුද්භවම්',
  'තථෛව',
  'දොෂ',
  'ගමනං',
  'ත්රිවිධං',
  'ව්යාධි',
  'ලක්ෂණම්',
  'ආමාග්නි',
  'බල',
  'මාදානං',
  'නිදානං',
  'පුර්ව',
  'හෙතුව',
  'ත්රිංශ',
  'දංගාන්',
  'භිෂග්',
  'දෘෂ්ටවා',
  'කර්ම',
  'භෛෂජ්ය',
  'මාචරෙත්',
  'දූත',
  'ලක්ෂණ',
  'දූත',
  'ලක්ෂණය',
  'නෛමි',
  'නෛමිත්ත',
  'ලක්ෂ',
  'ණය',
  'අංග',
  'අංග',
  'ලක්ෂණය',
  'ස්වප්නං',
  'ස්වප්න',
  'ලක්ෂණය',
  'අරිෂ්ටකම්',
  'අරිෂ්ට',
  'ලක්ෂණය',
  'ආරොග්ය',
  'ආරොග්ය',
  'ලක්ෂණය',
  'විපරිතඤ්ච',
  'විපරිත',
  'ලක්ෂණය',
  'හික්භිෂක්',
  'සම්පත්ය',
  'භෛෂජං',
  'භෛෂජ්ය',
  'සම්පත්ය',
  'ආතුරා',
  'ආතුර',
  'සම්පත්ය',
  'පරිවාරක',
  'සම්පත්නි',
  'පරිවාරක',
  'සම්පත්ය',
  'ව්යාධි',
  'ව්යාධි',
  'ලක්ෂණය',
  'ප්රකෘති',
  'ප්රකෘති',
  'ලක්ෂණය',
  'ස්ථානකං',
  'ස්ථාන',
  'ගතව්යාධිය',
  'දෙශ',
  'දෙශ',
  'ගුණය',
  'කාල',
  'කාල',
  'ගුණය',
  'වයඃ',
  'වයො',
  'ලක්ෂණය',
  'දෙහ',
  'දෙහ',
  'ලක්ෂණය',
  'සතත්ව',
  'සතත්ව',
  'ලක්ෂණය',
  'සාත්මික',
  'ලක්ෂණං',
  'සාත්මික',
  'ලක්ෂණය',
  'රස',
  'රස',
  'ලක්ෂණය',
  'දොෂ',
  'ස්වභාවඤ්ච',
  'දොෂ',
  'ස්වභාවය',
  'සර්වදොෂ',
  'සමුද්හවම්',
  'සියළු',
  'දොෂයන්ගේ',
  'උද්භවය',
  'තථා',
  'එව',
  'එසේම',
  'දොෂශමනං',
  'දොෂ',
  'ශම්නය',
  'ත්රිවිධං',
  'තුන්වැදෑ',
  'රුම්',
  'වූ',
  'ව්යාධි',
  'ලක්ෂණම්',
  'ව්යාධි',
  'ලක්ෂණය',
  'ආම',
  'ආම',
  'බලය',
  'අග්නි',
  'බලං',
  'අග්නි',
  'බලිය',
  'ආදානං',
  'ආදාන',
  'ලක්ෂණය',
  'නිදානං',
  'නිදාන',
  'ලක්ෂණය',
  'පූර්ව',
  'හේතුව',
  'පූර්ව',
  'හේතු',
  'ලක්ෂණයයි',
  'යන',
  'ත්රිංශත්',
  'අංගාන්',
  'මේ',
  'තිස්',
  'අංග',
  'යන්ගේ',
  'ලක්ෂණ',
  'භිෂක්',
  'වෙද',
  'තෙම',
  'දෘෂ්ටවා',
  'බලා',
  'දැක',
  'භෛෂජ්යං',
  'කර්ම',
  'භෛෂජ්යකර්මය',
  'ආවරෙත්',
  'මනාකොට',
  'කරන්නේය',
  'ත්රිංග',
  'හි',
  'ංග',
  'එහි',
  'පූර්වග',
  'දූත',
  'ලක්ෂණ',
  'නම්',
  'විජාති',
  'ව්යංග',
  'පාෂණ්ඩ',
  'පාශදණ්ඩායුධොද්ගතාඃ',
  'රක්තා',
  'ශිත',
  'විජිණෙක',
  'වස්ත්රානි',
  'අෂ්ටාභීධායිනඃ',
  'කරාවමදී',
  'මුක්තාශ්රැ',
  'සෙන',
  'භාරාංග',
  'තෘණච්ඡිද',
  'ස්ත්රීනපුංසක',
  'ව්යංග',
  'දෙහ',
  'සපෘෂ්ඨපාණයඃ',
  'ඛරොෂ්ට්ර',
  'මහිෂාරූඪ',
  'මුග',
  'ගර්හාදිභාෂිනඃ',
  'එතෙ',
  'දූතා',
  'විරුධ්යන්තෙ',
  'ප්රශස්තාශ්ව',
  'විපර්යයාඃ',
  'විජාති',
  'හීන',
  'ජාතිය',
  'ව්යංග',
  'අංග',
  'විකාරිය',
  'පාෂණ්ඩ',
  'ජටාමකුට',
  'ධාරීය',
  'හෙවත්',
  'වෙදාර්ථ',
  'නසන්නාය',
  'පාශදණ්ඩා',
  'යුධොද්ගතාඃ',
  'මලපුඩු',
  'වක්',
  'හෝ',
  'දණ්ඩක්',
  'හෝ',
  'ආයුධයක්',
  'හෝ',
  'ගත්',
  'අත්',
  'ඇත්තේය',
  'රතා',
  'ශිත',
  'විජිණෛඃකවස්ත්රානිෂ්ටාභිධායනඃ',
  'රක්තා',
  'ශීත',
  'විජිණෛඃක',
  'වස්ත්ර',
  'රක්ත',
  'කෘෂ්ණ',
  'විජිණී',
  'වූ',
  'එක්',
  'වස්ත්රයක්',
  'හැන්දේය',
  'අනිෂ්ටාභිධායිනා',
  'අනිෂ්ට',
  'වූවාක්',
  'ඇත්තේය',
  'යන',
  'මොහුද',
  'කරාවමදී',
  'අතමඩනේද',
  'මුක්තා',
  'ශ්රැ',
  'මිදූ',
  'කඳුලු',
  'ඇත්තේද',
  'සෙනගභංග',
  'තෙල්',
  'ඇඟ',
  'ගැල්',
  'වුයේද',
  'තෘණච්ඡදඃ',
  'තණකොඳු',
  'කඩායන්නේද',
  'ස්ත්රීන',
  'පුංසකං',
  'ස්ත්රී',
  'ලක්ෂණ',
  'නපුංසක',
  'වූද',
  'ව්යංග',
  'දෙහ',
  'අංග',
  'විකල',
  'වූ',
  'අඩ',
  'පුගුලෝද',
  'සපෘෂ්ඨපාණයඃ',
  'පිට',
  'අත',
  'බැඳ',
  'යන්නාහුද',
  'ඛර',
  'කොටළුය',
  'උෂ්ටු',
  'ඔටුය',
  'මහිෂ',
  'මිය',
  'යන',
  'මොවුන්ට',
  'ආරූඪ',
  'නැංගාහුද',
  'මූග',
  'ගොළුය',
  'ගර්භාදි',
  'භාෂිනඃ',
  'විලාපාදි',
  'බස්',
  'ඇත්තෝය',
  'යන',
  'එතෙදුතාඃ',
  'මේ',
  'අරිෂ්ට',
  'දූතයෝ',
  'විරුධන්තෙ',
  'විරුද්ධ',
  'වෙත්',
  'නොහොත්',
  'වෛද්යාචාරීන්',
  'විසින්',
  'වළකනු',
  'ලැබෙත්',
  'විපර්යයාඃ',
  'මෙකී',
  'ලක්ෂණයන්ට',
  'විපර්යාස',
  'වූවාහු',
  'ප්රශස්තෘ',
  'පසස්නා',
  'ලද්දාහුයි',
  'සමහර',
  'පොතක',
  'මත්තං',
  'තෛලාවලිනං',
  'භුජග',
  'මභිමුඛං',
  'මුක්ත',
  'කෙ',
  'සංචනග්නම්',
  'වෘද්ධාන්ධාන්',
  'ජින්න',
  'නායං',
  'ජටම්',
  'කුටධරාන්',
  'වංචකාලි',
  'ප්රලාපාන්',
  'ශුෂ්ක',
  'කුම්භඤ්ච',
  'කාත්ථං',
  'කලහමභිමුඛං',
  'රක්ත',
  'පුෂ්පඤ්ච',
  'වස්ත්රම්',
  'ප්රස්ථාන',
  'ප්රස්තුතානාං',
  'නව',
  'භවති',
  'ශුභං',
  'නාස්ති',
  'සිද්ධිර්නරාණාම්',
  'යන',
  'මේ',
  'ලකුණු',
  'භිෂ්',
  'ගුත්තමයා',
  'කරා',
  'යන',
  'දූතයා',
  'අධිවේද',
  'හුට',
  'සමඟ',
  'වුනේද',
  'ඉතා',
  'අශුභ',
  'අවමගල්යයක්වේ',
  'සාරාර්ථ',
  'සංග්රහට',
  'නිමිති',
  'ලකුණු',
  'කන්යාගාං',
  'භෙරි',
  'ශංඛා',
  'දධිඵල',
  'කුසුමං',
  'පාවකං',
  'දීප්යමානං',
  'ගංගාතීර',
  'ප්රයුක්තීන්',
  'භය',
  'ගජ',
  'වෘෂභොන්',
  'පුර්ණකුම්භ',
  'ධ්වජාන්වා',
  'උක්ෂිතාව',
  'ව',
  'භූමිං',
  'ජලධර',
  'යුගලං',
  'සුද්ධමන්නං',
  'ජපංවා',
  'වෙශ්යාස්ත්රී',
  'මාංසඛණ්ඩං',
  'ප්රියහිතවචනං',
  'මංගලම්',
  'ප්රස්තුතානාම්',
  'කන්නං',
  'කන්යා',
  'ස්ත්රියක්',
  'හෝ',
  'ගාං',
  'වසුමා',
  'දෙනක්',
  'හෝ',
  'භෙරි',
  'බෙර',
  'හෝ',
  'ශංඛං',
  'සක්',
  'හෝ',
  'ධි',
  'ඵලකුසුමං',
  'දීමධුරඵල',
  'කුසුම',
  'යන',
  'මොවුන්',
  'හෝ',
  'දීප්යමානංබබලන්නා',
  'වූ',
  'පාචකං',
  'ගින්න',
  'හෝ',
  'ගංගා',
  'තීර',
  'ප්රයුක්තාන්',
  'ගංතෙර',
  'යෙදුනා',
  'වූ',
  'භය',
  'අශ්වය',
  'ගජ',
  'හස්තිය',
  'වෘෂ',
  'භාන්',
  'වෘෂභය',
  'යන',
  'මොවුන්',
  'හෝ',
  'පූර්ණකුම්භ',
  'පුන්කලස්ය',
  'ධ්වජාන්',
  'වා',
  'ධිජය',
  'යන',
  'මොවුන්',
  'හෝ',
  'උක්ෂිප්තාවව',
  'භූමිං',
  'සානා',
  'බිමක්',
  'හෝ',
  'ජලධර',
  'යුගලං',
  'මෙඝය',
  'හා',
  'මත්ස්ය',
  'යුගලයක්',
  'හෝ',
  'සුද්ධ',
  'මන්තං',
  'සුද්ධාහාර',
  'හෝ',
  'ජපං',
  'ව',
  'මන්ත්රාධ්යයන',
  'යක්',
  'හෝ',
  'වේශ්යාස්ත්රී',
  'වෙසඟ',
  'නක්',
  'හෝ',
  'මාංශඛණ්ඩං',
  'මස්',
  'කැබල්ලක්',
  'හෝ',
  'ප්රියහිත',
  'වචනං',
  'ප්රිය',
  'හිත',
  'වචනයක්',
  'හෝ',
  'ප්රස්තුතානාං',
  'ගමනාරම්භ',
  'කළවුන්ට',
  'මංගලං',
  'මංගලයක්',
  'වේ',
  'වාමතඃ',
  'ශකුණො',
  'යාති',
  'දීර්ඝා',
  'වාමං',
  'ප්රයාතිච',
  'ශුක',
  'කාක',
  'කපොතාව',
  'දක්ෂිණාං',
  'යාන්ති',
  'වෙත්',
  'ශුභම්',
  'සමහර',
  'පොතක',
  'භෙරි',
  'මෘදංග',
  'මෘදුම',
  'දීලශංඛ',
  'වීණා',
  'වෙණුධව',
  'නීම්',
  'කර',
  'කුණ්ඩල',
  'භීති',
  'ඝොෂාඃ',
  'පුත්රාවිතා',
  'ච',
  'යුවතී',
  'සුරහෘසවත්සදො',
  'තාම්බරව',
  'රජ',
  'කො',
  'භිමුඛා',
  'ප්රශස්තාඃ',
  'හෙරි',
  'බෙරය',
  'මෘදංග',
  'මිහිඟු',
  'බෙරය',
  'මෘදුමර්දල',
  'මෘදුම',
  'දීල',
  'නම්',
  'වාද්ය',
  'භෙදය',
  'ශංඛ',
  'සක්ය',
  'වීණා',
  'වීණාය',
  'වෙණු',
  'ධධ්වනී',
  'කුලල්',
  'බට',
  'ආදීන්',
  'පිඹීමය',
  'මකරකුණ්ඩල',
  'මත්ස්ය',
  'කුණ්ඩලය',
  'ගීති',
  'ඝොෂා',
  'ගීති',
  'ඝොෂාය',
  'පුත්රාවිතාව',
  'යුවතී',
  'පුත්රයන්',
  'සහිත',
  'ස්ත්රීය',
  'සුරහිඃ',
  'සවත්සා',
  'වස්සා',
  'සහිත',
  'දෙනය',
  'ධෞතොරව',
  'රාජකා',
  'අභිමුඛා',
  'සුදු',
  'වස්ත්ර',
  'ඇති',
  'වහමු',
  'වූ',
  'රජකයා',
  'යන',
  'මොහු',
  'ප්රශස්තෘ',
  'පසස්නා',
  'ලද්දාහ',
  'එහෙයින්',
  'යොගතරංගිනියෙහි',
  'යානෙ',
  'මාතංග',
  'විප්රාස්තුරග',
  'වෘෂඵලච්ඡත්ර',
  'මාංශොදකුම්භා',
  'යොෂිත්',
  'පුත්රාර්ථතාවා',
  'සුරභිරපි',
  'තථා',
  'ඛඤ්ජරීටා',
  'මයුරාඃ',
  'වීණා',
  'හෙරි',
  'මෘදංගාම්බුජ',
  'පටහ',
  'රවා',
  'වෙද',
  'මංගල්යඝොෂා',
  'ශ්වාෂාඃ',
  'සිද්ධාන්ත',
  'භූභෘත්කුසුම්',
  'පුරවධු',
  'චන්දනාදාඃ',
  'ප්රශස්තෘ',
  'ත්රිංශදංගග',
  'ශකුණඃ',
  'ශකුණ',
  'තෙම',
  'වාමතඃ',
  'වාම',
  'දිග්',
  'භාගයෙන්',
  'දකුණු',
  'දිගට',
  'යාති',
  'සේද',
  'දීර්ඝා',
  'දීර්ඝතෙම',
  'වාමං',
  'දකුණු',
  'දිග',
  'සිට',
  'වා',
  'මදිගට',
  'ප්රයා',
  'තිව',
  'යේද',
  'ශුක',
  'ගිරව්ය',
  'කාක',
  'කවුඩුය',
  'කපොතාශ්ව',
  'කො',
  'බෙයිය',
  'යන',
  'මොවුහුද',
  'දක්ෂිණාං',
  'යාන්ති',
  'චෙන්',
  'ඉදින්',
  'දකුණු',
  'දිගට',
  'යෙත්නම්',
  'ශුභමි',
  'යන',
  'ගමනට',
  'යහපත්',
  'වන්නේයි',
  'අංග',
  'ලක්ෂණී',
  'උතුම්',
  'වූ',
  'වෛද්ය',
  'තෙම',
  'ආතුරයාගේ',
  'ඉදිරියෙහි',
  'සිට',
  'මං',
  'නමඃ',
  'ඉහිණිත',
  'කණිමුද්ධ',
  'සිද්ධසේ',
  'ස්වාහඃ',
  'යන',
  'මේ',
  'මන්ත්රය',
  'ජපකොට',
  'බලා',
  'සිටිකල',
  'සංවත්සරං',
  'පාද',
  'පෘෂ්ඨෙ',
  'ෂමාසං',
  'මර්',
  'බන්ධනෙ',
  'ත්රිමාසං',
  'කණිමූලෙ',
  'ච',
  'මාසාඨිත්තූ',
  'ලලාටකෙ',
  'භ්රෑයුගෙම',
  'නවදිනවව',
  'සප්ත',
  'සකන්ධෙ',
  'තථෛවච',
  'පඤ්ච',
  'චක්ෂුෂි',
  'ත්රිණී',
  'නසෞකං',
  'ජිහ්වායාං',
  'නජිවතී',
  'පාද',
  'පෘෂ්ඨෙ',
  'පිටි',
  'පතුල',
  'ගත',
  'ඕහට',
  'සංවත්සරං',
  'අව්රුද්දක්ද',
  'මණි',
  'බන්ධනෙ',
  'වලලු',
  'කර',
  'ගත',
  'ෂනවාසඃ',
  'සමසක්',
  'ද',
  'කණිමූලෙ',
  'කන්මුලගත',
  'ත්රිමාසඃ',
  'තුන්මසක්',
  'ද',
  'ලලාටකෙ',
  'නලළ',
  'ගත',
  'මාසා',
  'ඞීන්තු',
  'අඩ',
  'මසක්',
  'ද',
  'භ්රෑයුගෙම',
  'දෙබැම',
  'ගත',
  'නවදිනඤ්චව',
  'නව',
  'දවසක්',
  'ද',
  'තථා',
  'එව',
  'එසේම',
  'ස්කන්ධෙ',
  'කඳගත',
  'සප්ත',
  'සත්',
  'දවසක්',
  'ද',
  'චක්ෂුෂි',
  'ඇස',
  ...],
 13: ['ධර්ම',
  'ප්රදීපිකාව',
  'නමෝ',
  'තස්ස',
  'භගවතො',
  'අරහතො',
  'සම්මා',
  'සම්බුද්ධස්ස',
  'අප',
  'බුදුන්',
  'සාරාසකි',
  'කප්සුවහස්',
  'මතුයෙහි',
  'කුලුණුනු',
  'වණින්',
  'යුත්',
  'මහත',
  'වු',
  'සක්',
  'වැ',
  'දිවකුරු',
  'බුදුන්',
  'හමුවැ',
  'අතට',
  'පත්',
  'නිවන්',
  'සසර',
  'සේ',
  'පියා',
  'සතුන්',
  'සඳහා',
  'විඳුනා',
  'සසර',
  'දුක්',
  'නිවන්',
  'සේ',
  'ගෙන',
  'භව',
  'දුර්ගයට',
  'වැද',
  'පැරුම්',
  'පුරා',
  'තු',
  'පුර',
  'පැමිණ',
  'දසදහස්',
  'ලෝදාහි',
  'දෙව්බඹුන්ගේ',
  'අයජ',
  'මෙන්',
  'කිඹුල්වත්හි',
  'ඉපද',
  'වැඩිවිය',
  'පැමිණ',
  'මහභිනික්මන්',
  'කොට',
  'පැවිජි',
  'වැ',
  'මහා',
  'වීර්යය',
  'කොට',
  'බොධිපර්යංකාරූඪ',
  'වැ',
  'මාරවිජය',
  'කොට',
  'සර්වඥපදප්රාප්ත',
  'වැ',
  'හුනස්නෙන්',
  'නැඟී',
  'පූර්වොත්තර',
  'දිශා',
  'භාගයෙහි',
  'වැඩ',
  'සිට',
  'සප්තාහයක්',
  'අනිමිසලෝචන',
  'යුගලයෙන්',
  'පුදන',
  'ලද',
  'ජය',
  'මහා',
  'බොධිය',
  'තත',
  'ප්රභව',
  'වූ',
  'ඵල',
  'රුහ',
  'මහා',
  'බොධිය',
  'තදවයව',
  'වූ',
  'ශාඛා',
  'හා',
  'බොධිය',
  'යන',
  'තුන්',
  'මහා',
  'බොධීන්ගේ',
  'වංශයෙහි',
  'සහස්රරශ්මින්',
  'විභක්ත',
  'පදයන්',
  'අතුරෙහි',
  'පරිකථානුකූල',
  'පද',
  'ගෙන',
  'වර්ණනා',
  'කරනු',
  'ලැබේ',
  'යස්ස',
  'යනු',
  'චතුර්විධ',
  'පදයන්',
  'කෙරෙහි',
  'නාමපදයි',
  'එහි',
  'චතුර්විධ',
  'පද',
  'නම්',
  'කවරයත්',
  'නාම',
  'පදය',
  'ආඛ්යාත',
  'පදය',
  'උපසර්ග',
  'පදය',
  'නිපාතපදයි',
  'එහි',
  'නාම',
  'පද',
  'නම්',
  'සර්වාර්ථයන්',
  'නමන්නෙන්',
  'නාම',
  'පද',
  'නම්',
  'වේ',
  'එයින්',
  'කීහ',
  'යත්ත්රිලිංගං',
  'ත්රිවචනං',
  'සර්වාසු',
  'ච',
  'විභක්තිෂු',
  'නමත්යර්ථෙන',
  'සර්වාර්ථා',
  'නාම',
  'කවයො',
  'විදුඃ',
  'යී',
  'ක්රියාවාචක',
  'පද',
  'ආඛ්යාත',
  'නම්',
  'වේ',
  'එයින්',
  'කීහ',
  'යත්ත්රි',
  'කාලං',
  'ත්රිපුරුෂං',
  'ක්රියාවාචි',
  'ත්රිකාරකම්',
  'අත්රිලිංගං',
  'ත්රිවචනං',
  'තදාඛ්යාතං',
  'ප්රවක්ෂතෙ',
  'යී',
  'සාරාසංඛ්ය',
  'ලෝධාහි',
  'ධර්ම',
  'ප්රදීපිකා',
  'ක්රියා',
  'දොතක',
  'පද',
  'උපසර්ග',
  'නම්',
  'වේ',
  'එයින්',
  'කීහ',
  'යස්මාදුප',
  'සෘජන්තයන්',
  'පදස්යාපරි',
  'ගච්ඡති',
  'ක්රියායොග',
  'වහස්ත',
  'ස්මාදුප',
  'සර්ග',
  'ඉති',
  'ස්මෘතඃ',
  'යී',
  'දක්වන',
  'ලද',
  'පදයන්ගේ',
  'ආද්යන්ත',
  'මධ්යයෙහි',
  'නිපතිත',
  'වූ',
  'විචිත්රාර්ථ',
  'පදයෝ',
  'නිපාත',
  'නම්',
  'වෙත්',
  'එයින්',
  'කීහ',
  'යස්මාදාද්යාන්තමධ්යෙෂු',
  'වාක',
  'ප්රයොග',
  'විශෙෂතඃ',
  'නිපතන්ති',
  'විචිත්රාර්ථා',
  'නිපාතාසතුතු',
  'සංඥතාඃ',
  'යි',
  'මේ',
  'චතුර්විධ',
  'පදයන්ගේ',
  'ප්රයෝග',
  'දක්වන්නට',
  'කීහ',
  'පදං',
  'චතුර්විධං',
  'ප්රොක්තං',
  'නාමාඛ්යාතොප',
  'සර්ගජම්',
  'නිපාතජච',
  'ශබ්ද',
  'ඥෙරවඃ',
  'ඛලවභිධාවති',
  'යී',
  'මේය',
  'චතුර්විධ',
  'පද',
  'නම්',
  'නිසිතෙනාව',
  'යන',
  'තන්හි',
  'එව',
  'යන',
  'නිපාතය',
  'අයොග',
  'ව්යවඡදකය',
  'අන්ය',
  'යොග',
  'ව්යවච්ඡේදකය',
  'අත්යන්තා',
  'යොග',
  'ව්යව',
  'ච්ඡේදකය',
  'යි',
  'ත්රිවිධ',
  'වූයේ',
  'අන්ය',
  'යොග',
  'ව්යවච්ඡේදක',
  'වේ',
  'එහි',
  'විශෙෂණයා',
  'කෙරෙන්',
  'පර',
  'කොට',
  'ප්රයෝග',
  'කරන',
  'ලද',
  'එවකාරය',
  'අයොග',
  'ව්යවච්ඡේදක',
  'වෙයි',
  'චෛත්රො',
  'ධනුර්ධර',
  'එව',
  'යන',
  'තන්හි',
  'සෙයින්',
  'විශෙෂයා',
  'කෙරෙන්',
  'පර',
  'කොට',
  'ප්රයෝග',
  'කරන',
  'ලද',
  'එව',
  'කාරය',
  'අන්ය',
  'යොග',
  'ව්යවච්ඡේදක',
  'වෙයි',
  'පාර්ථි',
  'එව',
  'ධනුද්ධරඃ',
  'යන',
  'තන්හි',
  'සෙයින්ක්රියායෙන්',
  'පර',
  'කොට',
  'ප්රයොග',
  'කරන',
  'ලද',
  'එව',
  'කාරය',
  'අත්යන්තා',
  'යොග',
  'ව්යවච්ඡේදක',
  'වෙයි',
  'නීලං',
  'සරොජම',
  'සෙත්යව',
  'යන',
  'තන්හි',
  'සෙයින්වාක්යයන්',
  'ව්යවච්ඡේද',
  'ඵල',
  'වන',
  'බැවින්',
  'නිපාතයා',
  'ප්රයෝග',
  'නොකළද',
  'විවක්ෂා',
  'වශයෙන්',
  'ඔහුගේ',
  'අර්ථ',
  'ප්රතීත',
  'වේ',
  'මැයි',
  'එයින්',
  'කීහ',
  'ධර්ම',
  'කීර්තිපාදයෝ',
  'අයොගං',
  'යොගම',
  'පරෛරත්යන්තා',
  'යොග',
  'මෙව',
  'ච',
  'ව්යවච්ඡිනත්ති',
  'ධර්මස්ය',
  'නිපාතො',
  'ව්යතිරෙචකඃ',
  'විශේෂණ',
  'විශේෂ්යාභ්යා',
  'ක්රියයා',
  'ච',
  'සහොදිතඃ',
  'විවක්ෂාතො',
  'ප්රයොගෙ',
  'පි',
  'තයාර්ථෙ',
  'යං',
  'ප්රතීයතෙ',
  'ව්යවච්ඡෙද',
  'ඵලං',
  'වාක්යං',
  'යතා',
  'චිත්රො',
  'ධනුද්ධරඃ',
  'පාථො',
  'ධනුර්ධරො',
  'නීලං',
  'සරොජමස්ති',
  'වා',
  'යථා',
  'සරොජමිති',
  'යන',
  'පාඨය',
  'මෙහි',
  'පුර්වොක්තිය',
  'හා',
  'නොගැළපේ',
  'අහීස',
  'මාධි',
  'කථා',
  'ප්රතියොග',
  'ව්යවච්ඡෙදස්තත්රාප්යර්වෙෂු',
  'ගම්යතෙ',
  'තථා',
  'ප්රසිද්ධෙස්සා',
  'ධර්මර්ෂ්යාවක්ෂානුගමානෝ',
  'යී',
  'පත්තෝ',
  'සබ්බඤ්ඤැතං',
  'සත්ථා',
  'යනුයෙන්',
  'දක්වන',
  'ලද',
  'බුදුහු',
  'අනන්තා',
  'පරිමාණ',
  'ගුණ',
  'ඇතියෝ',
  'කිසේය',
  'යත්',
  'බුදුහු',
  'රූප',
  'විලාසයෙනුදු',
  'වචන',
  'විලාසයෙනුදු',
  'ඥාන',
  'විලාසයෙනුදු',
  'අචින්ත්යයහ',
  'අවාච්යයහ',
  'අතුල්යහ',
  'අවෙද්යයෝයි',
  'එව්හු',
  'අචින්ත්ය',
  'වන',
  'බැවින්',
  'චින්තා',
  'විෂයාතික්රාන්තයහ',
  'අවාච්ය',
  'වන',
  'බැවින්',
  'වාග්',
  'විෂයාතික්රාන්ත',
  'සහ',
  'අතුල්ය',
  'වන',
  'බැවින්',
  'උපමා',
  'විෂයාතික්රාන්තයහ',
  'අද',
  'වන',
  'බැවින්',
  'ඥාන',
  'විෂයාතික්රාන්තයහ',
  'කපකුදු',
  'වූ',
  'දවස්',
  'තම',
  'සේම',
  'වූ',
  'බුදු',
  'කෙනෙකුනුදු',
  'කියත්',
  'නොගෙවෙන',
  'ගුණ',
  'ඇතියෝ',
  'මහ',
  'මුහුදැ',
  'හෙළූ',
  'සිදුහතුළුදු',
  'කළ',
  'සැළදු',
  'තම',
  'තමා',
  'පමණින්',
  'දියගන්නා',
  'සේ',
  'ඒ',
  'බුදු',
  'රජහුගේ',
  'ගුණ',
  'මුහුදට',
  'වන්',
  'පසේ',
  'බුදුහුදු',
  'බුදු',
  'සවෝද',
  'තම',
  'තමන්ගේ',
  'නුවණ',
  'පමණින්',
  'ගන්ති',
  'ගුණ',
  'පමණින්',
  'ගන්නට',
  'නොනිසෝ',
  'ගංගාය',
  'වාලුකා',
  'බීයෙ',
  'උදකං',
  'ඛීයෙ',
  'මහණ්ණ',
  'වෙ',
  'මහියා',
  'මත්තිකා',
  'ඛීයෙ',
  'ලක්ඛෙන',
  'මම',
  'බුද්ධියා',
  'යී',
  'ඥානගර්ජනා',
  'කරන්නට',
  'සමර්ථ',
  'වූ',
  'ධර්ම',
  'සෙනෙවි',
  'සැරියුත්',
  'මහතෙ',
  'රුන්',
  'වැනි',
  'මහා',
  'පුරුෂයනටත්',
  'අවිෂය',
  'වූ',
  'බුදු',
  'ගුණ',
  'පුහුදුන්',
  'වැ',
  'කියම්',
  'හයි',
  'සිතනු',
  'මදුරු',
  'දළින්',
  'විදුරු',
  'ගිරි',
  'විදුනාක්',
  'පින',
  'හැඹිළි',
  'දළින්',
  'මහ',
  'පොළොව',
  'උකුල්',
  'දෙනුවක්',
  'වැනි',
  'බැවින්',
  'තම',
  'හට',
  'අවිෂය',
  'වතුදු',
  'ප්රසාද',
  'පරවශ',
  'වැ',
  'ප්රවචන',
  'වහල්',
  'කොට',
  'ශ්රද්ධා',
  'බුද්ධි',
  'සම්පන්නජනයන්',
  'සඳහා',
  'කතිපය',
  'ගුණයෙක්',
  'දක්වනු',
  'ලැබේ',
  'බුදුන්ගේ',
  'ගුණයෙහි',
  'පුහුදුනන්',
  'හාද',
  'සව්පසේ',
  'බුදුන්',
  'හාද',
  'සාධා',
  'රණ',
  'ගුණයෝ',
  'ඇත්මය',
  'අසාධාරණ',
  'ගුණයෝ',
  'ඇත්මැයි',
  'එහි',
  'සෙසු',
  'තිරිසනුන්',
  'හා',
  'සාධාරණ',
  'තණ',
  'කබල',
  'ගඳැත්කුස',
  'දිරුණ',
  'සිව්',
  'දෑ',
  'ගඳ',
  'වන',
  'සෙයින්',
  'පුහුදුන්',
  'ආදීන්',
  'හා',
  'සාධාරණ',
  'වූ',
  'රූපශොභාද',
  'ධ්යානාභි',
  'ඥාදි',
  'ගුණයෝද',
  'බුදු',
  'සතන්හිලා',
  'අසාධාරණ',
  'වෙති',
  'නොරබීජ',
  'නෙහි',
  'නොසිටුනා',
  'සිංහ',
  'තෙල්',
  'සෙයින්',
  'දශබල',
  'චතුර්වෛශාරද්යාදි',
  'අසාධාරණ',
  'ගුණයෝ',
  'වූ',
  'කල',
  'නොබුදු',
  'සතන්හි',
  'ලා',
  'නොසිටිත්',
  'ඔවුන්ගේ',
  'රූප',
  'විලාස',
  'නම්',
  'කවරයත්',
  'ද්වාත්රිංශන්මහා',
  'පුරුෂ',
  'ලක්ෂණයෙන්',
  'හා',
  'අශීති',
  'අනුව්යංජනයෙන්',
  'ප්රජ්වලිත',
  'රූප',
  'ශොභායි',
  'එහි',
  'ද්වාත්රිංගන්',
  'මහා',
  'පුරුෂ',
  'ලක්ෂණ',
  'නම්',
  'කවරයත්',
  'වදාළේ',
  'මැනො',
  'බුදුන්',
  'විසින්',
  'සුප්පතිටඨිත',
  'පාදො',
  'හෙට්ඨාපාදතලෙසු',
  'චක්කානි',
  'ජාතානී',
  'සහ',
  'සාරානී',
  'සනෙමිකානි',
  'සනාභිකානි',
  'සබ්බාකාර',
  'පරිපුරානි',
  'ආයත',
  'තෙසු',
  'ධර්ම',
  'ප්රදීපිකා',
  'පණහි',
  'දීඝගුලි',
  'මුදු',
  'තලු',
  'නහත්ථ',
  'පාදො',
  'ජාල',
  'හත්ථපාදො',
  'උස්සං',
  'ඛපාදො',
  'එණිජංඝො',
  'ඨිතකා',
  'අනොනිමන්තො',
  'උභොහි',
  'පාණී',
  'තලෙහි',
  'ජෂ්ණුකානි',
  'පරිමසති',
  'පරිමජ්ජතිකොසොහිතවත්ථගු',
  'හ',
  'සුවණ්ණවණ්ණො',
  'කඤචන',
  'සන්නිභත්තචො',
  'සුඛුමච්ඡවි',
  'වි',
  'සුඛුමන්තා',
  'ඡවියා',
  'රජො',
  'ජල්ලං',
  'කායෙ',
  'න',
  'උපලිප්පති',
  'එකෙක',
  'රජොජල්ලං',
  'ලොමො',
  'එකෙකානි',
  'ලොමානි',
  'ලොමකූපෙසු',
  'ජාතානි',
  'උඩග්ග',
  'ලොමො',
  'උද්ධග්ගානි',
  'ලොමානි',
  'ජාතානි',
  'නිලානි',
  'අඤ්ජන',
  'වණ්ණානි',
  'කුණ්ඩ',
  'ලාවත්තානි',
  'පදක්ඛිණාවත්තක',
  'ජාතානි',
  'බ්රහ්මුජ්ජුගත්තො',
  'සත්තු',
  'සීහ',
  'පුබ්බකායො',
  'චිතන්තරංසො',
  'නිග්රොධ',
  'පරිමණ්ඩ',
  'ලො',
  'යාවතඣස්ස',
  'කායො',
  'තාවතස්ස',
  'ව්යාමො',
  'යාවතස්ස',
  'ව්යාමො',
  'තාවතඤස්ස',
  'කායො',
  'සමවත්තක්ඛන්ධො',
  'රසග්ගසග්ගි',
  'සීහහනු',
  'චත්තාලීසදනෙන්තො',
  'සමදන්තො',
  'අවිවර',
  'දන්තො',
  'සුසුක්කදාඨො',
  'පහූත',
  'ජි',
  'වෙහා',
  'බ්රහ්මස්සරෝ',
  'කරවීකභාණී',
  'අභිනීල',
  'නෙත්තො',
  'ගොපඛුමො',
  'උණ්ණා',
  'භමුකන්තරෙ',
  'ජාතා',
  'ඔදාතා',
  'මුදුතු',
  'ලසන්නිභා',
  'උණහීස',
  'සීසො',
  'යී',
  'මෙහි',
  'සුප්පතිටඨිතපාදො',
  'යන',
  'තන්හි',
  'සුප්රතිෂ්ඨිතපාදතා',
  'නම්',
  'කවරයත්',
  'අනුන්',
  'පතුල්',
  'බිම',
  'ඔබන',

In [50]:
len(century_tokens[5])

1062

In [51]:
len(list(set(century_tokens[5])))

775

In [52]:
len(century_tokens[13])

10932

In [53]:
len(list(set(century_tokens[13])))

5698

In [54]:
len(century_tokens[14])

5937

In [55]:
len(list(set(century_tokens[14])))

3212

In [56]:
len(century_tokens[15])

6607

In [57]:
len(list(set(century_tokens[15])))

3698

In [58]:
len(century_tokens[18])

3909

In [59]:
len(list(set(century_tokens[18])))

2152

In [60]:
len(century_tokens[19])

11214

In [61]:
len(list(set(century_tokens[19])))

6119

In [62]:
len(century_tokens[20])

18366

In [63]:
len(list(set(century_tokens[20])))

8171

In [64]:
# Get total frequency of each word per century
freq_by_century = {
    century: Counter(tokens)
    for century, tokens in century_tokens.items()
}

# Create a DataFrame: rows = words, columns = centuries
freq_df = pd.DataFrame(freq_by_century).fillna(0).astype(int)

In [65]:
freq_df

              5   13  14  15  18  19  20
සාරාර්ථ        4   0   0   0   0   0   1
සංග්රඥාව       1   0   0   0   0   0   0
තමස්ත          1   0   0   0   0   0   0
භගවතෙහිත       1   0   0   0   0   0   0
සම්යක්         2   1   7   0   2   5   2
...           ..  ..  ..  ..  ..  ..  ..
අසලැ           0   0   0   0   0   0   1
නොතිබුණායින්   0   0   0   0   0   0   1
උදයැ           0   0   0   0   0   0   1
වැඩුයේ         0   0   0   0   0   0   1
හිරමනයෙන්      0   0   0   0   0   0   1

[22837 rows x 7 columns]

In [66]:
freq_df.loc['නිදහසේ']

5     0
13    0
14    0
15    0
18    0
19    0
20    8
Name: නිදහසේ, dtype: int64

In [67]:
freq_df[20].describe()

count    22837.000000
mean         0.804221
std          3.799976
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max        236.000000
Name: 20, dtype: float64

In [68]:
zscore_df = freq_df.copy()
zscore_df = (freq_df - freq_df.mean()) / freq_df.std(ddof=0)

In [69]:
zscore_df.loc['නිදහසේ']

5    -0.132369
13   -0.184565
14   -0.141752
15   -0.142622
18   -0.129702
19   -0.239043
20    1.893679
Name: නිදහසේ, dtype: float64

In [70]:
zscore_df.head()

,5,13,14,15,18,19,20
සාරාර්ථ,11.253384,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,0.051522
සංග්රඥාව,2.714069,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,-0.211643
තමස්ත,2.714069,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,-0.211643
භගවතෙහිත,2.714069,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,-0.211643
සම්යක්,5.560507,0.200992,3.675042,-0.142622,1.385779,2.194979,0.314688

In [71]:
zscore_df.to_csv("Z_Scores.csv")

In [72]:
def compute_coverage(zscores, lower=-1.5, upper=1.5):
    total = zscores.size
    within = ((zscores > lower) & (zscores < upper)).sum().sum()
    return within / total

In [73]:
coverage = compute_coverage(zscore_df, lower=float('-inf'), upper=6.1027)

In [74]:
print(f"Coverage for z ∈ [-1.5, 1.5]: {coverage*100:.2f}%")

Coverage for z ∈ [-1.5, 1.5]: 99.80%

In [75]:
# typical_words = {
#     century: zscore_df[
#         zscore_df[century].between(-1.5, 1.5)
#     ].index.tolist()
#     for century in zscore_df.columns
# }

In [76]:
# typical_words

In [77]:
# len(typical_words[5])

In [78]:
distinctive_words = {
    century: zscore_df[
        ~zscore_df[century].between(float('-inf'), 6.1027)
    ].sort_values(by=century, ascending=False).index.tolist()
    for century in zscore_df.columns
}

In [79]:
distinctive_words

{5: ['හෝ',
  'වූ',
  'ලක්ෂණය',
  'යන',
  'මේ',
  'ද',
  'ව්යාධි',
  'නම්',
  'කීහ',
  'අංග',
  'දෙහ',
  'දොෂ',
  'ලක්ෂණ',
  'විසින්',
  'ගත',
  'දූත',
  'ව්යංග',
  'සම්පත්ය',
  'සාරාර්ථ',
  'දවසක්',
  'හට',
  'වෛද්ය',
  'රස',
  'දක්ෂ',
  'පාද',
  'භය',
  'දකුණු',
  'වීණා',
  'මොවුන්',
  'භෙරි',
  'පොතක',
  'සමහර',
  'ප්රශස්තෘ',
  'සකල',
  'සහිත',
  'තෙම',
  'එසේම',
  'තථා',
  'ලද',
  'වෙද',
  'ලක්ෂණම්',
  'ශාස්ත්රය',
  'කාල',
  'ප්රකෘති',
  'ආරොග්ය',
  'සත්ව',
  'උතුම්'],
 13: ['වූ',
  'නම්',
  'යන',
  'ච',
  'යැ',
  'ය',
  'වැ',
  'ඇති',
  'ති',
  'ද',
  'නැමැති',
  'සේ',
  'විසින්',
  'හෙයින්',
  'ඒ',
  'මේ',
  'මහා',
  'ලද',
  'වෙයි',
  'යි',
  'හා',
  'කොට',
  'වේ',
  'කල්හි',
  'නිවන්',
  'බුදුන්',
  'මහ',
  'නො',
  'හෝ',
  'බැවින්',
  'වන',
  'යනු',
  'වා',
  'මනා',
  'තන්හි',
  'න',
  'වහන්සේ',
  'බුදු',
  'සෙයින්',
  'තෙන',
  'වැනි',
  'යී'],
 14: ['වූ',
  'ඒ',
  'නම්',
  'කොට',
  'විසින්',
  'වහන්සේ',
  'ලද',
  'මේ',
  'ඇති',
  'හා',
  'කල්හි',
  'දෙසන',
  'දැක',
  'මහ',
  'මහා',
  'යන',
  'එහි',
  'හෙයින්',
  'නුවර',
  'ධර්ම',
  'බුදුන්',
  'ශ්රී',
  'යනාදීන්',
  'ගොස්',
  'ලද්දේද',
  'සේක',
  'වඩනා',
  'හැර',
  'වැඩ',
  'පමණ',
  'බුද්ධ',
  'සර්වඥයන්',
  'ලක්ෂයක්',
  'යි',
  'දහසක්',
  'රජ',
  'කරවා',
  'දී',
  'යයි'],
 15: ['වූ',
  'කොට',
  'ර',
  'ද',
  'ස',
  'මේ',
  'හා',
  'නම්',
  'ලද',
  'ත',
  'සඳ',
  'තොප',
  'යන',
  'වැනි',
  'ල',
  'නමැති',
  'මෙන්',
  'ගුණ',
  'ඳ',
  'ඇති',
  'කරණ',
  'කර',
  'සැප',
  'හෙවත්',
  'සහ',
  'ණ',
  'ඇත්තා',
  'වේ'],
 18: ['වූ',
  'යන',
  'වේ',
  'කියාවේ',
  'තන්හි',
  'නම්',
  'සූත්රයෙන්',
  'මේ',
  'හට',
  'කියා',
  'කියාද',
  'ඇති',
  'ඒ',
  'ද',
  'යයි',
  'තෙම',
  'කල්හි',
  'ලක්ෂණයි',
  'විසින්',
  'ජ්වරය',
  'ලොප්',
  'පූර්ව',
  'ස්වර',
  'කොට',
  'ලකුණු',
  'කළ',
  'යනු',
  'ඉධ',
  'මෙම',
  'වීම',
  'වෘත්ත',
  'සුත්රයෙන්',
  'මෙකී',
  'කරා',
  'බුද්ධ',
  'හා',
  'හෙයින්',
  'තැන',
  'බව',
  'සංඥා',
  'ස්වරයා',
  'පැමිණ',
  'කළමනා',
  'සිටි'],
 19: ['වූ',
  'ඒ',
  'නම්',
  'න',
  'ද',
  'මේ',
  'කළ',
  'කොට',
  'විසින්',
  'කරණ',
  'යන',
  'තෙමේ',
  'ති',
  'ට',
  'කියා',
  'ස',
  'ලද',
  'තං',
  'විබත්',
  'වහන්සේ',
  'එක',
  'බව',
  'යනු',
  'හා',
  'මම',
  'පිණිස',
  'ක',
  'ලෙස',
  'රජ',
  'විය',
  'බස',
  'ඇති',
  'යයි',
  'පව්',
  'කී',
  'මට',
  'සේක',
  'නැති',
  'ඔහු',
  'මෙම',
  'ධම්මං',
  'ඉතා',
  'මා',
  'ච',
  'ඉති',
  'සහ',
  'පන',
  'නමුත්',
  'දී',
  'පොත්',
  'සිංහල',
  'මගේ',
  'ගෙණ',
  'සඳ',
  'එම',
  'සබ්බ',
  'ගේ',
  'ය',
  'නිසා',
  'කරන',
  'එවං',
  'කියන',
  'හි',
  'විභක්ති',
  'මහා'],
 20: ['වූ',
  'ද',
  'ඒ',
  'මේ',
  'යන',
  'නම්',
  'යනු',
  'යි',
  'වේ',
  'නො',
  'කොට',
  'බව',
  'ලද',
  'ය',
  'විසින්',
  'එ',
  'ට',
  'ම',
  'යයි',
  'යුතු',
  'යැ',
  'මැ',
  'අ',
  'හා',
  'ආදි',
  'වන',
  'ඇති',
  'න',
  'මෙහි',
  'කරණ',
  'හෙයින්',
  'සේ',
  'වී',
  'ගේ',
  'මෙ',
  'මෙන්',
  'එක',
  'ආ',
  'ක්',
  'හෝ',
  'වෙයි',
  'ගුණ',
  'කියන',
  'පද',
  'ගත',
  'නා',
  'කර',
  'ර',
  'මහා',
  'කී',
  'කළ',
  'ච',
  'රජ',
  'එහි',
  'ක',
  'බැවින්',
  'වැ',
  'ව්යාකරණ',
  'යී',
  'කියා',
  'වා']}

In [80]:
distinctive_words[20]

['වූ',
 'ද',
 'ඒ',
 'මේ',
 'යන',
 'නම්',
 'යනු',
 'යි',
 'වේ',
 'නො',
 'කොට',
 'බව',
 'ලද',
 'ය',
 'විසින්',
 'එ',
 'ට',
 'ම',
 'යයි',
 'යුතු',
 'යැ',
 'මැ',
 'අ',
 'හා',
 'ආදි',
 'වන',
 'ඇති',
 'න',
 'මෙහි',
 'කරණ',
 'හෙයින්',
 'සේ',
 'වී',
 'ගේ',
 'මෙ',
 'මෙන්',
 'එක',
 'ආ',
 'ක්',
 'හෝ',
 'වෙයි',
 'ගුණ',
 'කියන',
 'පද',
 'ගත',
 'නා',
 'කර',
 'ර',
 'මහා',
 'කී',
 'කළ',
 'ච',
 'රජ',
 'එහි',
 'ක',
 'බැවින්',
 'වැ',
 'ව්යාකරණ',
 'යී',
 'කියා',
 'වා']

In [81]:
len(distinctive_words[5])

47

In [82]:
len(distinctive_words[13])

42

In [83]:
len(distinctive_words[14])

39

In [84]:
len(distinctive_words[15])

28

In [85]:
len(distinctive_words[18])

44

In [86]:
len(distinctive_words[19])

65

In [87]:
len(distinctive_words[20])

61

In [88]:
zscore_df.head()

,5,13,14,15,18,19,20
සාරාර්ථ,11.253384,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,0.051522
සංග්රඥාව,2.714069,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,-0.211643
තමස්ත,2.714069,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,-0.211643
භගවතෙහිත,2.714069,-0.184565,-0.141752,-0.142622,-0.129702,-0.239043,-0.211643
සම්යක්,5.560507,0.200992,3.675042,-0.142622,1.385779,2.194979,0.314688

In [89]:
zscore_dict_cen = zscore_df[19].to_dict()

In [90]:
word_scores = sorted(zscore_dict_cen.items(), key = lambda item: item[1], reverse=True)

In [91]:
with open("stopwords_19th.txt", "w", encoding="utf-8") as f:
    for word, score in word_scores:
        f.write(f"{word}\t{score:.4f}\n")

In [92]:
distinctive_words[5]

['හෝ',
 'වූ',
 'ලක්ෂණය',
 'යන',
 'මේ',
 'ද',
 'ව්යාධි',
 'නම්',
 'කීහ',
 'අංග',
 'දෙහ',
 'දොෂ',
 'ලක්ෂණ',
 'විසින්',
 'ගත',
 'දූත',
 'ව්යංග',
 'සම්පත්ය',
 'සාරාර්ථ',
 'දවසක්',
 'හට',
 'වෛද්ය',
 'රස',
 'දක්ෂ',
 'පාද',
 'භය',
 'දකුණු',
 'වීණා',
 'මොවුන්',
 'භෙරි',
 'පොතක',
 'සමහර',
 'ප්රශස්තෘ',
 'සකල',
 'සහිත',
 'තෙම',
 'එසේම',
 'තථා',
 'ලද',
 'වෙද',
 'ලක්ෂණම්',
 'ශාස්ත්රය',
 'කාල',
 'ප්රකෘති',
 'ආරොග්ය',
 'සත්ව',
 'උතුම්']

In [93]:
first_10_words_per_century = {
    century: words[:10] for century, words in distinctive_words.items()
}

In [94]:
first_10_words_per_century

{5: ['හෝ', 'වූ', 'ලක්ෂණය', 'යන', 'මේ', 'ද', 'ව්යාධි', 'නම්', 'කීහ', 'අංග'],
 13: ['වූ', 'නම්', 'යන', 'ච', 'යැ', 'ය', 'වැ', 'ඇති', 'ති', 'ද'],
 14: ['වූ', 'ඒ', 'නම්', 'කොට', 'විසින්', 'වහන්සේ', 'ලද', 'මේ', 'ඇති', 'හා'],
 15: ['වූ', 'කොට', 'ර', 'ද', 'ස', 'මේ', 'හා', 'නම්', 'ලද', 'ත'],
 18: ['වූ',
  'යන',
  'වේ',
  'කියාවේ',
  'තන්හි',
  'නම්',
  'සූත්රයෙන්',
  'මේ',
  'හට',
  'කියා'],
 19: ['වූ', 'ඒ', 'නම්', 'න', 'ද', 'මේ', 'කළ', 'කොට', 'විසින්', 'කරණ'],
 20: ['වූ', 'ද', 'ඒ', 'මේ', 'යන', 'නම්', 'යනු', 'යි', 'වේ', 'නො']}

In [95]:
union_words = {word for words_list in distinctive_words.values() for word in words_list}

In [96]:
sorted_union = sorted(
    union_words,
    key=lambda word: zscore_df.loc[word].mean(),
    reverse=True
)

In [97]:
sorted_union

['වූ',
 'නම්',
 'යන',
 'ඒ',
 'මේ',
 'ද',
 'කොට',
 'විසින්',
 'ඇති',
 'ලද',
 'වේ',
 'හෝ',
 'හා',
 'න',
 'යනු',
 'ච',
 'ය',
 'වහන්සේ',
 'කළ',
 'හට',
 'හෙයින්',
 'ලක්ෂණය',
 'මහා',
 'බව',
 'යයි',
 'යි',
 'කියා',
 'කරණ',
 'කල්හි',
 'සේ',
 'ස',
 'ති',
 'යැ',
 'මහ',
 'ර',
 'වන',
 'තන්හි',
 'එක',
 'තෙම',
 'නො',
 'මෙන්',
 'එහි',
 'පිණිස',
 'බුද්ධ',
 'ගුණ',
 'වැ',
 'මෙහි',
 'කර',
 'රජ',
 'මා',
 'ට',
 'ම',
 'පූර්ව',
 'වෙයි',
 'උතුම්',
 'කීහ',
 'යුතු',
 'වා',
 'දැක',
 'ගත',
 'බුදුන්',
 'ක',
 'සඳ',
 'ධර්ම',
 'දී',
 'නැමැති',
 'කියන',
 'ලක්ෂණ',
 'කී',
 'පද',
 'සකල',
 'සූත්රයෙන්',
 'විය',
 'කියාවේ',
 'වැනි',
 'සිටි',
 'ශ්රී',
 'වී',
 'මෙ',
 'නැති',
 'සහ',
 'තං',
 'අ',
 'එ',
 'ගේ',
 'හි',
 'රස',
 'වැඩ',
 'එම',
 'සහිත',
 'ලෙස',
 'මම',
 'තෙමේ',
 'හැර',
 'කියාද',
 'ආදි',
 'ත',
 'බැවින්',
 'ණ',
 'ඉතා',
 'හෙවත්',
 'ල',
 'පැමිණ',
 'අංග',
 'ඉති',
 'ව්යාධි',
 'සර්වඥයන්',
 'කරා',
 'නමැති',
 'සේක',
 'නුවර',
 'පමණ',
 'ලකුණු',
 'මෙම',
 'ගෙණ',
 'මැ',
 'එසේම',
 'යී',
 'කරන',
 'පන',
 'තැන',
 'තථා',
 'පාද',
 'ඔහු',
 'නා',
 'නිසා',
 'දොෂ',
 'යනාදීන්',
 'ගොස්',
 'බුදු',
 'ආ',
 'තෙන',
 'මට',
 'දෙහ',
 'නිවන්',
 'වෛද්ය',
 'දවසක්',
 'සමහර',
 'ඉධ',
 'ඳ',
 'සැප',
 'සත්ව',
 'වෙද',
 'බස',
 'විබත්',
 'ස්වර',
 'කාල',
 'ලක්ෂයක්',
 'භය',
 'ශාස්ත්රය',
 'දූත',
 'සංඥා',
 'සිංහල',
 'දෙසන',
 'ලොප්',
 'සාරාර්ථ',
 'තොප',
 'නමුත්',
 'දක්ෂ',
 'මොවුන්',
 'ව්යංග',
 'සම්පත්ය',
 'ලක්ෂණයි',
 'වීම',
 'එවං',
 'මනා',
 'මෙකී',
 'පව්',
 'ජ්වරය',
 'පොත්',
 'ප්රකෘති',
 'මගේ',
 'ධම්මං',
 'වඩනා',
 'ක්',
 'පොතක',
 'දකුණු',
 'වීණා',
 'සබ්බ',
 'සෙයින්',
 'කරවා',
 'ස්වරයා',
 'ආරොග්ය',
 'භෙරි',
 'ලක්ෂණම්',
 'ප්රශස්තෘ',
 'විභක්ති',
 'ඇත්තා',
 'දහසක්',
 'වෘත්ත',
 'ලද්දේද',
 'ව්යාකරණ',
 'සුත්රයෙන්',
 'කළමනා']

In [98]:
len(sorted_union)

194

In [99]:
data_for_df = {}

for century, words_list in distinctive_words.items():
    availability_list = []
    for word in sorted_union:
        if word in words_list:
            availability_list.append(1)  # 1 for present
        else:
            availability_list.append(0)  # 0 for not present
    
    # Add the list of 1s and 0s to the dictionary
    data_for_df[century] = availability_list

In [100]:
availability_df = pd.DataFrame(data_for_df, index=sorted_union)

In [101]:
availability_df

           5   13  14  15  18  19  20
වූ          1   1   1   1   1   1   1
නම්         1   1   1   1   1   1   1
යන          1   1   1   1   1   1   1
ඒ           0   1   1   0   1   1   1
මේ          1   1   1   1   1   1   1
...        ..  ..  ..  ..  ..  ..  ..
වෘත්ත       0   0   0   0   1   0   0
ලද්දේද      0   0   1   0   0   0   0
ව්යාකරණ     0   0   0   0   0   0   1
සුත්රයෙන්   0   0   0   0   1   0   0
කළමනා       0   0   0   0   1   0   0

[194 rows x 7 columns]

In [102]:
availability_df.to_csv('Stopwords_Distribution.csv', index=True)